---
title: Blog Content List
subtitle: Guide Map of Blog Contents 
description: |
  As the number of blog topics increased, it became difficult to organize the contents. In order to increase content accessibility and to look at the relevance of blogs, links to the content list by topic are listed.
categories:
  - All List
author: Kwangmin Kim
date: 01/01/3000
format: 
  html:
    page-layout: full
    code-fold: true
---

:::{.callout-note}
* Scalars are denoted with a lower-case letter (ex a ) or a non-bolded lower-case Greek letter (ex $\alpha$ ).
* Vectors are denoted using a bold-faced lower-case letter (ex $\mathbf a$).
* Matrices are denoted using a bold-faced upper-case letter (ex $\mathbf A$, $\mathbf \phi$) or a bold-faced upper-case Greek letter (ex $\mathbf \Phi$).
* Tensors are denoted using a bold-faced upper-case letter with multiple subscripts or superscripts, indicating the number of indices and the dimensions of the tensor along each axis. 
  * A second-order tensor (also known as a matrix) $\mathbf A$ with dimensions $n \times m$ can be represented as: 
  $\mathbf A_{ij}$ where $i = 1,\dots,m$ and $j = 1,\dots,n$, which are the indices that run over the rows and columns of the matrix, respectively. 
  * A third-order tensor $T$ with dimensions $n \times m \times p$ can be represented as:
   $\mathbf A_{ijk}$ where $i = 1,\dots,m$, $j = 1,\dots,n$, which are $i$, and $k = 1,\dots,p$ $j$, and $k$, which are the indices that run over the three dimensions of the tensor.

:::

# Contents

* [Mathematics](../posts/Mathmatics/guide_map/index.qmd)
* [Statistics](../posts/statistics/guide_map/index.qmd)
* [Engineering](../posts/Engineering/guide_map/index.qmd)
* [Machine Learning](../posts/ML/guide_map/index.qmd)
* [Deep Learning](../posts/DL/guide_map/index.qmd)
* [Language](../posts/Language/guide_map/index.qmd)
* [Patent](../posts/Patent/guide_map/index.qmd)
* [Surveilance](../posts/Surveilance/guide_map/index.qmd)

# Reference

* Statistics 
  * George Casella & Rogeer L. Berger - Statistcal Inference, 2nd Edition
  * Dobson and Barnett (2008) An Introduction to Generalized Linear Model. 3rd Ed. Chapman & Hall.
  * Fitzmaurice, Laird and Ware (2011) Applied Longitudinal Analysis. 2nd Ed. Wiley.
  * Hosmer, Lemeshow and May (2008) Applied Survival Analysis. 2nd Ed. Wiley.
  * 슬기로운 통계생활 - https://www.youtube.com/@statisticsplaybook
  * 슬기로운 통계생활 - https://github.com/statisticsplaybook
  * Fast Campus, Coursera, Inflearn
  * 그 외 다수의 Youtube, and Documents from Googling
* Mathematics
  * James Stewart - Calculus Early Transcedentals, 7th Eidition & any James Stewart series
  * GILBERT STRANG - Introduction to Linear Algebra, 4th Edition. 
  * 임장환 - 머신러닝, 인공지능, 컴퓨터 비전 전공자를 위한 최적화 이론
  * Fast Campus, Coursera, Inflearn
  * [8일간의 선형대수학 기초(이상준 경희대 교수)](https://www.youtube.com/playlist?list=PLaqQvlCBe8vIkIEb4GX2ZZ1A4tFYeXR5W)
  * [Linear Algebra(Prof. Gilbert Strang, MIT Open Courseware)](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/)
  * [Computational Linear Algebra for Coders](https://github.com/fastai/numerical-linear-algebra/blob/master/README.md)
  * [Immersive linear Algebra](http://immersivemath.com/ila/)
  * [3blue1brown](https://www.3blue1brown.com/topics/linear-algebra)
  * 그 외 다수의 Youtube, and Documents from Googling
* Machine Learning
  * Gareth M. James, Daniela Witten, Trevor Hastie, Robert Tibshirani - An Introduction to Statistical Learning: With Applications in R 2nd Edition
  * Trevor Hastie, Robert Tibshirani, Jerome H. Friedman - The Elements of Statistical Learning 2nd Edition
  * Fast Campus, Coursera, Inflearn
  * 그 외 다수의 Youtube, and Documents from Googling
* Deep Learning
  * Saito Koki - Deep Learning from Scratch 1,2,3 (밑바닥부터 시작하는 딥러닝 1,2,3)
  * 조준우 - 머신러닝·딥러닝에 필요한 기초 수학 with 파이썬
  * 조준우 - https://github.com/metamath1/noviceml
  * 동빈나 - https://www.youtube.com/c/dongbinna 
  * 혁펜하임 - https://www.youtube.com/channel/UCcbPAIfCa4q0x7x8yFXmBag
  * Fast Campus, Coursera, Inflearn
  * 다수의 Youtube, and Documents from Googling
* Engineering
  * Fast Campus, Coursera, Inflearn
  * 그 외 다수의 Youtube, and Documents from Googling