---
title: Terminology
subtitle: Statistics vs Computer Scinece
description: |
  Some confusing terms.
categories:
  - Statistics
author: Kwangmin Kim
date: 12/29/2022
format: html
tbl-colwidths: [50,50]
draft: True
format: 
  html:
    page-layout: full

---

## Terms about Rectangular Data

Rectangular data is the commonly used data structure for statistical and machine learning models, which has a shape of rectangle where values or data . It has many other names such as a spreadsheet in Excel, a table in Relational Database Management System (RDBMS), a matrix in mathematics, a 2-D array in computer science, and a data frame in data science.

|   Terms  | Mathmatics            | Statistics                                             | Computer Science           | Data Engineering |
|----------|-----------------------|--------------------------------------------------------|----------------------------|------------------|
| graph    | visulaized plot       | visulaized plot                                        | connections among entities | data structure   |
| variable | independent variable  | predictor, experimental variable, explanatory variable | feature, input             | attribute, column|
| outcome  | dependent variable    | response variable, outcome                             |  output, target            | target           |
| Records  | pattern, example      | case, sample, observation                              |  instance                  | record, row      |

: Confusing Terms in Data Science {#tbl-letters}

See @tbl-letters.