---
title: Content List, Mathematics 
subtitle: Guide Map of Blogs in Mathematics Section
description: |
  Rather than studying pure mathematics, I focus on studying and organizing mathematical concepts by filling out this mathematics blog section with some mathematics stuff for deep learning
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/01/2100
format: 
  html:
    page-layout: full
    code-fold: true
---

# Contents

## Basic

* 2023-03-24, [Variable types](../variables/index.qmd)
* 1111-11-11, [Function](../function/index.qmd)
  * 2023-01-31, [Function (1) - Univariable Scalar Function (One to One)](../function/univariable_scalar_function.qmd)
  * 2023-01-31, [Function (2) - Multi-variable Scalar Function (Many to One)](../function/multivariable_scalar_function.qmd)
  * 2023-01-31, [Function (3) - Univariable Vector Function (One to Many)](../function/univariable_vector_function.qmd)
  * 2023-01-31, [Function (4) - Multi-variable Vector Function (Many to Many)](../function/mutivariable_vector_function.qmd)
  * 2023-02-18, [Function (5) - Composite Function](../function/composite_function.qmd)
* 2023-02-18, [Transformations of Functions](../transformation/index.qmd)
* 1111-11-11, Vector & Matrix
* 2023-03-15, [Limit, $\epsilon-\delta$ Method](../epsilon_delta/)
* Differentiation
  * 2023-02-04, [Derivative (1) - Univariable Scalar Funtion](../differentiation/2023-02-04_uni_derivative.qmd)
  * 1111-11-11, [Derivative (2) - Chain Rule & Partial Derivative](../differentiation/2023-02-10_composite_partial_derivative.qmd)
  * 1111-11-11, Derivative (3) - Higher Order Derivative
  * 1111-11-11, Derivative (4) - Mean Value Theorem
  * 1111-11-11, Derivative (5) - Gradient
* 2023-03-15, [Talyer's Series](../taylor_series/index.qmd)
* 1111-11-11, Gradient Direction
* 1111-11-11, Random Variable
* 1111-11-11, Probability Distribution
* 1111-11-11, Information Theory - Entropy
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11,

## Linear Algebra

* 2023-03-30, [Basics (1) - Vector Operations](../linear_algebra/01.basic_vector.qmd)
* 2023-03-30, [Basics (2) - Matrix Operations](../linear_algebra/02.basic_matrix.qmd)
* 2023-03-30, [Basics (3) - Special Matrix](../linear_algebra/03.basic_special_matrix.qmd)
* 1111-11-11, Inner Product
* 1111-11-11, Linear Combination
* 1111-11-11, 
* 1111-11-11, Linear Independence
* 1111-11-11, Basis, Dimension, & Rank
* 1111-11-11, Outer Product
* 1111-11-11, Eigen Value & Eigen Vector
* 1111-11-11, Eigen Decomposition
* 1111-11-11, Singular Value Decomposition (SVD)
* 1111-11-11, Gram-Schmidt
* 1111-11-11, Group
* 1111-11-11, Orthogonal Matrix
* 1111-11-11, Rotation & Group
* 2023-04-02, [Matrix Transformation (5) - Quadratic Form](../linear_algebra/quadratic_form.qmd)
* 2023-04-02, [Matrix Calculus (1) - Quadratic Form](../linear_algebra/diff_quadratic_form.qmd)
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 

## Optimization

* 2023-03-23, [Minimizer & Minimum](../optimization/minimizer.qmd)
* 1111-11-11, Convex Set
* 1111-11-11, Convex Function
* 1111-11-11, Unconstrained Optimization
* 1111-11-11, Non-linear Least Square
* 1111-11-11, Largrange Multiplier Method
  * 1111-11-11, Largrange Primal Function
  * 1111-11-11, Largrange Dual Function
  * 1111-11-11, KKT conditions
* 1111-11-11, Gradient Descent Optimizers
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 

## Reference

* Statistics 
  * George Casella & Rogeer L. Berger - Statistcal Inference, 2nd Edition
  * 슬기로운 통계생활 - https://www.youtube.com/@statisticsplaybook
  * 슬기로운 통계생활 - https://github.com/statisticsplaybook
  * 다수의 Youtube, and Documents from Googling
* Mathematics
  * James Stewart - Calculus Early Transcedentals, 7th Eidition
  * any James Stewart series
  * 임장환 - 머신러닝, 인공지능, 컴퓨터 비전 전공자를 위한 최적화 이론
  * 다수의 Youtube, and Documents from Googling
* Deep Learning
  * 조준우 - 머신러닝·딥러닝에 필요한 기초 수학 with 파이썬
  * 조준우 - https://github.com/metamath1/noviceml
  * 동빈나 - https://www.youtube.com/c/dongbinna 
  * 혁펜하임 - https://www.youtube.com/channel/UCcbPAIfCa4q0x7x8yFXmBag
  * 다수의 Youtube, and Documents from Googling