---
title: "Description"
subtitle: "Project Description"
description: "Due to security concerns, it is difficult to display the data used in this project. Therefore, I will generate fake data to reproduce and demonstrate a rough analysis pipeline. \n 보안 문제로 인해 이 프로젝트에서 사용된 데이터를 공유하기 어렵습니다. 따라서 대략적인 분석 파이프라인을 재현하고 시연하기 위해 가상의 데이터를 생성할 것입니다."
author: Kwangmin Kim
date: 2023-01-03
---
# Introduction

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Background

알츠하이머병(AD)은 수백만 명의 미국인에게 영향을 미치는 가장 흔한 형태의 치매이다. 알츠하이머병은 기억력, 사고력 및 행동에 영향을 주지만 증상이 나타나기까지 거의 20년에 걸쳐 진행이 된다. 따라서 전 임상 단계에서 생리학을 이해하는 것이 필수적이다. 유전적 요인이 AD에 거의 50% 기여하는 것으로 추정된다. 유전자가 세포 환경을 변경하여 알츠하이머병 위험에 어떻게 기여하는지 더 잘 이해하기 위해 AD와 연관이 있는 유전자인 APOE를 보유한 사람들의 대사체를 조사했다. 대사체는 게놈과 프로테옴에서 생성된 산물을 나타낸다. 이러한 생화학 부산물은 유전적 요인과 환경적 요인 모두의 영향을 받는다. 모집단은 장수마을에 사는 Caucasian (백인) 참여자들이다. 

## Objective

LLFS(Long Life Family Study) 프로젝트의 목적은 전사체 및 단백질체 단계를 통해 게놈에서 대사체 단계에 이르는 다단계에서 통계 및 기계 학습을 사용하여 분석 파이프라인을 구축하고 알츠하이머병에 대한 중요한 바이오마커를 식별하기 위함이다.

## Goal

이 시뮬레이션 연구에서는 다변량 정규분포 하에서 데이터를 생성하여 대사 단계에서 가짜 데이터를 생성하는 데에만 집중할 것이다. (현재 내 실력으로는 이산 변수에 대하여 통계적으로 시뮬레이션하는데 더 연구가 필요함.) 이 시뮬레이션 연구의 목표는 알츠하이머병과 비알츠하이머병과 관련된 바이오마커를 구별할 수 있는 일련의 예측인자(또는 대사물질 또는 생화학물질)를 식별하는 것이다.

## Feature

보안 문제로 인해 이 프로젝트에 사용된 실제 데이터와 전체 분석 파이프라인을 표시하기 어렵다. 따라서 시뮬레이션을 통해 대략적인 분석 파이프라인을 재현하고 시연하기 위해 가짜 데이터를 생성한다.이 글에서는 보안 문제로 인해 대략적인 분석 파이프라인을 재현하고 시연하기 위한 시뮬레이션 데이터를 준비한다. 시뮬레이션 데이터는 실제 연구를 위해 표본으로 쓰이는 데이터의 특성을 전혀 반영하지 않는다.


## Development Environment

* Operating System
    * Window
    * Ubuntu 20.04
* Software
    * Quarto for dynamic documentation
    * VS code
    * R studio 2022.07.2+576
    * R base 4.2.2 in the English section
    * Python 3.11 in the Korean section

## How to Read the Contents

읽기의 편의를 위해 이 프로젝트를 5개 섹션으로 나누었습니다.

* Description (Current)
* Data Preparation
* EDA (Exploratory Data Analysis)
* Method1: statistical approach
* Method2: ML Approach
* Conclusion



</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

## Background

Alzheimer Disease (AD) is a most common form of dementia that affects millions of Americans. AD affects memory, thinking and behavior, but its progression is slow, spanning nearly two decades before the symptoms appear. Thus, it is imperative to understand the physiology at the pre-clinical stage. It is estimated that genetic factors contribute nearly 50% to AD. To better understand how genes contribute to the risk of AD by altering cellular milieu, we have examined the metabolome of individuals with the AD-related genotype, APOE. The metabolome represents the products that were generated from the genome and proteome. These biochemical products represent influences of both genetic and environmental factors. The population is Caucasian participants living in longevity village. 

## Objective

The objective of the Long Life Family Study (LLFS) project was to build an analysis pipeline of identifying significant biomarkers for AD using statistics and machine learning at the multi stages from the genomic to the metabolomic stage through the transcriptomic and proteomic stage.

## Goal

In this simulation study, I will focus only on generating fake data at the metabolomic stage by generating data under multivariate normal distributions. The aim of this simulation study is to identify a set of predictors (or metabolites or bio-chemicals) that will enable to differentiate bio-markers that are associated with AD vs. non-AD.

## Feature

In this article, due to security concerns, it is difficult to display the real data and the entire analysis pipeline used in this project. Therefore, I prepared simulated data to reproduce and demonstrate a rough analysis pipeline. The simulated data does not reflect the characteristics of the truely sampled data used in the LLFS at all.

## Development Environment

* Operating System
    * Window
    * Ubuntu 20.04
* Software
    * Quarto for dynamic documentation
    * VS code
    * R studio 2022.07.2+576
    * R base 4.2.2 in the English section
    * Python 3.11 in the Korean section

## How to Read the Contents

For the convenience of reading, I divided this proejcts into 5 sections:

* Description (Current)
* Data Preparation
* EDA (Exploratory Data Analysis)
* Method1: statistical approach
* Method2: ML Approach
* Conclusion



</div>


# Analysis Pipeline Architecture

## Overview 

### As-Is
```{mermaid}
%%| fig-width: 7.5
flowchart TB
    subgraph Skip_These_Steps_in_This_Article
        direction LR
        subgraph data_collection
            direction TB
            multi-centered_medical_centers---
            set_inclusion\exclusion_criteria---
            patient_visit---
            blood_sampling---
            store_samples_in_labs
        end
        subgraph mass_spectrometry
            direction LR
            conduct_mass_spectrometry---
            digitalization---
            store_in_database_system    
        end
        subgraph data_transfer
            direction TB
            subgraph data
                direction LR
                metabolome_data---
                clinical_data---
                demographic_data---
                dietary_habit_data
            end
            data---csv_or_excel_format
        end
        subgraph data_quality_control
            direction TB
            identify_anomaly_data---
            identify_missing_values
            subgraph missing_value_analysis
                direction LR
                MCAR---
                MAR---
                MNAR
            end
            either_imputation_or_omission---
            communication_with_labs---
            set_data_inclusion/exclusion_criteria
        end
        identify_missing_values---missing_value_analysis---either_imputation_or_omission
        subgraph data_preprocessing
            direction LR
            data_transformation
        end
    end
    subgraph data_analytics
        direction LR
        exploratory_data_analysis---
        statistical_analysis---
        machine_learning
    end
    subgraph report_to_faculty_members
        direction TB
        share_with_medical_doctors---
        share_with_epidemiologists---
        share_with_neurologists---
        share_with_biologists---
        share_with_biostatisticians---
        share_with_bioinformatician
    end
    subgraph write_manuscript
        direction LR
    end
    
data_collection-->mass_spectrometry-->data_transfer-->data_quality_control-->data_preprocessing-->data_analytics-->report_to_faculty_members-->write_manuscript
```

### To-Be 

```{mermaid}
%%| fig-width: 7.5
flowchart TB
    subgraph Simulation
        direction TB
        subgraph assign_frequency
        direction LR
        Assign_probabilities     
        end
        subgraph generate_multivariate_normal_distribution
            direction TB
            determine_sample_size ---
            determine_number_of_columns---
            create_covariate_correlation_matrix---
            apply_noise_to_the_covariance_matrix
        end
        subgraph create_weight_matrix
            direction LR
            apply_some_noise_to_the_covariance_matrix
        end
        subgraph calculate_score_matrix
            direction LR
            matrix_multiplication_covariance_matrix_weight_matrix---
            used_logistic_function
        end
        subgraph create_response_variable
            direction LR
            result_of_logistic_function
        end
        subgraph creation_some_discrete_variables
            direction LR       
        end
        subgraph join
            direction LR
            all_the_matrix_and_vector_created       
        end
        assign_frequency-->generate_multivariate_normal_distribution-->create_weight_matrix-->
        calculate_score_matrix-->create_response_variable-->creation_some_discrete_variables-->
        join
    end
    subgraph data_analytics
        direction LR
        exploratory_data_analysis---
        statistical_analysis---
        machine_learning
    end
    subgraph conclusion
        direction LR
    end
    Simulation-->data_analytics-->conclusion
```
