---
title: "ML Approach"
subtitle: "Analysis using Machine Learning"
description: "Machine Learning"
author: Kwangmin Kim
date: 2023-01-03
---
```{r}
#| echo: false
#| message: false
#| code-fold: true
#| warning: false

library(tidyverse)
library(tidymodels)
library(glmnet)
library(MASS)
library(mixOmics)
set.seed(20230103) 
knitr::opts_chunk$set(message=FALSE,warning=FALSE)
```


```{r, echo=FALSE,message=FALSE,warning=FALSE}
n <- 1000    # sample size
p <- 10000     # the number of predictors
significant_p <- p*0.25  # the number of predictors associated with a response variable

x <- matrix(rnorm(n*p), nrow=n, ncol=p)
y <- apply(x[,1:significant_p], 1, sum) + rnorm(n)

# Split data into train (2/3) and test (1/3) sets
train_rows <- sample(1:n, .66*n)
x.train <- x[train_rows, ]
x.test <- x[-train_rows, ]

y.train <- y[train_rows]
y.test <- y[-train_rows]

list.of.fits <- list()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)
  
  list.of.fits[[fit.name]] <-
    cv.glmnet(x.train, y.train, type.measure="mse", alpha=i/10, 
      family="gaussian")
}

results <- data.frame()
for (i in 0:10) {
  fit.name <- paste0("alpha", i/10)
  
  predicted <- 
    predict(list.of.fits[[fit.name]], 
      s=list.of.fits[[fit.name]]$lambda.1se, newx=x.test)
  
  mse <- mean((y.test - predicted)^2)
  
  temp <- data.frame(alpha=i/10, mse=mse, fit.name=fit.name)
  results <- rbind(results, temp)
}

results
```
