---
title: Composite Function
subtitle: Draft
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 01/31/2023
execute: 
  warning: false
format: 
  html:
    page-layout: full
    code-fold: true
draft: False
---


<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Composite Function

::: {#def-composite}

Given two functions f and g, the composite function $f\circ g$ (also called the **composition** of $f$ and $g$) is defined by 

$$
(f\circ g)(x)=f(g(x))
$$ {#eq-composite}

:::

The domain of $f\circ g$ is the set of all $x$ in the domain of $g$ such that $g(x)$ is in the domain of $f$. In other words, $(f\circ g)(x)$ is defined whenever both $g(x)$ and $f(g(x))$ are defined. 

### Example

If $f(x)=x^2$ and $g(x)=e^x$, find $f\circ g$ and $g\circ f$. 

$$
\begin{aligned}
(f\circ g)(x)&=f(g(x))=f(e^x)=(e^x)^2=e^{2x}\\
(g\circ f)(x)&=g(f(x))=g(x^2)=e^{x^2}=e^{x^2}\\
\end{aligned}
$$

위의 예제처럼, $f\circ g \ne f\circ g$. 

</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">


## Composite Function

::: {#def-composite}

Given two functions f and g, the composite function $f\circ g$ (also called the **composition** of $f$ and $g$) is defined by 

$$
(f\circ g)(x)=f(g(x))
$$ {#eq-composite}

:::

The domain of $f\circ g$ is the set of all $x$ in the domain of $g$ such that $g(x)$ is in the domain of $f$. In other words, $(f\circ g)(x)$ is defined whenever both $g(x)$ and $f(g(x))$ are defined. 

### Example

If $f(x)=x^2$ and $g(x)=e^x$, find $f\circ g$ and $g\circ f$. 

$$
\begin{aligned}
(f\circ g)(x)&=f(g(x))=f(e^x)=(e^x)^2=e^{2x}\\
(g\circ f)(x)&=g(f(x))=g(x^2)=e^{x^2}=e^{x^2}\\
\end{aligned}
$$

Like the example above, $f\circ g \ne f\circ g$. 

</div>

```{python}
#| echo: false
#| eval: false
radius = 10
from IPython.display import display, Markdown
display(Markdown("""
The radius of the circle is {radius}.
""".format(radius = radius)))
```


## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)