---
title: Univariable Scalar Function
subtitle: template
description: |
  template
categories:
  - template
author: Kwangmin Kim
date: 01/31/2023
format: 
  html:
    page-layout: full
    code-fold: true
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Univariable Scalar Function

* $f:\mathbb{R} \rightarrow \mathbb{R}$ or $y=f(x)$ 으로 표현
    * $f:\mathbb{R} \rightarrow \mathbb{R}$ : 입력과 출력의 개수를 직관적으로 알 수 있음
    * 예시: $f(x)=x^2, f(x)=2^x, f(x)=log_3x$

### Scalar Function

* Polynomials
    * monomial: one term, 상수 또는 변수 항 하나로 이루어진 식
        * ex) $2,x,x^2,x/3$ 
    * binomial: two terms, 단항식이 덧셈과 뻴셈으로 연결된  식
        * ex) $3x^2+2$, coefficient=3. $x$= 변수, degree = 2, constant = 2
    * trinomial: three terms
    * quadrinomial: four terms
    * quintinomial: five terms
    * multinomial: more than one terms, a combination of nomials with +/-.
        * ex) $x^2+2x+3$
* Multinomial Function
    * 다항식으로 구성된 함수
    * ex) $f(x)=x^2+2x+4$
    * 연속이고 미분 가능
* Exponential Function
* Log Function
* Logistic Sigmoid Function


```{python}
#| echo: false
#| eval: false
radius = 10
from IPython.display import display, Markdown
display(Markdown("""
The radius of the circle is {radius}.
""".format(radius = radius)))
```


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">


</div>


## Blog Guide Map Link

* [Statistics Blog](../../statistics/guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)