project:
  type: website

website:
  title: "Kwangmin Kim"
  navbar:
    background: dark
    logo: ./images/logo.png
    search: true
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - file: about.qmd
        text: About
      - href: docs/CV/index.qmd 
        text: "CV"
      - text: "Projects"
        href: docs/projects/index.qmd 
      - text: "Blog"
        href: docs/blog/index.qmd

    right:
      - icon: github
        href: https://github.com/kmink3225
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/kwangmin-kim-a5241b200/
        aria-label: Linkedin
      - icon: envelope
        href: kmink3225@gmail.com
        aria-label: Email
        
  sidebar: 
    - id: Projects
      title: "Projects" 
      style: "floating"
      collapse-level: 2
      backgournd: light
      align: left
      contents:
        - docs/projects/index.qmd
        - text: "Project 1"
          href: docs/projects/project1.qmd
        - text: "Project 2"
          href: docs/projects/project2.qmd
        - text: "Project 3"
          href: docs/projects/project3.qmd
   
    - id: CV
      title: "CV" 
      style: "floating"
      collapse-level: 2
      backgournd: light
      align: left
      contents:
        - docs/CV/index.qmd
        - text: "Resume"
          href: docs/CV/Resume.pdf
        - text: "CV"
          href: docs/CV/cv.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

