project:
  type: website

website:
  title: "Kwangmin Kim"
  site-url: kmink3225.netlify.app
  description: "A great sample blog"
  navbar:
    background: dark
    logo: ./images/logo.png
    search: true
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: docs/CV/index.qmd 
        text: "CV"
      - text: "Projects"
        href: docs/projects/index.qmd 
      - text: "Blog"
        href: docs/blog/index.qmd

    right:
      - text: Me
        href: about.qmd
      - icon: github
        href: https://github.com/kmink3225
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/kwangmin-kim-a5241b200/
        aria-label: Linkedin
      - icon: rss
        href: docs/blog/index.qmd
      #- icon: envelope
      #  href: kmink3225@gmail.com
      #  aria-label: Email
        
  sidebar: 
    - id: Projects
      style: "floating"
      collapse-level: 1
      backgournd: light
      align: left
      contents:
        - text: "Projects"
          href: docs/projects/index.qmd
        - section: "High Dimension"  
          contents:
            - docs/projects/high_dimension/description.qmd
            - docs/projects/high_dimension/architecture.qmd
            - docs/projects/high_dimension/data_preparation.qmd
            - docs/projects/high_dimension/eda.qmd
            - docs/projects/high_dimension/statistical_approach.qmd
            - docs/projects/high_dimension/ml_approach.qmd
            - docs/projects/high_dimension/report.qmd
    - id: CV
      title: "CV" 
      style: "floating"
      collapse-level: 2
      backgournd: light
      align: left
      contents:
        - docs/CV/index.qmd
        - text: "Resume"
          href: docs/CV/Resume.pdf
        - text: "CV"
          href: docs/CV/cv.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

