project:
  type: website

website:
  title: "Kwangmin Kim"
  site-url: kmink3225.netlify.app
  description: "blog"
  navbar:
    background: dark
    logo: ./images/logo.png
    search: true
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: docs/CV/index.qmd 
        text: "CV"
      - text: "Projects"
        href: docs/projects/index.qmd 
      #- text: "Blog"
      #  href: docs/blog/index.qmd

    right:
      - text: Me
        href: about.qmd
      - icon: github
        href: https://github.com/kmink3225
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/kwangmin-kim-a5241b200/
        aria-label: Linkedin
      #- icon: rss
      #  href: docs/blog/index.qmd
      #- icon: envelope
      #  href: kmink3225@gmail.com
      #  aria-label: Email
        
  sidebar: 
    - id: Projects
      style: "floating"
      collapse-level: 1
      backgournd: light
      align: left
      contents:
        - text: "Projects"
          href: docs/projects/index.qmd
        - section: "Baseline Fitting" 
          contents:
          - docs/projects/baseline_subtraction/index.qmd    
        - section: "FDA Validation" 
          contents:
          - docs/projects/dsp_validation/index.qmd  
        - section: "Diagnostic Device QC"  
          contents:
          - docs/projects/qc_platform/index.qmd    
        #- section: "Platform Plan"  
        #  contents:
        #  - docs/projects/platform_plan/index.qmd
        #- section: "Diagnostic Algorithm"  
        #  contents:
        #  - docs/projects/backfitting/index.qmd
        #- section: "Clinical Data Analysis"  
        #  contents:
        #  - docs/projects/pcr_clinical/index.qmd
        - section: "LLFS"  
          contents:
          - docs/projects/LLFS/project_description.qmd
          #- section: "Self Project"
          #  contents:
          #  - docs/projects/LLFS/self_description.qmd
          #  - docs/projects/LLFS/data_preparation.qmd
          #  - docs/projects/LLFS/eda.qmd
          #  - docs/projects/LLFS/mining.qmd
          #  - docs/projects/LLFS/statistical_approach.qmd
          #  - docs/projects/LLFS/ml_approach.qmd
          #  - docs/projects/LLFS/report.qmd
        - section: "Heavy Metal Removal"  
          contents:
          - docs/projects/heavy_metal/index.qmd
        #- section: "Diffusion Model"  
        #  contents:
        #  - docs/projects/social_network/index.qmd
        - section: "Phellinus Linteus Effects"  
          contents:
          - docs/projects/phellinus_linteus/index.qmd    
    - id: CV
      title: "CV" 
      style: "floating"
      collapse-level: 2
      backgournd: light
      align: left
      contents:
        - docs/CV/index.qmd
#        - text: "Resume"
#          href: docs/CV/Resume.pdf
#        - text: "CV"
#          href: docs/CV/cv.qmd

format:
  html:
    theme: materia
    #css: styles.css
    toc: true
    code-fold: true
    code-copy: true
    code-overflow: wrap
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 200px
      body-width: 1150px
      margin-width: 100px
editor: visual

