---
title: Invention Description
subtitle: SG Switch Model for the FDA Validation Report
description: |
  template
categories:
  - template
author: Kwangmin Kim
date: 04/07/2023
format: 
  pdf:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: true
---

## 발명의 명칭 (한글,영문)

SG Switch Model for the FDA Validation Report

## 발명(고안)의 상세한 설명

### 그 분야 종래기술의 설명 및 문제점

SG 자체 시스템에서는 알고리즘의 안정성 test를 위해 white box testing (= unit test, integration level test, system level test)를 진행하고 있고 advanced testing method (=statistical testing)는 없다.

선행문헌1_존슨컨트롤스테크놀러지_1020107028596은 데이터 시뮬래이션에 관한 내용으로 연관성이 없다. Switch Model은 정해진 시나리오를 기반으로 Ct값과 양/음성 결과를 반복 측정하는 것이다.

선행문헌2_한국과학기술원_1020180052680은 확률 기반으로 관심 모듈을 확률적으로 호출하는 발명으로 본 발명과 연관이 없다. Switch model은 씨젠의 data scientist에 의해 정해진 modules을 전제로 한다.

### 본 발명의 목적

DSP 알고리즘의 안정성을 통계적으로 검증하기 위해 고안된 model이다.

### 본 발명의 내용

SW의 안정성 테스트는 대체적으로 unit test, integration level test, system level test가 있다. 하지만 FDA validation guidance document에서 위의 3가지 방식으로는 SW안정성을 검증하기 어렵다고 기재되어 있기 떄문에 advanced testing인 statistical testing 을 수행했다. 아래의 switch model은 statistical testing을 구현하게 만드는 model이다.

### Definition of Switch Model

DSP 알고리즘의 안정성을 테스트하고 정량 분석을 위한 통계 테스트를 수행하기 위해 SG는 내부적으로 **스위치 모델**을 기획하고 개발했다. siwtch 모델은 DSP 알고리즘을 구성하는 모듈을 하나씩 꺼서 각각의 모듈이 최종 결과인 양-부정율과 Ct에 어떤 영향을 미치는지 관찰하도록 설계된 모델이다. 예를 들어 본 문서에서 Scenario01은 DSP 알고리즘 중 module01의 기능을 비활성화하고 나머지 모듈을 활성화하는 DSP 알고리즘을 의미한다. Scenario02는 DSP 알고리즘 중 module02의 기능이 꺼지고 다른 모듈의 기능이 켜진 DSP 알고리즘을 말한다.

### Composition of Switch Model

통계 실험적 관점에서 스위치 모델은 1. 실험군과 2. 대조군의 두 그룹으로 나뉜다. 실험군은 각 모듈의 기능이 비활성화된 일련의 알고리즘을 의미한다. 대조군은 다시 음성대조군과 양성대조군으로 나누어 음성대조군은 null 모듈을, 양성대조군은 full 모듈을 사용하였다. null 모듈은 Baseline Estimation and Subtraction, Modeling Fluorescence Signal with Sigmoid Function, Ct Calculation을 제외한 실험군의 모든 모듈의 기능이 꺼져 있음을 의미한다. 반면 full 모듈은 DSP 알고리즘 자체로, 모든 모듈이 켜져 있는 알고리즘을 의미한다.

1. 실험군
  * BPN
  * MuDT
  * Noise Signal Filtering
  * Jump Correction
  * Linear Growth Signal Filtering
  * Baseline Estimation and Subtraction for Early-cycle Amplification
  * Classification Using 4-Parameter Sigmoid Modeling Parameters
  * Modeling Diverse PCR Signal Patterns
2. 대조군
  * negative control: null module
  * positive control: full modules
3. Default Group
  * Baseline Estimation and Subtraction
  * Modeling Fluorescence Signal with Sigmoid Function
  * Ct Calculation

### Switching Scenarios

스위치 모델은 스위치 모델에 기능 모듈과 실험군을 도입하고 각 모듈의 on/off 상태에 대한 시나리오를 할당하여 구현한다.

* scenario00 (the positive control): the full modules, all the modules are turned on
* scenario01 (the experiment group): the BPN module off
* scenario02 (the experiment group): the MuDT module off
* scenario03 (the experiment group): the DRFU Filter module off
* scenario04 (the experiment group): the Jumping Correction module off
* scenario05 (the experiment group): the Linear Growth Signal Filtering module off
* scenario06 (the experiment group): the Baseline Determination for Early Amplification module off
* scenario07 (the experiment group): the Parameter-Based Signal Classifier module off
* scenario08 (the experiment group): the Amplfication Signal Sigmoid Pattern Identification module off
* scenario99 (the negative control): the null module, all the modules are turned off  

자세한 내용은 FDA validation report를 참조하길 바란다.

### 발명의 효과

본 발명은 시나리오별로 알고리즘을 반복적으로 측정함으로써 시약과 최종 산출물인 Ct값과 양음성률의 관계를 교란시킬수 있는 교란자 (Inhibitors, dimerization, dye의 광학적 특성 등)의 효과를 최소화 시키는 효과를 갖는다. 통계적 검정이 수반되기 때문에 data의 일시적인 결과 및 패턴을 관찰하는 것이 아니라 실제로 알고리즘이 안전한가에 대한 진리값에 대한 추정 및 추론이 최종 결과로서 산출 된다.

## 참조 선행 문헌

