---
title: Content List, Statistics 
subtitle: Guide Map of Blogs in Statistics Section
description: |
  Just enumerating a list of the contents in the the statistics section 
categories:
  - Statistics
author: Kwangmin Kim
date: 05/01/2100
format: 
  html:
    page-layout: full
    code-fold: true
tbl-colwidths: [50,50]
---

**(Draft)**

# Contents List

## Basic

### Probability Theory

* 2023-02-05, Set Theory
* 2023-02-05, [Basics of Probability Theory - Axiomatic Foundations]
* 2023-02-05, [Basics of Probability Theory - Calculus of Probabilities]
* 2023-02-05, [Basics of Probability Theory - Probability](../2023-02-05_probability/index.qmd)
* 2023-02-05, [Conditional Probability](../2023-02-05_conditional_probability/index.qmd)
* 2023-02-05, [Independence]
* 2023-02-05, [Bayes' Rule](../2023-02-05_bayes_rule/index.qmd)
* 2023-02-05, Random Variable
* 1111-11-11, Probability Distribution

### Transformations and Expectations

* 2023-02-21, [Transformation of Random Variables](../2023-02-21_transformation/index.qmd)
* 1111-11-11, Expected Value vs Realizaed Value
* 1111-11-11, Variance
* 1111-11-11, Covariance and Correlation
* 2023-02-28, [Moment Generating Function, MGF](../2023-02-28_mgf/index.qmd)

### Exponential Family Distributions

* Discrete Random Variable
  * 2023-02-27,[Bernoulli Distribution](../2023-02-27_exponential_family/discrete_bernoulli.qmd)
  * 2023-02-28,[Binomial Distribution](../2023-02-27_exponential_family/discrete_binomial.qmd)
  * 2023-03-01,[Poisson Distribution](../2023-02-27_exponential_family/discrete_poisson.qmd)
  * 2023-03-01,[Geometric Distribution](../2023-02-27_exponential_family/discrete_geometric.qmd)
  * 1111-11-11, Hypergeometric Distribution
* Continuous Random Variable
  * 1111-11-11, Normal Distribution
  * 1111-11-11, Exponential Distribution
  * 1111-11-11, Beta Distribution
  * 1111-11-11, Chi-squared Distribution
* 1111-11-11, 

### Multiple Random Variables

* 1111-11-11, Joint Distribution and Marginal Distribution

### Point Estimation

* 1111-11-11, Estimation Methods - Method of Moments
* 2023-03-29, Estimation Methods - [Maximum Likelihood Estimation & Statistical Bias](../2023-03-25_MLE/index.qmd)
* 1111-11-11, Estimation Methods - Bayesian Estimation
* 1111-11-11, Estimation Methods - The EM Algorithm
* 1111-11-11, Evaluation Methods of Estimators - Mean Squared Error
* 1111-11-11, Evaluation Methods of Estimators - Best Unbiased Estimators
* 1111-11-11, Evaluation Methods of Estimators - Sufficiency and Unbiasedness
* 1111-11-11, Evaluation Methods of Estimators - Loss Function Optimality



## Hypothesis Testing

* 1111-11-11, Hypothesis Testing
* 1111-11-11, Permutation Test

### Methods of Finding Tests

* 1111-11-11, Likelihood Ratio Tests
* 1111-11-11, Bayesian Tests
* 1111-11-11, Union-Intersection and Intersection-Union Tets

### Methods of Evaluating Tests

* 1111-11-11, Power
* 1111-11-11, Error Proabilities and the Power Function
* 1111-11-11, Most Powerful Tests
* 2022-12-28, [p-values](../2022-12-08-P-value/index.qmd)
* 1111-11-11, Loss Function Optimality
* 1111-11-11, Multiple Testing
* 1111-11-11, Sample Size Calculation
* 1111-11-11, A/B Testing
* 2023-01-07, [ANOVA](../2023-01-07-anova/index.qmd)
  * 2023-01-27, [ANCOVA](../2023-01-27_ANCOVA/)
  * 2023-01-27, [repeated measures ANOVA](../2023-01-27_rmANOVA/)
  * 2023-01-28, [MANOVA](../2023-01-28_MANOVA/)

## Categorical Data Analysis

* 1111-11-11, Introduction
* 1111-11-11, 
* 1111-11-11, 
* 2022-12-28, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 1111-11-11, 
* 2023-01-07, 
* 2023-01-27, 
* 2023-01-27, 
* 2023-01-28, 

## Regression

* 1111-11-11, Least Square and Simple Linear Regression
* 1111-11-11, Multiple Linear Regression

### Generalized Linear Models
* 1111-11-11, Logistic Regression
* 1111-11-11, Multinomial Regression
* 1111-11-11, Poisson Regression
* 1111-11-11, Poisson Regression
* 1111-11-11, Poisson Regression

## Longitudinal Data Analysis

* 2023-03-23, [LDA (1) - Intro](../LDA/1_intro.qmd)
* 2023-03-23, [LDA (2) - Concepts & Covariance Models](../LDA/2_covariance_model.qmd)
* 2023-03-25, [LDA (3) - WLS & REML](../LDA/intro.qmd)
* 2023-03-25, [LDA (4) - Respiratory Infection Data Example](../LDA/intro.qmd)
* 2023-03-28, [LDA (5) - Epileptic Seizures Data Example](../LDA/intro.qmd)

### Mixed Models

 * 1111-11-11, Linear Mixed Models

## Generalized Additive Models

## Survival Analysis

* 1111-11-11,  Cox-Hazard Model