---
title: "RNN Concept"
author: "Kwangmin Kim"
date: "2023.03.10"
categories: 
  - DL
format: 
  html:
    page-layout: full
    toc: true
    code-fold: true
    number-sections: true
---


<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

(The Very First Draft)

# Introduction

GNN stands for Generative Adversarial Network

<fig1>

Generator 와 Discriminator가 서로 Adversarial

- 서로 동시에 학습 불가
    - G : D를 속이고 싶음. → D에서 G의 출력 값이 정답으로 나와야 함.
    - D : G가 만든 출력과 real 데이터를 구분하고 싶음. →
    - G 학습 → D 학습 → G 학습 → D 학습 … 반복
    - GAN 모델이 잘 만들어지면 D는 G의 출력과 real 데이터를 잘 구분하지 못함. → 0.5, 0.5
- 입력
- 출력
    - G의 결과

<fig2>

그림1과 같이 RNN에서는 hidden layer에서 activation function을 통해 output을 출력하는 노드를 cell이라고 표현한다. 이는 cell이 이전 시점의 값을 기억하는 일종의 메모리 역할을 수행하기 때문이며 memory cell 또는 RNN cell이라고 부르기도 한다.

<그림2>

RNN 모델에서 cell은 이전 시점에 출력된 값을 현 시점의 입력으로 사용하는 재귀적 활동을 한다. 그림2의 왼쪽 그림은 그림1을 세로로 표현한 버전으로 $t$는 현재 시점을 의미한다. 그림2의 오른쪽 그림은 time step에 따라 cell의 output이 어떻게 다음 시점의 입력이 되는지를 보여준다. 

이 때, 현재 시점($t$)에서 cell의 입력으로 사용되는 과거 시점($t-1$)의 cell의 output 값을 **hidden state**라고 부른다.

## Types

RNN 모델은 FeedForward network와 달리 해결하고 싶은 문제에 따라 입력과 출력의 길이를 다양하게 조절할 수 있다.

<그림3>

### One-to-one (일대일)

하나의 입력에 대해 하나의 결과를 출력

### One-to-many (일대다)

하나의 입력에 대해 여러 개의 결과를 출력

**예시**

- 이미지 캡셔닝 (Image Captioning) : 이미지 입력 시 이미지의 제목(단어의 나열)을 출력

### Many-to-one (다대일)

여러 개의 입력에 대해 하나의 결과를 출력

**예시**

- 감성 분류 (sentiment classification) : 문장의 긍부정 판별

### Many-to-many (다대다)

여러 개의 입력에 대해 여러 개의 결과를 출력

**예시** 

- chatbot : 사용자가 문장을 입력하면 문장으로 답변.
- 번역 : 영어 문장을 입력하면 한국어로 번역한 문장 출력.
- 개체명 인식 :
- 품사 태깅 :


### References

- [RNN 설명이 gif로 잘 정리되어 있음 ](https://www.simplilearn.com/tutorials/deep-learning-tutorial/rnn)


:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>


# Go to Project Content List

[Project Content List](./docs/projects/index.qmd)

# Go to Blog Content List

[Blog Content List](../../content_list.qmd)

