---
title: "Basic Vector(3) - Vector Equation"
subtitle: Vector Equation, Reparametrization
description: |
  Basic Linear Algebra 
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/30/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
execute:
  echo: false
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">



# Introduction

미분 기하에서 많이 쓰임. 임의의 component or tuple를 넣었을 때 좌표가 나오는 관계를 확립시켜줌. 그리고 차원의 확장이 용이하다.

## Linear Equation

* $y=mx+b$ 은 $(x,mx+b)$ 를 지나는 직선 
  * $y=mx+b$ 에서 $b=0$ 이면 원점을 지나는 직선 $y=mx$
    * $x=1 \rightarrow y=m \rightarrow (1,m)$ 이것을 $f(1)=(1,m)=\mathbf{v}$ 로 간단하게 표현해주는 함수가 바로 벡터 방정식
    * 이를 일반화하면 $(x,y)=t\mathbf{v}$ 이고 $(x,y)=\mathbf{x}$ 라 하면 $\mathbf{x}=t\mathbf{v}$ 라 둘 수 있다.
    * $\mathbf{x}=t\mathbf{v}$ 가 $y=mx$ 의 벡터 방정식이고 t 값이 정해지면 $\mathbf{x}$ 가 좌표로 출력된다.
    * $y=mx$ 위에 $(2,\frac{2}{3}m)$ 있는지 볼 때 
      $$
      \begin{aligned}
        \mathbf{x}&=t\mathbf{v}=t(1,m)\\
        \text{when }t=2, &\quad \mathbf{x}=2(1,m) = (2,2m)\\
        (2,2m) &\ne (2,\frac{2}{3}m)
      \end{aligned}
      $$
  * $y=mx+b$ 는 $\mathbf{x}=t\mathbf{v}$ 를 $b$ 만큼 평행 이동한 직선 이므로
    * $(0,b)= \mathbf{p}_0$ 라 두면 $(1,m)=\mathbf{v}_1$ 라 했을 때 $y=mx+b$ 는 $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ 로 표현된다.
* $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ 표현은 차원 확장의 용이
  * 3차원 이상의 공간을 표현할 때도 $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ 로 표현
  * 3차원 공간의 임의의 벡터가 주어졌을 때 원점에서 임의의 벡터까지의 벡터를 $\mathbf{p}_0$ 로 표현하면 $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ 가 임의의 벡터의 모든 점을 표현할 수 있다. 여기서 $\mathbf{x}=(x,y,z)$ 이다. 
  *  $\mathbf{p}_0$ 는 반드시 수직으로 이동한 벡터를 표현할 필요는 없다. 원점에서 임의의 직선상의 한점까지 거리와 방향을 표현한 벡터이면 충분하다. 그리고 직선에 평행한 벡터를 실수배하여 표현한 벡터에 $\mathbf{p}_0$ 를 더해주면 된다.

## Equations of Planes

* 평면은 벡터로 하나로 표현 불가하기 때문에 2개의 벡터를 이용
* 왜냐면, 벡터의 실수배는 벡터이기 때문
* 좌표 자체가 2개의 벡터로 되어 있기 때문에 평면을 모두 설명할 수 있다.
  * $(x,y) = xe_1+ye_2$ where $e_1=(1,0)$ and $e_2=(0,1)$
  * 단, 2개의 벡터는 평행하면 안된다. 평행한 두 벡터는 한 벡터가 다른 하나의 벡터의 실수배로 표현되기 때문
  * 만약, $\mathbf{v}_1 // \mathbf{v}_2$ 하다면 $(a,b)=a\mathbf{v}_1+b\mathbf{v}_2=ak\mathbf{v}_2+b\mathbf{v}_2=(ak+b)\mathbf{v}_2$ 그래서 직선하나 밖에 표현이 안된다.
* **평면 전체를 표현하려면 서로 평행하지 않은 두 벡터가 있어야 한다.** (선형적으로 독립인 벡터)
* 평행한 벡터는 두 벡터가 서로 종속임을 의미
* 그러므로 평면의 방정식: $\mathbf{x}=\mathbf{p}_0+t_0\mathbf{v}_1+t_1\mathbf{v}_2$
  * 원점으로 부터 평면에 $\mathbf{p}_0$ 만큼 이동해서 평면상의 $\mathbf{v}_1$ 과 $\mathbf{v}_2$ 의 실수배의 합으로 평면상의 모든 점을 표현한다.

### Example

* $y=3x+2$ 의 벡터방정식을 구하면 직선상의 임의 두 점을 선택 $(1,5), (2,8)$
$$
\begin{aligned}
  \mathbf{x}&=\mathbf{p}_0+t\mathbf{v}_1\\
  &=(1,5)+t(2-1,8-5)\\
  &=(1,5)+t(1,3)
\end{aligned}
$$

* $x+2y+3z=4$ 의 벡터방정식을 구하면 평면상의 임의 세 점을 선택 $(1,1,\frac{1}{3}), (1,2,-\frac{1}{3}), (0,0,\frac{3}{4})$
$$
\begin{aligned}
  \mathbf{x}&=\mathbf{p}_0+t_0\mathbf{v}_1+t_1\mathbf{v}_2\\
  &=(1,1,\frac{1}{3})+t_0(0,1,-\frac{2}{3})+t_1(-1,-1,\frac{5}{12})\\
  &=(1+t_0-t_1,1+t_0-t_1,\frac{1}{3}-t_0\frac{2}{3}+\frac{5}{12}t_1)
\end{aligned}
$$

## Reparametrization 

주로 미분 기하에서 많이 쓰임

### 벡터 방정식의 한계 점

* 유일성을 보장하기 힘들다
  * $y=x$ 의 벡터 방정식은 임의의 점 $(1,1)$ 을 잡아서 표현하면 $\mathbf{x}=t\mathbf{v}_1=t(1,1)=(t,t)$
  * 벡터 방정식을 함수로 봤을 때 $f(t)=(t,t)$ 로 표현가능하고 t를 매개변수라고 부른다.
  * 점 $(2,2)$ 를 잡아서 표현하면 $g(t)=t\mathbf{v}_2=t(2,2)=(2t,2t)$ 가 된다.
  * 이렇게, 같은 직선이 다른 벡터 방정식으로 표현이 되었고 이를 reparametrization이라 부른다. $f(t),g(t)$ 는 재매개변수화의 결과물이다.
* reparametrized vector equations 사이의 차이점
* 벡터는 방향을 가진 물리량이기 때문에 힘이나 속도같은 물리량들이 시간에 따라 어떻게 변하는지를 많이 쓰이는데 매개변수 $t$ 를 보통 time으로 잡는다. $t$ 가 0~1 까지 움직일 때 $f(t) g(t)$ 가 움직이는 속도가 달라짐 (엄밀히 말하면 $y=x$ 의 예시에서 방향은 동등하게 유지되고 거리가 바뀌었기 때문에 속력이 달라졌다고 말할 수 있다. 하지만 일반적으로 방향과 이동 거리가 모두 달라짐.)
  * $t=0, f(t)=g(t)=(0,0)$
  * $t=1, f(t)=(1,1), g(t)=(2,2)$
  * 즉, $f(t)$ 는 $(0,0) \rightarrow (1,1)$. $g(t)$ 는 $(0,0) \rightarrow (2,2)$
* 유일성을 보장하기 위해 속도의 기준은 방향성 때문에 정하기 어렵지만 속력의 기준은 정할 수 있다.
* 단위 속력 : 속력이 항상 $1$ 인 벡터 방정식
  * $y=x$ 의 $f(t)=(t,t)$ 시간 $t$ 에 대한 $y=x$ 의 좌표 (위치)의 변화율은 속도가 됨
  * $f'(t)$: 속도. $f'(t)=(1,1)$: $(1,1)$ 의 속도 방향을 가지고 있다는 의미
  * 속력은 $f'(t)=(1,1)$ 의 norm을 구하면 됨: $||f'(t)||=\sqrt{1^2+1^2}=\sqrt{2}$
  * 기준 속력 : $h(t)=\frac{f(t)}{||f'(t)||}=\frac{f(t)}{\sqrt{2}}=(\frac{t}{\sqrt{2}},\frac{t}{\sqrt{2}})$
  * $h'(t)=(\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}}), \quad ||h'(t)||=1$


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

# Introduction

Vector equations play a crucial role in the field of differential geometry, serving to establish meaningful relationships between vectors and their corresponding coordinates. By inserting an arbitrary component or tuple, these equations enable the representation of vectors in terms of their constituent coordinates. Furthermore, vector equations offer the flexibility to expand the dimensionality of the vector space under consideration. This property proves particularly valuable in accommodating systems with varying degrees of complexity and provides a versatile framework for geometric analysis and calculations.

## Vector Equation

A vector equation represents a geometric relationship between vectors and points. It is typically written in the form:

$$
\mathbf{x} = t\mathbf{v} + \mathbf{p}
$$

where $\mathbf{x}$ is a vector representing a point, $\mathbf{v}$ is a direction vector, $t$ is a scalar parameter, and $\mathbf{p}$ is a position vector.

Properties of Vector Equations:

1. Equivalent Directions:
   If $\mathbf{x} = t\mathbf{v} + \mathbf{p}$, then any scalar multiple of $\mathbf{v}$ yields an equivalent direction vector. For example, $2\mathbf{v}$ or $-3\mathbf{v}$ represent the same direction.
2. Parallel Lines:
   If two vector equations have the same direction vector $\mathbf{v}$, but different position vectors $\mathbf{p}_1$ and $\mathbf{p}_2$, then the corresponding lines are parallel.
3. Intersection:
   The point $\mathbf{x}$ in the vector equation represents the intersection point of the line with the direction vector $\mathbf{v}$ and the position vector $\mathbf{p}$
4. Translation:
   Adding or subtracting a vector $\mathbf{a}$ to the position vector $\mathbf{p}$ in the vector equation results in a translated line parallel to the original line.


## Linear Equation

For a better understanding of the concept of a vector equation, let's look into a simple example of a linear equation, $y=mx+b$ and its relation to vector equations by conveying the concept of representing lines and their translations using vector notation. 

* The equation $y=mx+b$ represents a line passing through the point $(x,mx+b)$.
  * When $b=0$, the equation represents a line passing through the origin, given by $y=mx$.
    * By setting $x=1$, we have $y=m$, which can be expressed as $(1,m)$ or $f(1)=(1,m)=\mathbf{v}$. This function provides a concise representation using vector equation notation.
    * Generalizing this, we have $(x,y)=t\mathbf{v}$, which can also be written as $\mathbf{x}=t\mathbf{v}$ if we denote $(x,y)$ as $\mathbf{x}$.
    * The vector equation $\mathbf{x}=t\mathbf{v}$ represents the line $y=mx$, and for a given value of $t$, $\mathbf{x}$ yields the corresponding coordinates.
    * To determine if $(2,\frac{2}{3}m)$ lies on the line $y=mx$, we evaluate:
      $$
      \begin{aligned}
        \mathbf{x}&=t\mathbf{v}=t(1,m)\\
        \text{when }t=2, &\quad \mathbf{x}=2(1,m) = (2,2m)\\
        (2,2m) &\ne (2,\frac{2}{3}m)
      \end{aligned}
      $$
  
  * The equation $y=mx+b$ represents a line that is a translation of the vector equation $\mathbf{x}=t\mathbf{v}$ by $b$ units.
    * Let $(0,b)=\mathbf{p}_0$ and $(1,m)=\mathbf{v}_1$. Then, $y=mx+b$ can be expressed as $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$.

Vector equation is useful for the versatile representation in expressing spaces of higher dimensions and clarifies its application in three-dimensional space. The statement about $\mathbf{p}_0$ not necessarily being orthogonal to the movement but representing a vector from the origin to any point on the line is accurate and adds further insight.

* The representation $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ facilitates dimension expansion.
  * It can be used to express spaces of dimensionality higher than 3 as $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$.
  * When representing an arbitrary vector in 3-dimensional space from the origin to the vector itself, $\mathbf{x}=\mathbf{p}_0+t\mathbf{v}_1$ can express all points of the vector. Here, $\mathbf{x}=(x,y,z)$.
  * $\mathbf{p}_0$ does not necessarily need to represent a vector orthogonal to the movement. It is sufficient to represent a vector from the origin to any point on the line. Adding a vector parallel to the line, obtained by scaling a vector, to the representation of the vector, $\mathbf{p}_0$ is added.

## Equations of Planes

* Because a plane cannot be represented by a single vector, we use two vectors.
* This is because scalar multiples of a vector are also vectors.
* Since the coordinates themselves are composed of two vectors, we can describe the entire plane.
  * $(x, y) = xe_1 + ye_2$ where $e_1 = (1, 0)$ and $e_2 = (0, 1)$.
  * However, the two vectors must not be parallel. If two vectors are parallel, one vector can be expressed as a scalar multiple of the other vector.
  * If $\mathbf{v}_1 // \mathbf{v}_2$, then $(a, b) = a\mathbf{v}_1 + b\mathbf{v}_2 = ak\mathbf{v}_2 + b\mathbf{v}_2 = (ak + b)\mathbf{v}_2$. Therefore, only a single line can be represented.
* To represent the entire plane, two vectors that are not parallel (linearly independent) are required.
* Parallel vectors indicate that the two vectors are dependent on each other.
* Therefore, the equation of a plane is $\mathbf{x} = \mathbf{p}_0 + t_0\mathbf{v}_1 + t_1\mathbf{v}_2$.
  * Starting from the origin and moving $\mathbf{p}_0$ units to the plane, all points on the plane are expressed as the sum of scalar multiples of $\mathbf{v}_1$ and $\mathbf{v}_2$ on the plane.

### Example

* When obtaining the vector equation of $y=3x+2$, we can choose any two points on the line, such as $(1,5)$ and $(2,8)$:
$$
\begin{aligned}
  \mathbf{x}&=\mathbf{p}_0+t\mathbf{v}_1\\
  &=(1,5)+t(2-1,8-5)\\
  &=(1,5)+t(1,3)
\end{aligned}
$$

* When obtaining the vector equation of $x+2y+3z=4$, we can choose any three points on the plane, such as $(1,1,\frac{1}{3})$, $(1,2,-\frac{1}{3})$, and $(0,0,\frac{3}{4})$:
$$
\begin{aligned}
  \mathbf{x}&=\mathbf{p}_0+t_0\mathbf{v}_1+t_1\mathbf{v}_2\\
  &=(1,1,\frac{1}{3})+t_0(0,1,-\frac{2}{3})+t_1(-1,-1,\frac{5}{12})\\
  &=(1+t_0-t_1,1+t_0-t_1,\frac{1}{3}-t_0\frac{2}{3}+\frac{5}{12}t_1)
\end{aligned}
$$

## Reparametrization 

Reparametrization is typically used in situations where we want to express the same geometric object or curve using different parameterizations in differential geometry.

### Limitations of Vector Equations

* Difficulty in guaranteeing uniqueness.
  * The vector equation $y=x$ can be expressed by choosing an arbitrary point $(1,1)$ as $\mathbf{x}=t\mathbf{v}_1=t(1,1)=(t,t)$.
  * When viewing the vector equation as a function, it can be expressed as $f(t)=(t,t)$, where $t$ is referred to as the parameter.
  * Choosing the point $(2,2)$ leads to the representation $g(t)=t\mathbf{v}_2=t(2,2)=(2t,2t)$.
  * Thus, the same line is represented by different vector equations, and this is called reparametrization. $f(t)$ and $g(t)$ are the results of reparametrization.
* Differences between reparametrized vector equations.
* Vectors are physical quantities with direction, so they are often used to describe quantities such as force and velocity that vary with time. The parameter $t$ is usually taken as time. When $t$ ranges from 0 to 1, the speeds at which $f(t)$ and $g(t)$ move are different (strictly speaking, in the example of $y=x$, the direction remains the same while the distance changes, so it can be said that the speeds are different. However, in general, both direction and distance change).
  * $t=0, f(t)=g(t)=(0,0)$
  * $t=1, f(t)=(1,1), g(t)=(2,2)$
  * In other words, $f(t)$ goes from $(0,0)$ to $(1,1)$, while $g(t)$ goes from $(0,0)$ to $(2,2)$.
* To ensure uniqueness, determining the standard for velocity is difficult due to directionality, but it is possible to determine the standard for speed.
  * Unit speed: A vector equation with a constant speed of 1.
  * For $y=x$, the rate of change of the coordinates (positions) of $f(t)=(t,t)$ with respect to time $t$ represents velocity.
  * $f'(t)$: Velocity. $f'(t)=(1,1)$: Indicates that $(1,1)$ has a velocity direction.
  * Speed can be obtained by calculating the norm of $f'(t)$: $||f'(t)||=\sqrt{1^2+1^2}=\sqrt{2}$.
  * Standard speed: $h(t)=\frac{f(t)}{||f'(t)||}=\frac{f(t)}{\sqrt{2}}=(\frac{t}{\sqrt{2}},\frac{t}{\sqrt{2}})$.
  * $h'(t)=(\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}})$, $||h'(t)||=1$.


</div>