---
title: "Basic Matrix (1) - Matrix Operations"
subtitle: template
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/31/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
execute:
  warning: false
  message: false
  eval: false
draft: true
---

```{r}
#| eval: false

library(tidyverse)
set.seed(100)
```


```{python}
#| echo: false
#| eval: false

import numpy as np
import matplotlib_inline
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sympy as sym # for RREF
import scipy.linalg # for LU
import matplotlib.gridspec as gridspec # used to create non-regular subplots

# NOTE: these lines define global figure properties used for publication.
from IPython import display
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')
#display.set_matplotlib_formats('svg') # display figures in vector format
plt.rcParams.update({'font.size':14}) # set global font size
     
```


## Matrix

A matrix is a rectangular array of elements, usually real numbers, arranged in rows and columns. If $\mathbf{A}$ is an $m \times n$ matrix, it can be represented as:
$$
\begin{bmatrix} 
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots & \vdots & \ddots & \vdots \\
  a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} 
$$
where $a_{ij}$ is the element in the $i$-th row and $j$-th column of the matrix $\mathbf{A}$.

## Terminology

### Column Vector

### Row Vector

### Elements

* 성분, 원소, 항
* 성분: i 행 j열에 위치한 성분
* 정방 행렬
* 대각원소

### 행렬의 동치

* 행렬의 크기: A_mn=B_mn
* 행렬의 원소가 같음

## Basic Matrix Operations

### Matrix addition 

The sum of two matrices of the same size is a matrix of the **same size** obtained by adding corresponding entries.

Given two $m \times n$ matrices $\mathbf{A}$ and $\mathbf{B}$, their sum $\mathbf{C} = \mathbf{A} + \mathbf{B}$ is defined by:

$$
c_{i,j}=a_{i,j}+b_{i,j}​
$$
for $1 \leq i \leq m$ and $1 \leq j \leq n$.

$$
\begin{bmatrix}
  1 & 2 \\
  3 & 4 \\
  5 & 6
\end{bmatrix} +
\begin{bmatrix}
  -1 & 0 \\
  2 & -3 \\
  -5 & 4
\end{bmatrix} =
\begin{bmatrix}
  0 & 2 \\
  5 & 1 \\
  0 & 10
\end{bmatrix}
$$

### Scalar multiplication 

The product of a scalar and a matrix is a matrix obtained by multiplying each entry of the matrix by the scalar.

Given a scalar $k$ and an $m \times n$ matrix $\mathbf{A}$, their product $k\mathbf{A}$ is defined by:
$$
(k\mathbf{A})_{i,j} = k(a_{i,j})
$$

for $1 \leq i \leq m$ and $1 \leq j \leq n$.

Example:
$$
2\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix} =
\begin{bmatrix}
2 & 4 \\
6 & 8 \\
10 & 12
\end{bmatrix}
$$

### Isomorphism

(set_a, operation_a) = (set_b, operation_b)

exist f:A-B s.t. f is an isomorphism <=> notation A~=B, B~=A, A is somorphic to B, B is isomorphic to A

덧셈과 스칼라배에 한해서 행렬과 벡터는 동형사상 기술

연산이라 함은 어떤 집합의 연산이 그 집합에 닫혀 있어야한다.  그래서 dot product는 벡터의 곱이 벡터가 나오는게 아니라 스칼라가 나오기 때문에 연산이라 볼 수 없고 함수 또는 관계로 봐야한다.

### Matrix multiplication

The product of two matrices $\mathbf{A}$ and $\mathbf{B}$ is a matrix obtained by multiplying the rows of $\mathbf{A}$ by the columns of $\mathbf{B}$.

Given two matrices $\mathbf{A}$ and $\mathbf{B}$ with dimensions $m \times n$ and $n \times p$, respectively, their product $\mathbf{C} = \mathbf{AB}$ is an $m \times p$ matrix defined by:
$$
c_{i,j} = \sum_{k=1}^n a_{i,k}b_{k,j}
$$
for $1 \leq i \leq m$ and $1 \leq j \leq p$.

Example:
$$
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix} \begin{bmatrix}
-1 & 0 & 2 \\
2 & -3 & 1
\end{bmatrix} =
\begin{bmatrix}
3 & -6 & 4 \\
5 & -12 & 10 \\
7 & -18 & 16
\end{bmatrix}
$$

## Rules for Matrix Operations

You reference some rules of matrix operations in the other blog (See [the basic matrix operation](./02.basic_matrix.qmd)).

### Commutative Law of Matrix Addition

Matrix addition is commutative, which means that changing the order of the matrices being added does not affect the result.

$$
\begin{align*}
\mathbf A + \mathbf B = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} + \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} = \begin{bmatrix}
1 + 5 & 2 + 6 \\
3 + 7 & 4 + 8
\end{bmatrix} = \begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix}
\\
\mathbf B + \mathbf A = \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} + \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} = \begin{bmatrix}
5 + 1 & 6 + 2 \\
7 + 3 & 8 + 4
\end{bmatrix} = \begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix}
\end{align*}
$$

### Distributive Law

Matrix addition distributes over matrix multiplication, which means that multiplying a matrix by the sum of two matrices is the same as multiplying the matrix by each individual matrix and then adding the results.

$$
\begin{align*}
\mathbf A (\mathbf B + \mathbf C )
&= \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} \cdot \left( \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} + \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} \right) = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} \cdot \begin{bmatrix}
14 & 16 \\
18 & 20
\end{bmatrix} = \begin{bmatrix}
70 & 76 \\
158 & 172
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\mathbf A \mathbf B + \mathbf A \mathbf C 
&= \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} \cdot \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} + \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} \cdot \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} = \begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix} + \begin{bmatrix}
23 & 26 \\
31 & 34
\end{bmatrix} = \begin{bmatrix}
70 & 76 \\
158 & 172
\end{bmatrix}
\end{align*}
$$


### Associative Law

Matrix addition is associative, which means that changing the grouping of the matrices being added does not affect the result.

$$
\begin{align*}
(\mathbf A + \mathbf B )+ \mathbf C 
&= \left( \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} + \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} \right) + \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} = \begin{bmatrix}
1 + 5 & 2 + 6 \\
3 + 7 & 4 + 8
\end{bmatrix} + \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} = \begin{bmatrix}
6 & 8 \\
10 & 12
\end{bmatrix} + \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} = \begin{bmatrix}
15 & 18 \\
21 & 24
\end{bmatrix}
\end{align*}
$$

$$
\begin{align*}
\mathbf A + (\mathbf B + \mathbf C) 
&= \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} + \left( \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} + \begin{bmatrix}
9 & 10 \\
11 & 12
\end{bmatrix} \right) = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix} + \begin{bmatrix}
14 & 16 \\
18 & 20
\end{bmatrix} = \begin{bmatrix}
15 & 18 \\
21 & 24
\end{bmatrix}
\end{align*}
$$

