---
title: "Basic Matrix (5) - Matrix Multiplication"
subtitle: Linear Transition
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/31/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
execute:
  warning: false
  message: false
  eval: false
draft: true
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

# Identity Matrix

항등 핼렬, 단위 행렬

항등 행렬 또는 단위 행렬은 정사각 행렬로, 대각선 요소는 모두 1이고 대각선을 제외한 모든 요소는 0인 행렬입니다. 크기가 n인 항등 행렬은 $\mathbf{I}_n$ 으로 표기된다.

## Example

Example of a $3\times 3$ identity matrix, $\mathbf{I}_3$:
$$
\begin{equation}
\mathbf{I}_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}
\end{equation}
$$

* 보통 $\mathbf{I}_{1\times 1}=\mathbf{I}_{1}=1, \quad \mathbf{I}_{2\times 2}=\mathbf{I}_2, \quad\mathbf{I}_{3\times 3}=\mathbf{I}_3, \quad\mathbf{I}_{4\times 4}=\mathbf{I}_4$ 로 표현한다.

## 행렬곱의 열분해

$\mathbf{AB=C}$

$$
\begin{align*}
\begin{bmatrix}
- & - & \cdots & - \\
- & - & \cdots & - \\
- & - & \ddots & - \\
- & - & \cdots & -
\end{bmatrix}
\begin{bmatrix}
| & 0  & \cdots & 0 \\
| & 0  & \cdots & 0 \\
| & 0  & \ddots & 0 \\
| & 0  & \cdots & 0
\end{bmatrix}
=
\begin{bmatrix}
| & 0  & \cdots & 0 \\
| & 0  & \cdots & 0 \\
| & 0  & \ddots & 0 \\
| & 0  & \cdots & 0
\end{bmatrix}
\end{align*}
$$

위에서 보는 바와 같이 $\mathbf{C}$ 의 1열 에 영향을 주는 것은 $\mathbf{A}$ 의 모든 열 $\mathbf{B}$ 의 1열이다.
이를 수식화 하면 아래와 같이 행렬 $\mathbf{B}$ 의 열분해가 된다. 역으로 이렇게 열 분해가 된 것을 이어 붙이면 행렬 곱 $\mathbf{AB}$ 와 같아진다. 
그러므로 $\mathbf{B}$ 의 열을 각 각 $\mathbf{A}$ 와 곱을 해서 $\mathbf{c}_i$ 를 n번 구해서 이어 붙이는 것이나 행렬 곱 $\mathbf{AB}$ 을 수행한 것이나 같은 결과를 얻게 된다.
그러므로 핼렬곱이 더 간단한 연산 표현 방식이다.

$$
\begin{align*}
\mathbf{A}\mathbf{b}_1&=\mathbf{c}_1 \\
\mathbf{A}\mathbf{b}_2&=\mathbf{c}_1 \\
& \vdots \\
\mathbf{A}\mathbf{b}_n&=\mathbf{c}_n 

\end{align*}
$$


## Properties

Some properties of an identity matrix include:

* 어떤 행렬이 항등 행렬과 곱해져도 원래 행렬과 같다: $\mathbf{A} \mathbf{I} = \mathbf{I} \mathbf{A} = \mathbf{A}$.
  * 행렬 곱셈 $\mathbf{y}=\mathbf{Fx}$ 에서 가중치 행렬 $\mathbf{F}$ 는 $\mathbf{y}$ 와 $\mathbf{x}$ 사이의 선형 매핑으로 볼 수 있다.
  * 이 연산에서 항등 행렬 $\mathbf{I}$ 를 $\mathbf{F}$ 자리에 대입하면 선형 매핑은 $y_1=x_1, \ldots, y_n=x_n$ 과 같은 항등 함수 관계로 표현된다.
  * 다시 말해, $\mathbf{x}$ 를 항등 함수 $\mathbf{I}$ 에 입력하면 $\mathbf{y}$ 는 $\mathbf{x}$ 와 동일해진다.
  * 이 원리는 $\mathbf{x}$ 가 행렬로 변환되더라도 여전히 적용된다. 따라서 $\mathbf{I} \mathbf{A} = \mathbf{A}$ 가 성립한다.
  * 마찬가지로 $\mathbf{A} \mathbf{I}$ 를 고려하고 열 분해를 적용하면 $\mathbf{A}$ 의 열들이 $\mathbf{I}$ 의 열 벡터 (표준 단위 벡터)와 곱해져서 $\mathbf{A}$ 의 해당 열들이 출력된다.
  * 따라서 $\mathbf{A} \mathbf{I} = \mathbf{A}$ 가 성립한다.
* 임의의 행렬과 해당 역행렬의 곱은 항등 행렬이다: $\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I}$.
* 항등 행렬의 행렬식은 1이다: $\det(\mathbf{I}) = 1$.
* 항등 행렬은 대칭 행렬이다: $\mathbf{I} = \mathbf{I}^T$.


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">


# Identity Matrix

항등 핼렬, 단위 행렬

An identity matrix is a square matrix in which all the diagonal elements are equal to $1$ and all the off-diagonal elements are equal to 0. The notation for an identity matrix of size $n$ is $\mathbf{I}_n$.

## Example

Example of a $3\times 3$ identity matrix, $\mathbf{I}_3$:
$$
\begin{equation}
\mathbf{I}_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}
\end{equation}
$$

* Typically, $\mathbf{I}{1\times 1}=\mathbf{I}{1}=1$, $\mathbf{I}_{2\times 2}=\mathbf{I}2$, $\mathbf{I}{3\times 3}=\mathbf{I}3$, and $\mathbf{I}{4\times 4}=\mathbf{I}_4$ are used to represent the identity matrices of respective sizes.

## Matrix multiplication column decomposition

$\mathbf{AB=C}$

$$
\begin{align*}
\begin{bmatrix}
- & - & \cdots & - \\
- & - & \cdots & - \\
- & - & \ddots & - \\
- & - & \cdots & -
\end{bmatrix}
\begin{bmatrix}
| & 0  & \cdots & 0 \\
| & 0  & \cdots & 0 \\
| & 0  & \ddots & 0 \\
| & 0  & \cdots & 0
\end{bmatrix}
=
\begin{bmatrix}
| & 0  & \cdots & 0 \\
| & 0  & \cdots & 0 \\
| & 0  & \ddots & 0 \\
| & 0  & \cdots & 0
\end{bmatrix}
\end{align*}
$$

As seen above, the elements in the first column of matrix $\mathbf{C}$ are influenced by all the columns of matrix $\mathbf{A}$ and the first column of matrix $\mathbf{B}$. This can be formulated as the column decomposition of matrix $\mathbf{B}$. Conversely, by concatenating these decomposed columns, we obtain the matrix product $\mathbf{AB}$. Therefore, obtaining $\mathbf{c}_i$ by multiplying each column of $\mathbf{B}$ with $\mathbf{A}$ and concatenating them yields the same result as performing the matrix multiplication $\mathbf{AB}$. Thus, matrix multiplication provides a simpler way to express the operation.

$$
\begin{align*}
\mathbf{A}\mathbf{b}_1&=\mathbf{c}_1 \\
\mathbf{A}\mathbf{b}_2&=\mathbf{c}_1 \\
& \vdots \\
\mathbf{A}\mathbf{b}_n&=\mathbf{c}_n 

\end{align*}
$$


## Properties

Some properties of an identity matrix include:

* Multiplying any matrix by an identity matrix results in the same matrix: $\mathbf{A} \mathbf{I} = \mathbf{I} \mathbf{A} = \mathbf{A}$.
  * In matrix multiplication $\mathbf{y} = \mathbf{Fx}$, the weight matrix $\mathbf{F}$ can be viewed as a linear mapping between $\mathbf{y}$ and $\mathbf{x}$.
  * When the identity matrix $\mathbf{I}$ is substituted for $\mathbf{F}$ in this operation, the linear mapping is represented as an identity function, where $y_1 = x_1, \ldots, y_n = x_n$.
  * In other words, when $\mathbf{x}$ is input to the identity function $\mathbf{I}$, $\mathbf{y}$ becomes equal to $\mathbf{x}$.
  * This principle still holds even when $\mathbf{x}$ is transformed into a matrix. Therefore, $\mathbf{I} \mathbf{A} = \mathbf{A}$ holds true.
  * Similarly, considering $\mathbf{A} \mathbf{I}$ and applying column decomposition, the columns of $\mathbf{A}$ are multiplied by the column vectors of $\mathbf{I}$ (standard unit vectors), resulting in the corresponding columns of $\mathbf{A}$.
  * Therefore, $\mathbf{A} \mathbf{I} = \mathbf{A}$ holds true.
* The product of any matrix and its corresponding inverse is an identity matrix: $\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I}$.
* The determinant of an identity matrix is 1: $\det(\mathbf{I}) = 1$.
* An identity matrix is symmetric: $\mathbf{I} = \mathbf{I}^T$.


</div>

