---
title: $\epsilon - \delta$ Method
subtitle: The Precise definition of a Limit
description: |
  Pre-requisite for convergence in probability and convergence in distribution.
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/14/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

## Definition

::: {#def-function_limit}

Let $f$ be a function defined on some open interval that contains the number $a$, exccept possibly at $a$ itself. Then, $f$ is said to converge to the real number $L$ provided that for every number $\epsilon>0$, there is a number $\delta>0$ such that
$$
\text{if } 0<|x-a|<\delta \text{ then } |f(x)-L|<\epsilon
$$

If $f(x)$ converges to $L$, then $L$ is called the**limit** of $f(x)$ as $x$ approaches $a$ , and we write
$$
\lim_{x \to a} f(x) =L
$$

If a function does not coverge to a real number, it is said to diverge.

:::

먼저, 위의 정의를 하나씩 곱 씹어보면, $\text{if } 0<|x-a|<\delta \text{ then } |f(x)-L|<\epsilon$ 에서 $|x-a|$ 와 $|f(x)-L|$ 가 절대값으로 표기가 되어 있기 때문에 거리(distance)로 해석이 된다. 또한, $|x-a|$ 는 임의의 충분히 작은 수 $\delta$ 와 대응이 되고 $|f(x)-L|$ 는 임의의 충분히 작은 수 $\epsilon$ 와 대응이 되는 것을 숙지해야한다. 그리고 $\epsilon - \delta$ Method 라는 표현에서도 이해에 대한 실마리를 얻을 수 있는데 $\epsilon$ 이 먼저 정해지면 $\delta$ 를 그 후에 결정할 수 있다. 좀 더 자세히 말하면, 궁극적으로 $\delta$ 를 $\epsilon$ 의 함수 $\delta(\epsilon)$ 로 표현하여 함수의 수렴성을 증명하게 된다. 

그럼 본격적으로 limit의 notation, $\lim_{x \to a} f(x) =L$ 을 해석하면, 고등학교 때 우리는 이 표현을 $x$ 가 $a$ 로 한없이 가까워질 때 $f(x)$ 의 limit은 $L$ 이다 라고 배웠다. 이를 조금 더 정밀하게 해석하면, $x$ 와 $a$ 사이의 거리가 만족할 만큼 충분히 작아질 때, (하지만 $x\ne a$), $f(x)$ 와 $L$ 사이의 거리가 임의대로 작아 질수 있다는 것을 의미한다. 하지만 이 표현 역시 수학적이지 않다. 왜냐면 위의 문장은 **만족할 만큼 충분히 작아질 때** 라는 표현 때문에 명제(statement)가 될 수 없기 때문이다. 사람의 주관마다 어떤 사람은 거리가 1 일 때 충분히 작다고 말 할 수 있고 좀 더 정밀한 사람의 경우 0.0001 이 충분히 작다고 말할 수 있기 때문이다. 또 어떤 사람은 100이 충분히 작은 거리라고 표현할 수 있는 모호성이 존재한다. 

여기서, $\lim_{x \to a} f(x) =L$ 의 해석을 분석해보고 수식화 시켜보자. 

'$x$ 와 $a$ 사이의 거리가 만족할 만큼 충분히 작아질 때, (하지만 $x\ne a$), $f(x)$ 와 $L$ 사이의 거리가 임의대로 작아 질수 있다.' 는 

* 조건절: '$x$ 와 $a$ 사이의 거리가 만족할 만큼 충분히 작아질 때, (하지만 $x\ne a$),
* 결과절: $f(x)$ 와 $L$ 사이의 거리가 임의대로 작아 질수 있다.' 
와 같이 조건절과 결과절로 나눌 수 있다. 이를 수식으로 표현하면, 거리의 의미는 수학에서 절대값으로 표현될 수 있기 때문에

* 조건절: $|x-a|$ 가 만족할 만큼 충분히 작아질 때, (하지만 $x\ne a$),
* 결과절: $|f(x)-L|$ 가 임의대로 작아 질수 있다.' 
와 같이 표현 될 수 있다.

위의 정의 @def-function_limit 의 $\text{if } 0<|x-a|<\delta \text{ then } |f(x)-L|<\epsilon$ 를 유심히 보면 애매한 표현을 수학적으로 표현하기 위해 **누구나 만족할만한 충분히 작은 수** 를 **임의의 양수 (every number $\epsilon>0$ or any number $\epsilon>0$)**라고 표현하여 명제화 시키는 것을 볼 수 있다. 

부등식으로 표현된 명제, $\text{if } 0<|x-a|<\delta \text{ then } |f(x)-L|<\epsilon$ 를 대수적으로 변형시켜 분석해보자.

* 조건절: $\text{if } 0<|x-a|<\delta$ 

$$
\begin{aligned}
    |&x-a|<\delta \\
    -\delta<&x-a<\delta \text{  }(\because \delta>0)\\
    a-\delta<&x<a+\delta\\
    0<|&x-a|\text{  }(\because x \ne a)\\
\end{aligned}
$$


* 결과절: $\text{ then } |f(x)-L|<\epsilon$
$$
\begin{aligned}
    |&f(x)-L|<\epsilon \\
    -\epsilon<&f(x)-L<\epsilon \text{  }(\because \epsilon>0)\\
    L-\epsilon<&f(x)<L+\epsilon\\
    0<|&x-a|<\delta\text{  }(\because x \ne a)\\
\end{aligned}
$$


위의 간단한 부등식 조작으로 3가지 사실을 재정리했다.

1. $x$ 의 범위 : $a-\delta<x<a+\delta$
1. $|x-a|$ 의 범위: $0<|x-a|$
1. $f(x)$ 의 범위: $L-\epsilon<f(x)<L+\epsilon\\$

이 3가지 사실을 기반으로 limit의 정의 (@def-function_limit)를 다시 해석해보면,  

*$lim_{x\to a}f(x)=L$ 은 모든 임의의 양수 $\epsilon>0$ 에 대해서,$x \in (a-\delta,a-\delta)$ (i.e. $x$ 가 $(a-\delta,a-\delta)$ 범위안에 있다) 이고 $x\ne a$ 라면 $f(x) \in (L-\epsilon,L+\epsilon)$ 을 만족시키는 임의의 양수 $\delta>0$ 가 존재한다* 

라고하는 좀 더 쉬운 해석이 가능해진다. 다른 방식으로 표현하면,

$$
\begin{aligned}
\text{If } f(x) \in (L-\epsilon,L+\epsilon), &\text{then } \exists \text{ } x \in (a-\delta,a+\delta)  \ni \\ 
 f:(a-\delta,a+\delta) &\rightarrow (L-\epsilon,L+\epsilon)
\end{aligned}
$$

여기서, $f(x)\in (L-\epsilon,L+\epsilon)$ 은 $f(x)$ 를 $L$ 의 근방 $(\text{i.e. } L-\text{neighborhood})$ 으로 한정시켰다고 표현한다. 같은 방식으로, $x \in (a-\delta,a+\delta)$ 은 $x$ 를 $a$ 의 근방 $(\text{i.e. } a-\text{neighborhood})$ 한정시켰다고 표현한다. 여기서, neighborhood는 $\epsilon$ 과 $\delta$ 가 정해져야 결정될 수 있는 것을 볼 수 있다. 그리고 if 조건문에 의해 $\epsilon$ 에 의해 $\delta$ 가 정해진다는 것을 미루어 짐작할 수 있다.

이를 또 다르게 해석할 수 있는데,

$$
\begin{aligned}
\text{If } \lim_{x \to a}f(x)=L, &\text{ then } \exists \delta > 0 \ni\\
 \text{if } x \in (a-\delta,a+\delta), &\text{ then } f(x) \in (L-\epsilon,L+\epsilon)
\end{aligned}
$$

위의 표현을 해석해보면, $x$ 가 $a$ 로 한없이 다가가서 $L$ 에 수렴한다면, $x$ 를 $a$ 근방에 한정시켜 $f(x)$ 가 $L$ 근방에 한정되는 임의의 양수 $\delta$ 가 존재한다.

실제 많은 참고서적에서 예시를 들어 문제를 풀때는 이 표현을 이용한다.

#### Example

find $\delta$ corresponding to $\epsilon=0.5$ in the definition of a limit for $f(x)=x^2-4x+5$ with $a=1$ and $L=2$.
$$
\text{if } |x-1|<\delta \text{ then} |(x^2-4x+5)-2|<0.5
$$

* solution

$$
-0.5<x^2-4x+5-2<0.5
1.5 <x^2-4x+5<2.5

$$


:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::

reference : james steward, Calculus

</div>
