<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="dcterms.date" content="2023-04-22">
<meta name="description" content="Due to security concerns, it is difficult to display the data used in this project.">

<title>Kwangmin Kim - DevOps Project: Diagnostic Device QC Platform Construction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/CV/index.html">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../../docs/projects/index.html" aria-current="page">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/blog/index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">
 <span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"><i class="bi bi-github" role="img" aria-label="Github">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"><i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/blog/index.html"><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">DevOps Project: Diagnostic Device QC Platform Construction</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/index.html" class="sidebar-item-text sidebar-link">Projects</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">FDA Validation</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/dsp_validation/index.html" class="sidebar-item-text sidebar-link">FDA Algorithms Validation</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">LLFS</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/project_description.html" class="sidebar-item-text sidebar-link">Description</a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">Self Project</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/self_description.html" class="sidebar-item-text sidebar-link">Project Description</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/data_preparation.html" class="sidebar-item-text sidebar-link">Data Preparation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/eda.html" class="sidebar-item-text sidebar-link">EDA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/mining.html" class="sidebar-item-text sidebar-link">Data Mining</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/statistical_approach.html" class="sidebar-item-text sidebar-link">Statistical Approach</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/ml_approach.html" class="sidebar-item-text sidebar-link">ML Approach</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/LLFS/report.html" class="sidebar-item-text sidebar-link">Conclusion</a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Diagnostic Device QC</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/qc_platform/index.html" class="sidebar-item-text sidebar-link active">DevOps Project: Diagnostic Device QC Platform Construction</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">Platform Plan</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/platform_plan/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">Diagnostic Algorithm</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/backfitting/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">Clinical Data Analysis</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/pcr_clinical/index.html" class="sidebar-item-text sidebar-link">PCR Clinical Data Analysis</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">Noise Test Prediction</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/noise_prediction/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">Heavy Metal Removal</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/heavy_metal/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">Diffusion Model</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/social_network/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">Phellinus Linteus Effects</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../docs/projects/phellinus_linteus/index.html" class="sidebar-item-text sidebar-link">index.html</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">DevOps Project: Diagnostic Device QC Platform Construction</h1>
<p class="subtitle lead">Long Term Strategy: Seegene’s Full Automation</p>
</div>

<div>
  <div class="description">
    Due to security concerns, it is difficult to display the data used in this project.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kwangmin Kim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 22, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<ul class="nav nav-pills" id="language-tab" role="tablist">
<li class="nav-item" role="presentation">
<button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">
Korean
</button>
</li>
<li class="nav-item" role="presentation">
<button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">
English
</button>
</li>
<div class="tab-content" id="language-tabcontent">

<div id="Korean" class="tab-pane fade show active" role="tabpanel" aria-labelledby="Korean-tab">
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<ul>
<li>진단 장비의 품질 관리는 의료 장비와 연관된 제품의 특성상 Global Market 진출시 각 나라의 정부에서 요구하는 규제사항 중 하나이다.
<ul>
<li>시약의 안정성 검증 요구</li>
<li><strong>장비의 안정성 검증 요구</strong></li>
<li>Software의 안정성 검증 요구</li>
<li>Diagnostic Algorithm의 안정성 검증 요구</li>
</ul></li>
<li>현재 Seegene이 사용하고 있는 진단 장비는 자사 제품이 아니기 때문에 진단 장비의 품질 관리 방식에 어려움이 있다.</li>
<li>PCR 기기의 noise test는 의료 장비의 QC process 중 하나로서, Seegene의 시약 제품의 성능 안정성과 직접적으로 영향을 주는 품질 검증 시스템이다.</li>
<li>회사의 규모가 커지고 잦은 조직 개편으로 수동 방식의 noise tests가 여러 부서로 이관됨에 따라 noise test 수행자의 이해도와 숙련도가 떨어져 noise test가 올바르게 수행되지 않고 있다.</li>
<li>씨젠의 장기 목표인 전사 자동화를 위해 noise test를 자동화하는 프로젝트가 발탁됐다.</li>
</ul>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<ul>
<li>2020.12.19~2021.03.06에 입고된 PCR기기 2201대를 2552번의 실험에서 만들어진 61,248개의 신호에서 얻은 data-driven parameters로 장비의 성능을 평가하여 합격/불합격 뿐만 아니라 장비에 등급을 차등 부여하여 시간에 따른 장비의 성능을 지속적으로 분석 가능하게 한다.</li>
<li>다음의 주요 문제점을 개선한다.
<ul>
<li>신호의 증폭에 크기에 따라 noise test 결과에 영향을 크게 주어 잘못된 결과를 산출해주는 metric 개선</li>
<li>단순한 휴먼 에러 신호에 무조건적으로 장비의 불합격처리가 결정 되는 문제 보완하여 robust한 평가체계로 현업부서의 부담을 덜어준다.</li>
<li>장비 고유에서 발생하는 pattern을 찾아 장비 error 신호를 labeling 한다.</li>
</ul></li>
<li>수동 계산과정에 소요되는 시간을 20번의 test당 30분에서 웹 기반의 자동화로 약 2~3분내로 단축시킬 수 있다.</li>
<li>씨젠의 full automation의 best practice로 만들어 IT 부분과 제조 부문 및 BT부문과의 협력체계 구축 및 활성화 한다.</li>
<li>시각화와 noise test result history를 제공하여 추적 및 VOC 대응 system을 구축한다.</li>
</ul>
</section>
<section id="strategies" class="level2">
<h2 class="anchored" data-anchor-id="strategies">Strategies</h2>
<section id="strategy-a" class="level3">
<h3 class="anchored" data-anchor-id="strategy-a">Strategy A</h3>
<ul>
<li>현업 부서와의 긴밀한 소통으로 QC process를 세분화하여 앞 단계 QC에서 발생하는 data를 활용하여 뒷 단계 QC인 noise test의 결과를 예측한다.</li>
<li>noise가 적다고 확실시 되는 기기에 한해서 noise test 생략</li>
</ul>
</section>
<section id="strategy-b" class="level3">
<h3 class="anchored" data-anchor-id="strategy-b">Strategy B</h3>
<ul>
<li>전체 QC 프로세스를 자동화 또는 반 자동화</li>
<li>기존의 noise 측정 metric 분석 및 새로운 metric 생성하여 검사 결과의 정확도를 향상</li>
<li>시각화와 noise test result history를 제공하여 실무자의 이해도를 높이고 관리가능하게 한다.</li>
</ul>
</section>
</section>
<section id="issues" class="level2">
<h2 class="anchored" data-anchor-id="issues">Issues</h2>
<ul>
<li>현업 업무 기술서 부재</li>
<li>실무자의 백업 실수</li>
<li>부서마다 산재된 데이터</li>
<li>높은 난이도의 data cleansing
<ul>
<li>실무자의 데이터로부터 분석 가능한 데이터 선별</li>
<li>실무자의 데이터의 오입력</li>
<li>data 및 문서의 DRM 수동해제</li>
</ul></li>
<li>reverse engineering 필요</li>
<li>잦은 조직 개편으로 관련 인원 및 부서 연락체계 부재</li>
</ul>
</section>
<section id="required-skills" class="level2">
<h2 class="anchored" data-anchor-id="required-skills">Required Skills</h2>
<ul>
<li>Back-end Engineering for DevOps Pipeline Construction</li>
<li>Data Engineering for data cleansing and reverse engineering</li>
<li>Data Modeling for a RDB system construction</li>
<li>Statistical Analysis for the noise test performance verification</li>
<li>Machine Learning for pattern analysis</li>
<li>Front-end Engineering for UI/UX construction</li>
<li>Biologics, Biophysics, Physics Knowledge</li>
</ul>
</section>
<section id="colaborators" class="level2">
<h2 class="anchored" data-anchor-id="colaborators">Colaborators</h2>
<ul>
<li>1 data scientist (me) - project owner</li>
<li>5 mechanical engineers</li>
<li>4 biologists</li>
<li>2 patent attoneys</li>
<li>2 data engineers</li>
<li>3 full stack developers</li>
<li>1 advisor (a professor of Computer Science at Seoul National University)</li>
</ul>
</section>
<section id="acheivements" class="level2">
<h2 class="anchored" data-anchor-id="acheivements">Acheivements</h2>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Noise Test</th>
<th style="text-align: left;">As-Is</th>
<th style="text-align: left;">To-Be</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sample Size</td>
<td style="text-align: left;">n=100</td>
<td style="text-align: left;">2552번의 실험에서 얻은 신호 n=61,248</td>
</tr>
<tr class="even">
<td style="text-align: center;">Evaluation Metrics</td>
<td style="text-align: left;">2 metrics</td>
<td style="text-align: left;">10 metrics ( the exsting 2 metrics + new 8 metrics)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Input Process</td>
<td style="text-align: left;">manually copy &amp; paste data of excel files extracted from a certain program</td>
<td style="text-align: left;">Web-Based Automation, upload multiple experiment files</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output Process</td>
<td style="text-align: left;">Batch Evaluation method, if even one of the signals from the equipment fails, the equipment fails. (Blind Spot: If there is one human error signal, the equipment is unconditionally disqualified.)</td>
<td style="text-align: left;">Differential Evaluation method, The signals from the equipment are scored, the average value is obtained, and the equipment is graded A+, A, B, and F. Failed if F. Robust on the error signal as it excludes the error signal from evaluation</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 1</td>
<td style="text-align: left;">pass: 92.58%, fail: 7.42%</td>
<td style="text-align: left;">A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output 2</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Visualized Plots and Tables.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 3</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Normal Signals, Human Errors, Device Errors, Manufacturing Errors</td>
</tr>
<tr class="even">
<td style="text-align: center;">Time Consumed</td>
<td style="text-align: left;">About 30 minutes per 20 experiments</td>
<td style="text-align: left;">About 25 minutes per 2552 experiments</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Data Management</td>
<td style="text-align: left;">Non-standard management method (stored in NAS directory in a different form as an Excel file in a different way for each worker)</td>
<td style="text-align: left;">Automatic loading in DB in standardized form by a scheduler (equipment failure tracing analysis becomes possible)</td>
</tr>
</tbody>
</table>
<section id="remarkable" class="level3">
<h3 class="anchored" data-anchor-id="remarkable">Remarkable</h3>
<ul>
<li>The noise test was abolished in the whole QC Process because I statistically proved that the noise test result does not have a significant impact on the difference of the mean of the final result in the whole diagnostic process at the 1% significance level.</li>
<li>It turned out to be an opportunity for the Data Science department to increase their understanding of experiments and data generated from equipment.</li>
<li>It served as the basis for building a company-wide DB and building a platform architecture.</li>
</ul>
</section>
</section>
</div>
<div id="English" class="tab-pane fade" role="tabpanel" aria-labelledby="English-tab">
<section id="background-1" class="level2">
<h2 class="anchored" data-anchor-id="background-1">Background</h2>
<ul>
<li>Quality Control of diagnostic equipment is one of the necessities for the regulations required by the government of each country when entering the global market due to the nature of products related to medical equipment.
<ul>
<li>Reagent stability verification &amp; validation required</li>
<li><strong>Equipment stability verification &amp; validation request</strong></li>
<li>Software stability verification &amp; validation request</li>
<li>Stability Verification &amp; validation Request of Diagnostic Algorithm</li>
</ul></li>
<li>Since the diagnostic equipment currently being used by Seegene is not its own product, it is difficult to manage the quality of the diagnostic equipment.</li>
<li>The noise test of PCR equipment is one of the QC processes of medical equipments, and it is a quality verification system that directly affects the performance stability of Seegene’s reagent products.</li>
<li>As the size of the company grows and frequent organizational reshuffles result in manual noise tests being transferred to various departments, the noise test performers’ understanding and skills are low, resulting in noise tests not being performed correctly.</li>
<li>A project to automate the noise test was selected for Seegene’s long-term goal of enterprise automation.</li>
</ul>
</section>
<section id="objective-1" class="level2">
<h2 class="anchored" data-anchor-id="objective-1">Objective</h2>
<ul>
<li>Data-driven parameters obtained from 61,248 signals from 2552 experiments were used to evaluate 2201 PCR devices, which were stocked between 2020.12.19 and 2021.03.06. yield Enables continuous analysis of equipment performance over time.</li>
<li>Improve the following major problems:
<ul>
<li>Improved metrics that produces erroneous results by greatly affecting the noise test result depending on the size of the signal amplification.</li>
<li>It relieves the burden on the field department with a robust evaluation system by supplementing the problem of unconditionally determining equipment rejection in response to a simple human error signal.</li>
<li>Equipment error signals are labeled by finding patterns that occur in equipment.</li>
</ul></li>
<li>The time required for the manual calculation process can be reduced from 30 minutes per 20 tests to about 2 to 3 minutes with web-based automation.</li>
<li>By making it the best practice of Seegene’s full automation, establish and vitalize the cooperation system between the IT, manufacturing and BT sectors.</li>
<li>Visualization and noise test result history are provided to build a tracking and VOC response system.</li>
</ul>
</section>
<section id="strategies-1" class="level2">
<h2 class="anchored" data-anchor-id="strategies-1">Strategies</h2>
<section id="strategy-a-1" class="level3">
<h3 class="anchored" data-anchor-id="strategy-a-1">Strategy A</h3>
<ul>
<li>The QC process is subdivided through close communication with the field departments, and the results of the noise test, which is the next stage QC, are predicted by utilizing the data generated in the previous stage QC.</li>
<li>Noise test omitted only for devices that are certain to have low noise.</li>
</ul>
</section>
<section id="strategy-b-1" class="level3">
<h3 class="anchored" data-anchor-id="strategy-b-1">Strategy B</h3>
<ul>
<li>Automate or semi-automate the entire QC process</li>
<li>Improve the accuracy of inspection results by analyzing the existing noise measurement metric and creating a new metric</li>
<li>Visualization and noise test result history are provided to increase the understanding of practitioners and enable management</li>
</ul>
</section>
</section>
<section id="issues-1" class="level2">
<h2 class="anchored" data-anchor-id="issues-1">Issues</h2>
<ul>
<li>Absence of job description</li>
<li>Backup Mistakes by Practitioners</li>
<li>Data scattered across departments</li>
<li>High level of data cleansing
<ul>
<li>Select data that can be analyzed from practitioner data</li>
<li>Incorrect input of practitioner data</li>
<li>Manual release of DRM for data and documents</li>
</ul></li>
<li>reverse engineering required</li>
<li>Absence of contact system for related personnel and departments due to frequent organizational reshuffle</li>
</ul>
</section>
<section id="required-skills-1" class="level2">
<h2 class="anchored" data-anchor-id="required-skills-1">Required Skills</h2>
<ul>
<li>Back-end Engineering for DevOps Pipeline Construction</li>
<li>Data Engineering for data cleansing and reverse engineering</li>
<li>Data Modeling for a RDB system construction</li>
<li>Statistical Analysis for the noise test performance verification</li>
<li>Machine Learning for pattern analysis</li>
<li>Front-end Engineering for UI/UX construction</li>
<li>Biologics, Biophysics, Physics Knowledge</li>
</ul>
</section>
<section id="colaborators-1" class="level2">
<h2 class="anchored" data-anchor-id="colaborators-1">Colaborators</h2>
<ul>
<li>1 data scientist (me) - project owner</li>
<li>5 mechanical engineers</li>
<li>4 biologists</li>
<li>2 patent attoneys</li>
<li>2 data engineers</li>
<li>3 full stack developers</li>
<li>1 advisor (a professor of Computer Science at Seoul National University)</li>
</ul>
</section>
<section id="acheivements-1" class="level2">
<h2 class="anchored" data-anchor-id="acheivements-1">Acheivements</h2>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Noise Test</th>
<th style="text-align: left;">As-Is</th>
<th style="text-align: left;">To-Be</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sample Size</td>
<td style="text-align: left;">n=100</td>
<td style="text-align: left;">Signals from 2552 experiments, n=61,248</td>
</tr>
<tr class="even">
<td style="text-align: center;">Evaluation Metrics</td>
<td style="text-align: left;">2 metrics</td>
<td style="text-align: left;">10 metrics ( the exsting 2 metrics + new 8 metrics)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Input Process</td>
<td style="text-align: left;">manually copy &amp; paste data of excel files extracted from a certain program</td>
<td style="text-align: left;">Web-Based Automation, upload multiple experiment files</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output Process</td>
<td style="text-align: left;">Batch Evaluation method, if even one of the signals from the equipment fails, the equipment fails. (Blind Spot: If there is one human error signal, the equipment is unconditionally disqualified.)</td>
<td style="text-align: left;">Differential Evaluation method, The signals from the equipment are scored, the average value is obtained, and the equipment is graded A+, A, B, and F. Failed if F. Robust on the error signal as it excludes the error signal from evaluation</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 1</td>
<td style="text-align: left;">pass: 92.58%, fail: 7.42%</td>
<td style="text-align: left;">A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output 2</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Visualized Plots and Tables.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 3</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Normal Signals, Human Errors, Device Errors, Manufacturing Errors</td>
</tr>
<tr class="even">
<td style="text-align: center;">Time Consumed</td>
<td style="text-align: left;">About 30 minutes per 20 experiments</td>
<td style="text-align: left;">About 25 minutes per 2552 experiments</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Data Management</td>
<td style="text-align: left;">Non-standard management method (stored in NAS directory in a different form as an Excel file in a different way for each worker)</td>
<td style="text-align: left;">Automatic loading in DB in standardized form by a scheduler (equipment failure tracing analysis becomes possible)</td>
</tr>
</tbody>
</table>
<section id="remarkable-1" class="level3">
<h3 class="anchored" data-anchor-id="remarkable-1">Remarkable</h3>
<ul>
<li>The noise test was abolished in the whole QC Process because I statistically proved that the noise test result does not have a significant impact on the difference of the mean of the final result in the whole diagnostic process at the 1% significance level.</li>
<li>It turned out to be an opportunity for the Data Science department to increase their understanding of experiments and data generated from equipment.</li>
<li>It served as the basis for building a company-wide DB and building a platform architecture.</li>
</ul>
</section>
</section>
</div>



</div></ul></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>