---
title: Variable Types
subtitle: template
description: |
  template
categories:
  - template
author: Kwangmin Kim
date: 03/23/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

# Variable Types

Variable types can be classified with various perspectives depending on research purpose:

* From the perspective of a data type, variable types are largely divided into two categories:
    * quantitative variable: a variable containing quantitative data that represents quantity
    * categorical variable: a variable containing qualitative data that represents groups
* From the standpoint of modeling or experiment designs, variable types are largely divided into 3 categories:
    * independent variable: a variable (cause) that might have an effect on a dependent variabe (result).
    * dependent variable: a variable (result) that might be influenced by independent variables (cause).
    * control variable: a variable that is fixed to look into a relation between an independent variable in your interest and dependent variable.
* From the point of mathmatical view, variable types are categorized largely into 4 categories:
    * univariable: each subject gives rise to a single measurement of independent variable termed exploratory variable.
    * univariate: each subject gives rise to a single measurement of dependent variables termed response.
    * multivariate: each subject gives rise to a vector of measurements of independent variables termed exploratory variables.
    * multivariable: each subject gives rise to a vector of measurements of dependent variables termed responses.

## From the Point of Data Type

### Quantitative Variable

the values of the quantitative variables with which you can conduct arithematic operations. 
There are two types of quantitative variables: discrete and continuous.

#### Discrete Variables

* As integer, count valuess of individual items.
* ex: number of people, number of different events, etc.

#### Continuous Variables

* As real number, measurement values of continuous or uncountable values.
* ex: height, weight, distance, volume, age, etc.

### Categorical Variables

Categorical variables contain grouping values representing categories rather than quantity.
There are three types of categorical variables: binary, nominal, and ordinal variables.

#### Binary Variables

* Binary variables a.k.a dichotomous variables contain two types of values, true or false, 1 or 0  
* ex: disease/non-disease, heads/tails in flipping a coin, win/lose in a game

#### Nominal Variables

* catogories with no rank or order among them.
* ex: gender, races, colors, brands, company names

#### Ordinal Variables

* catogories ranked in a specific order
* ex: ranks in a game, places in a line, rating scale responses in a movie review


## From the Perspective of Modeling

Experiments or models are usually designed or built to discover what effect one variable has on another.

### Independent Variables 

* Independent variable is a variable you can set to observe an effect on the outcome of an experiment.	
* By many people, independent Variables are also commonly called predictors, explanatory variables, treatment variables, features, etc.

### Dependent variables 

* Dependent variable is a variable that represents the outcome of the experiment.
* By many people, dependent variables are also commonly called outcome variables, response variables, targets, etc. 

### Control variables

* Control variable is a variable that is held fixed throughout the experiment.
* Positive control: a variable that is set for showing effect on the dependent variable.
* Negative control: a variable that is set for showing no effect on the dependent variable.
* Internal control: a variable that is set for showing effect on the dependent variable with a researcher's certain intention.

::: {.callout-tip}

### FYI

Strictly speaking, the synonyms of independent and dependent variables are all slightly different for the different purpose.  

* In association research, the use of the terms “dependent” and “independent” should be avoided because the research does not focus on causality between one another.  
* When the before-and-after relationship is clear, there might be cases where one variable clearly precedes the other   
    * for example, rainfall leads to mud, rather than the other way around. 
    * In these cases, you may call the rainfall a predictor and the mud an outcome variable.

:::

## Perspective of Modeling

There are largely 3 types of variables: confounders, latent variables, and composite variables

### Confounders

* Confounding variables or confounders
    * Confounder is a variable that hides the true effect of another variable in an experiment by confounding the association between independent and dependent variables. This can happen when the 3rd variable has effect on both independent variable and dependent variable but the 3rd variable has not been controlled in your experiment. Confounders run a high risk of introducing a variety of research biases to your analysis result, particularly omitted variable bias.
* ex: When conducting a study on muscle mass increase for dumbbells in a gym, if gender is not included in the research model, gender is a confounder. This is because men and women have different innate muscle mass and baseline for lifting dumbbells.

### Latent variables

* Latent variable is a variable that can’t be measured directly but indirectly via a proxy.
* ex: lactose tolerance of a person cannot be measured directly but indirectly inferred from measurements of a person's can be inferred from measurements of digestion ability with biochemical metrics in a certain designed experiment.

### Composite variable

* Composite variable is a variable made by combining multiple variables of your data. These variables are created not when you measure it but when you analyze data, 
* ex: When your academic performance is measured with math, physics, literature, and writing composition, your numerical academic performance can be measured by combining math with physics, and your language academic performance by combining literature with writing composition.

## From the point of mathmatical view

* univariable: each subject gives rise to a single measurement of independent variable termed exploratory variable.
* univariate: each subject gives rise to a single measurement of dependent variables termed response.
* multivariate: each subject gives rise to a vector of measurements of independent variables termed exploratory variables.
* multivariable: each subject gives rise to a vector of measurements of dependent variables termed responses.

# Data Type

Data types can also be classified with various perspectives depending on research purpose:

* From the perspective of programming or computer science [data type](https://amplitude.com/blog/data-types)

| Data Type | Definition | Examples |
| --- | --- | --- |
| Integer (int) | Numeric data type for numbers without fractions | -707, 0, 707 |
| Floating Point (float) | Numeric data type for numbers with fractions | 707.07, 0.7, 707.00 |
| Character (char) | Single letter, digit, punctuation mark, symbol, or blank space | a, 1, ! |
| String (str or text) | Sequence of characters, digits, or symbols—always treated as text | hello, +1-999-666-3333 |
| Boolean (bool) | True or false values | 0 (false), 1 (true) |
| Enumerated type (enum) | Small set of predefined unique values (elements or enumerators) that can be text-based or numerical | rock (0), jazz (1) |
| Array | List with a number of elements in a specific order—typically of the same type | rock (0), jazz (1), blues (2), pop (3) |
| Date | Date in the YYYY-MM-DD format (ISO 8601 syntax) | 2021-09-28 |
| Time | Time in the hh:mm:ss format for the time of day, time since an event, or time interval between events | 12:00:59 |
| Datetime | Date and time together in the YYYY-MM-DD hh:mm:ss format | 2021-09-28 12:00:59 |
| Timestamp | Number of seconds that have elapsed since midnight (00:00:00 UTC), 1st January 1970 (Unix time) | 1632855600 |

* From the perspective of data measurement
    * longitudinal (or repeated) data: Each subject gives rise to a vector of measurements, but these represent the same response measured at a sequence of observation times
    * cross-sectional data : Outcome variable(s) and covariates that are measured at a single time point

## From the perspective of data measurement

### Longitudinal (or repeated) Data

### Cross-sectional Data

# Refrences

* [Scribbr](https://www.scribbr.com/methodology/types-of-variables/)

:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>

# Go to Content List

* [Project Content List](./docs/projects/index.qmd)
* [Blog Content List](./docs/blog/posts/content_list.qmd)