---
title: "Basics (3) - Vector Operations"
subtitle: Motivation, Scalr, Vector, Addition, Scalar Multiplication, Dot Product, Norm, Unit Vector, Projection, Cross Product, Column Vector, Row Vector, Linear Combination of Vectors, Outer Product
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/30/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: true
---


# Chapter 03

## 가우스-조던 소거법(Gauss-Jordan elimination)

{{< video https://youtu.be/Q1zCibRtI2A >}}

* $Ax=b$ 에서 $x$를 찾는 방법 &rarr; 이미 중학교 때 배운 것...
* $\begin{matrix}x+2y=4\\2x+5y=9\end{matrix} \quad \Rightarrow \quad \begin{matrix}2x+4y=8\\2x+5y=9\end{matrix} \quad \Rightarrow \quad y=1, x=2$

* $\begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 4 \\ 9 \end{bmatrix} \quad \Rightarrow \quad \begin{bmatrix}
    1 & 2 &\bigm| & 4 \\
    2 & 5 &\bigm| & 9 
\end{bmatrix}$ : 확장 행렬 표기
* 기본 행 연산 &larr; 가우스 조던 소거법의 핵심 규칙
  * 양 변에 0이 아닌 상수배를 해줌
  * 상수배한 행을 다른 행에 더하거나 뺌
  * 행끼리 자리를 바꿈

* $\begin{bmatrix}
    1 & 2 &\bigm| & 4 \\
    2 & 5 &\bigm| & 9 
\end{bmatrix} \quad \Rightarrow \quad \begin{bmatrix}
    1 & 2 &\bigm| & 4 \\
    0 & 1 &\bigm| & 1 
\end{bmatrix} \quad \Rightarrow \quad \begin{bmatrix}
    1 & 0 &\bigm| & 2 \\
    0 & 1 &\bigm| & 1 
\end{bmatrix} \quad \Rightarrow \quad y=1, x=2$
  * 왼쪽을 항등행렬로 만들어 주면, 오른 쪽에 연립방정식의 해가 나옴
    * 점차 off-diagonal elements를 0으로 만들어 주는 방향으로 진행

* 예
$$\begin{matrix}2x+y-z=8\\-3x-y+2z=-11\\-2x+y+2z=-3\end{matrix} \quad \Rightarrow \quad \begin{bmatrix}
    2 & 1 & -1 &\bigm| & 8 \\
    -3 & -1 & 2 &\bigm| & -11 \\
    -2 & 1 & 2 &\bigm| & -3 \\
\end{bmatrix}$$
  * 첫번째 행에 $\frac{2}{3}$ 곱해서 두번째 행렬에 더하기
    $$\begin{bmatrix}
    2 & 1 & -1 &\bigm| & 8 \\
    0 & \frac{1}{2} & \frac{1}{2} &\bigm| & 1 \\
    -2 & 1 & 2 &\bigm| & -3 \\
\end{bmatrix}$$
  * 첫번째 행을 마지막 행에 더하기
    $$\begin{bmatrix}
    2 & 1 & -1 &\bigm| & 8 \\
    0 & \frac{1}{2} & \frac{1}{2} &\bigm| & 1 \\
    0 & 2 & 1 &\bigm| & 5 \\
\end{bmatrix}$$
  * 두번째 행에 4를 곱해서 마지막 행을 빼기
    $$\begin{bmatrix}
    2 & 1 & -1 &\bigm| & 8 \\
    0 & \frac{1}{2} & \frac{1}{2} &\bigm| & 1 \\
    0 & 0 & -1 &\bigm| & 1 \\
\end{bmatrix}$$
  * 세번째 행에 $\frac{1}{2}$를 곱해서 두 번째 행에 더하기
    $$\begin{bmatrix}
    2 & 1 & -1 &\bigm| & 8 \\
    0 & \frac{1}{2} & 0 &\bigm| & \frac{3}{2} \\
    0 & 0 & -1 &\bigm| & 1 \\
\end{bmatrix}$$
  * 첫번째 행에서 세번째 행 빼기
    $$\begin{bmatrix}
    2 & 1 & 0 &\bigm| & 7 \\
    0 & \frac{1}{2} & 0 &\bigm| & \frac{3}{2} \\
    0 & 0 & -1 &\bigm| & 1 \\
\end{bmatrix}$$
  * 두번째 행에 2 곱해서 첫번째 행에서 빼기
    $$\begin{bmatrix}
    2 & 0 & 0 &\bigm| & 4 \\
    0 & \frac{1}{2} & 0 &\bigm| & \frac{3}{2} \\
    0 & 0 & -1 &\bigm| & 1 \\
\end{bmatrix}$$
  * 각 행에 적절한 값을 곱해서 항등 행렬 만들기 (첫번째 행에 $\frac{1}{2}$, 두번째 행에 2, 세번째 행에 -1)
    $$\begin{bmatrix}
    1 & 0 & 0 &\bigm| & 2 \\
    0 & 1 & 0 &\bigm| & 3 \\
    0 & 0 & 1 &\bigm| & -1 \\
\end{bmatrix}$$

## 역행렬(Inverse Matrix)를 가우스-조던 소거법으로 구하기

{{< video https://youtu.be/L9gOujaGv4Q >}}

* $2 \times 2$의 역행렬 구하는 공식을 가우스-조던 소거법으로 구해보자!
  $$\begin{bmatrix} a & b \\ c & d \end{bmatrix}^{-1} = \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$
* Chap02 reminder: 두 연립2차방정식은 행렬의 곱으로 나타낼 수 있음 [참고](../chap02/chap02.qmd#sec-matmul)
  * $A A^{-1} = I$를 같은 식으로 나타내서 역행렬 $A^{-1}$을 구해볼 수 있음
    $$\begin{bmatrix} a & b \\ c & c \end{bmatrix} \begin{bmatrix} x_1 & x_2 \\ y_1 & y_2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$
  * 아래와 같은 두 개의 확장행렬(증강 행렬?)로 나타낼 수 있으나, 결국 같은 부분($a,b,c,d$)를 푸는 것이므로 둘을 합쳐서 풀 수 있음
    * $\begin{bmatrix}
    a & b &\bigm| & 1 \\
    c & d &\bigm| & 0 
\end{bmatrix}$ , $\begin{bmatrix}
    a & b &\bigm| & 0 \\
    c & d &\bigm| & 1 
\end{bmatrix}$ $\Rightarrow$ $\begin{bmatrix}
    a & b &\bigm| & 1 & 0\\
    c & d &\bigm| & 0 & 1
\end{bmatrix}$
    * 첫 행에 $\frac{c}{a}$를 곱해서 아래 행을 뺌
      $$\begin{bmatrix}
    a & b &\bigm| & 1 & 0\\
    0 & d-\frac{bc}{a}=\frac{ad-bc}{a} &\bigm| & -\frac{c}{a} & 1
\end{bmatrix}$$
    * 두번째 행에 \frac{a}{ad-bc}를 곱함
      $$\begin{bmatrix}
    a & b &\bigm| & 1 & 0\\
    0 & 1 &\bigm| & \frac{-c}{ad-bc} & \frac{a}{ad-bc}
\end{bmatrix}$$
    * 두번째 행에 $b$를 곱해서 첫번째 행에서 뺌
      $$\begin{bmatrix}
    a & 0 &\bigm| & 1+\frac{bc}{ad-bc}=\frac{ad}{ad-bc} & \frac{-ab}{ad-bc}\\
    0 & 1 &\bigm| & \frac{-c}{ad-bc} & \frac{a}{ad-bc}
\end{bmatrix}$$
    * 첫번재 행을 $a$로 나눠줌
      $$\begin{bmatrix}
    1 & 0 &\bigm| & \frac{d}{ad-bc} & \frac{-b}{ad-bc}\\
    0 & 1 &\bigm| & \frac{-c}{ad-bc} & \frac{a}{ad-bc}
\end{bmatrix}$$
    * $A^{-1} = \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$
* $ad-bc$가 0이면??
  * 행렬이 invertible하지 않음 ([역행렬이 존재하지 않음](../chap02/chap02.qmd#sec-inv))
    * $ad-bc$: determinant, $det(A)$
* 역행렬의 특징들
  * 정사각행렬 $A$가 invertible하다(=nonsingular matrix) $\leftrightarrow$
    * $det(A) \neq 0$
    * $rank(A_{n \times n}) = n$ ($A$가 full rank)
      * $det(A) = 0 \leftrightarrow$ $A$가 rank-deficient
    * $N(A)$ 에 영벡터($\mathbf{0}$)만 존재
  * $(AB)^{-1} = B^{-1}A^{-1}$
    * $ABB^{-1}A^{-1} = AIA^{-1} = I$
  * $(A^{-1})^{-1} = A$
  * $k$가 scalar 일때, $(kA)^{-1} = \frac{1}{k}A^{-1}$
  * $(A^{T})^{-1} = (A^{-1})^{T}$
  * $det(A^{-1}) = \frac{1}{det(A)}$