---
title: Momment Generating Function
subtitle: Moment
description: | 
 
categories:
  - Statistics
author: Kwangmin Kim
date: 03/01/2023
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}


## Momment Generating Function

::: {#def-moment}

확률 변수 $X^r$ 의 expectation, $\text{E}((X-\mu)^r)$ 를 확률 변수 $X$ 의 평균 $\mu$ 에 대한 $r$ 차 중심 적률(moment) 이라하고 그 notation은 $\mu_r'=\text{E}((X-\mu)^r)$ 로 한다.
$\mu_r'=\text{E}(X^r)$ 은 원점에 대한 $r$ 차 중심 적률이라 한다.

즉,

$$
\begin{aligned}
  \mu_{r}'&= 
    \begin{cases}
      \text{E}((X-\mu)^r)&=
        \begin{cases}
          \sum_{x}(x-\mu)^rf(x), & \text{if }x \text{ is discrete}\\
          \int_{-\infty}^{\infty}(x-\mu)^rf(x)dx, & \text{if }x \text{ is continuous}\\
        \end{cases} & \text{moment about }\mu\\
      \text{E}(X^r)&=
        \begin{cases}
          \sum_{x}x^rf(x), & \text{if }x \text{ is discrete}\\
          \int_{-\infty}^{\infty}x^rf(x)dx, & \text{if }x \text{ is continuous}\\
        \end{cases} & \text{moment about origin}\\\\
    \end{cases}  
\end{aligned}
$$ 

이다. 

:::



분포의 특징을 묘사하는 parameters 중 많은 종류가 확률 변수의 적률을 이용해 계산될 수 있다. 그 대표적인 예가

* 평균 (mean): 분포의 위치를 나타내는 척도, 1차 중심 적률로 계산
* 분산 (variance): 분포가 평균으로부터 퍼진 정도를 나타내는 척도, 2차 중심 적률로 계산
* 왜도 (skewedness): 분포가 기울어진 방향과 정도를 나타내는 척도, 3차 중심 적률로 계산
* 첨도 (kurtosis): 분포가 위로 뾰족한 정도를 나타내는 척도, 4차 중심 적률로 계산


::: {#def-mgf}

확률 변수 $X$ 의 적률 생성 함수 (Moment Generating Function, mgf), $\text{M}_X(t) =\text{E}(e^{tX})$ 로 정의한다.

즉,

$$
\begin{aligned}
  M_X(t)=\text{E}(e^{tX})&=
        \begin{cases}
          \sum_{x}e^{tx}f(x), & \text{if }x \text{ is discrete}\\
          \int_{-\infty}^{\infty}e^{tx}f(x)dx, & \text{if }x \text{ is continuous}\\
        \end{cases} 
\end{aligned}
$$ 

이다. 

:::


::: {#thm-mgf}

확률 변수 $X$ 의 적률 생성 함수 (Moment Generating Function, mgf), $\text{M}_X(t) =\text{E}(e^{tX})$ 로 r차 적률 계산은 다음과 같이 할 수 있다.

$$
\begin{aligned}
  \frac{d^r}{dt^r}M_X(t) \bigg|_{t=0}=M_X^r(0)=\text{E}(X^r)=\mu_r'
\end{aligned}
$$ 

이다. 즉, 적률 생성 함수 (mgf) $M_X(t)$ 를 구하고 r 번 미번한 후에 $t=0$ 대입하면 r차 중심 적률을 구할 수 있다.

:::

proof (for the only continuous case) 

$$
\begin{aligned}
  \text{First Order Moment}\\
  \frac{d}{dt}M_X(t)&= \frac{d}{dt}\text{E}(e^{tX})\\
    &=  \frac{d}{dt}\int_{-\infty}^{\infty}e^{tx}f(x)dx\\
    &=  \int_{-\infty}^{\infty}\frac{d}{dt}e^{tx}f(x)dx\\
    &=  \int_{-\infty}^{\infty}xe^{tx}f(x)dx\bigg|_{t=0}\\
    &=  \int_{-\infty}^{\infty}xf(x)dx\\
    &=  \text{E}(X)\\
    &=  \mu_1'\\
  \text{Second Order Moment}\\
  \frac{d^2}{dt^2}M_X(t)&= \frac{d^2}{dt^2}\text{E}(e^{tX})\\
    &=  \frac{d^2}{dt^2}\int_{-\infty}^{\infty}e^{tx}f(x)dx\\
    &=  \int_{-\infty}^{\infty}\frac{d}{dt}xe^{tx}f(x)dx\\
    &=  \int_{-\infty}^{\infty}x^2e^{tx}f(x)dx\bigg|_{t=0}\\
    &=  \int_{-\infty}^{\infty}x^2f(x)dx\\
    &=  \text{E}(X^2)\\
    &=  \mu_2'\\
  \vdots\\
  \text{r th Order Moment}\\
  \frac{d^r}{dt^r}M_X(t)&= \frac{d^r}{dt^r}\text{E}(e^{tX})\\
    &=  \frac{d^r}{dt^r}\int_{-\infty}^{\infty}e^{tx}f(x)dx\\
    &=  \int_{-\infty}^{\infty}x^re^{tx}f(x)dx\bigg|_{t=0}\\
    &=  \int_{-\infty}^{\infty}x^rf(x)dx\\
    &=  \text{E}(X^r)\\
    &=  \mu_r'
\end{aligned}
$$



### Example

#### Discrete Random Variables

* MGF of $X\sim B(n,p)$

확률 변수 $X \sim B(n,p)$ $X$ 의 mgf, $M_X(t)$, $\text{E}(X)$ 및 $\text{Var}(X)$ 는 다음과 같다.

$$
\begin{aligned}
  f(x)&=\binom{n}{x}p^xq^{n-x}\\
  \sum_{x=0}^{n}f(x)&=\sum_{x=0}^{n}\binom{n}{x}p^xq^{n-x}=(p+q)^n\\
  M_X(t)&=\sum_{x=0}^{n}e^{tx}f(x)=\sum_{x=0}^{n}e^{tx}\binom{n}{x}p^xq^{n-x}\\
        &=\sum_{x=0}^{n}\binom{n}{x}(pe^t)^xq^{n-x}=(pe^t+q)^n\\
  \text{E}(X)&=\mu_1'=\frac{d}{dt}M_X(t)\bigg|_{t=0}\\
  \frac{d}{dt}M_X(t)\bigg|_{t=0}&=\frac{d}{dt}(pe^t+q)^n\\
    &=n(pe^t+q)^{n-1}pe^t\bigg|_{t=0}\\
    &=n(p+q)^{n-1}p=np\\
  \text{E}(X^2)&=\mu_2'=\frac{d^2}{dt^2}M_X(t)\bigg|_{t=0}\\
    &=\mu_2'=(\mu_1')'=\frac{d}{dt}\mu_1'\bigg|_{t=0}\\
    &=\frac{d}{dt}(n(pe^t+q)^{n-1}pe^t)\bigg|_{t=0}\\
    &=(n(n-1)(pe^t+q)^{n-2}pe^tpe^t+n(pe^t+q)^{n-1}pe^t)\bigg|_{t=0}\\
    &=n(n-1)(p+q)^{n-2}p^2+n(p+q)^{n-1}p\\
    &=n(n-1)p^2+np\\
  \text{Var}(X)&=\text{E}(X^2)-(\text{E}(X))^2\\
    &=n(n-1)p^2+np-(np)^2\\
    &=n^2p^2-np^2+np-n^2p^2\\
    &=np(1-p)=npq
\end{aligned}
$$


* MGF of $X\sim Poisson(\lambda)$

확률 변수 $X \sim Poisson(\lambda)$ $X$ 의 mgf, $M_X(t)$, $\text{E}(X)$ 및 $\text{Var}(X)$ 는 다음과 같다.

$$
\begin{aligned}
  f(x)&=\frac{e^{-\lambda}\lambda^{x}}{x!}\\
  M_X(t)&=\sum_{x=0}^{\infty}e^{tx}f(x)=\sum_{x=0}^{\infty}e^{tx}\frac{e^{-\lambda}\lambda^{x}}{x!}\\
        &=e^{-\lambda}\sum_{x=0}^{\infty}\frac{{e^{t}\lambda^{x}}^x}{x!}\\
        &=e^{-\lambda}e^{\lambda e^t} \because \text{(Maclaurin's Series)}\\
        &=e^{\lambda(e^t-1)} \\
        (&\text{Maclaurin's Series: } \sum_{n=0}^{\infty}\frac{x^n}{n!}=1+x+\frac{x^2}{2!}+\frac{x^3}{3!}+ ... =e^x)\\     
  \text{E}(X)&=\mu_1'=\frac{d}{dt}M_X(t)\bigg|_{t=0}\\
  \frac{d}{dt}M_X(t)\bigg|_{t=0}&=\frac{d}{dt}e^{\lambda(e^t-1)}\bigg|_{t=0}\\
    &=\lambda e^{e^t}e^{\lambda(e^t-1)}\bigg|_{t=0}=\lambda\\
  
  \text{E}(X^2)&=\mu_2'=\frac{d^2}{dt^2}M_X(t)\bigg|_{t=0}\\
    &=\mu_2'=(\mu_1')'=\frac{d}{dt}\mu_1'\bigg|_{t=0}\\
    &=\frac{d}{dt}\lambda e^{e^t}e^{\lambda(e^t-1)}\bigg|_{t=0}\\
    &=\lambda e^te^{\lambda (e^t-1)}+\lambda e^t\lambda e^te^{\lambda(e^t-1)}\bigg|_{t=0}\\
    &=\lambda + \lambda^2\\

  \text{Var}(X)&=\text{E}(X^2)-(\text{E}(X))^2\\
    &=\lambda + \lambda^2 -\lambda^2\\
    &=\lambda
\end{aligned}
$$

#### Continuous Random Variables

* MGF of $X\sim N(0,1)$

확률 변수 $X \sim N(0,1)$ $X$ 의 mgf, $M_X(t)$, $\text{E}(X)$ 및 $\text{Var}(X)$ 는 다음과 같다.

$$
\begin{aligned}
  f(x)&=\frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}}(-\infty < x < \infty)\\
  M_X(t)&=\int_{-\infty}^{\infty}e^{tx}f(x)dx=\int_{-\infty}^{\infty}e^{tx}\frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}}dx\\
        &=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-\frac{x^2}{2}+tx}dx\\
        &=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-\frac{1}{2}(x-t)^2+\frac{1}{2}t^2}dx\\
        &=e^{\frac{t^2}{2}}\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-\frac{1}{2}(x-t)^2}dx\\
        &=e^{\frac{t^2}{2}}\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-\frac{1}{2}u^2}du \text{  }(\because x-t=u \rightarrow dx=du)\\
        &=e^{\frac{t^2}{2}} \\     
  \text{E}(X)&=\mu_1'=\frac{d}{dt}M_X(t)\bigg|_{t=0}\\
  \frac{d}{dt}M_X(t)\bigg|_{t=0}&=\frac{d}{dt}e^{\frac{t^2}{2}}\bigg|_{t=0}\\
    &=te^{\frac{t^2}{2}}\bigg|_{t=0}\\
    &=0\\
  
  \text{E}(X^2)&=\mu_2'=\frac{d^2}{dt^2}M_X(t)\bigg|_{t=0}\\
    &=\mu_2'=(\mu_1')'=\frac{d}{dt}\mu_1'\bigg|_{t=0}\\
    &=\frac{d}{dt}te^{\frac{t^2}{2}}\bigg|_{t=0}\\
    &=e^{\frac{t^2}{2}}+t(te^{\frac{t^2}{2}})\bigg|_{t=0}\\
    &=1\\

  \text{Var}(X)&=\text{E}(X^2)-(\text{E}(X))^2\\
    &=1
    
\end{aligned}
$$

* MGF of $X\sim N(\mu,\sigma^2)$

확률 변수 $X\sim N(\mu,\sigma^2)$ $X$ 의 mgf, $M_X(t)$, $\text{E}(X)$ 및 $\text{Var}(X)$ 는 다음과 같다.

$$
\begin{aligned}
  f(x)&=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}(-\infty < x < \infty)\\
  M_X(t)&=\int_{-\infty}^{\infty}e^{tx}f(x)dx\\
        &=\frac{1}{\sqrt{2\pi\sigma^2}}\int_{-\infty}^{\infty}e^{-\frac{(x-\mu)^2}{2\sigma^2}+tx}dx\\
        &=e^{\frac{t^2\sigma^2}{2}+t\mu}\int_{-\infty}^{\infty}\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{1}{2}(\frac{(x-(t\sigma^2+\mu))}{\sigma})^2}dx\\
        &=e^{\frac{t^2\sigma^2}{2}+t\mu}\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{\frac{u^2}{2}}du\\
        (&\because \frac{x-(t\sigma^2+\mu)}{\sigma}=u \rightarrow \frac{dx}{\sigma}=du) \\
        &=e^{\frac{t^2\sigma^2}{2}+t\mu}\frac{1}{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-\frac{u^2}{2}}du\\
        &=e^{\frac{t^2\sigma^2}{2}+t\mu}\\
  
  \text{E}(X)&=\mu_1'=\frac{d}{dt}M_X(t)\bigg|_{t=0}\\
  \frac{d}{dt}M_X(t)\bigg|_{t=0}&=\frac{d}{dt}e^{\frac{t^2\sigma^2}{2}+t\mu}\bigg|_{t=0}\\
    &=e^{\frac{t^2\sigma^2}{2}+t\mu}(\sigma^2t+\mu)\bigg|_{t=0}\\
    &=\mu\\
  \text{E}(X^2)&=\mu_2'=\frac{d^2}{dt^2}M_X(t)\bigg|_{t=0}\\
    &=\mu_2'=(\mu_1')'=\frac{d}{dt}\mu_1'\bigg|_{t=0}\\
    &=\frac{d}{dt}e^{\frac{t^2\sigma^2}{2}+t\mu}(\sigma^2t+\mu)\bigg|_{t=0}\\
    &=\sigma^2+\mu^2 \\
  \text{Var}(X)&=\text{E}(X^2)-(\text{E}(X))^2\\
    &=\sigma^2
\end{aligned}
$$

  
  


  

:::


::: {#thm-identical_distribution}

확률 변수 $X$ 와 $Y$ 가 유한한 같은 적률 생성 함수를 가지면 두 확률 변수는 같은 확률 분포를 갖는다. 
(단, $t\in[-c,c]$ where $c$ is a positive constant)
$$
\text{M}_X(t) =\text{M}_Y(t) \rightarrow F_X(a)=F_Y(a) \text{ for } a \in \mathbb{R} 
$$
다시 말해서, 확률 변수의 분포의 특징이 적률 생성 함수에 의하여 유일하게 결정된다.

:::

[Proof Reference-Washington University](https://courses.cs.washington.edu/courses/cse312/22wi/files/student_drive/5.6.pdf)

[MGF reference](https://www.probabilitycourse.com/chapter6/6_1_3_moment_functions.php)


::: {#thm-linearity_mgf}

$$
\text{M}_{X+a}(t) =e^{at}\text{M}_X(t)
$$
:::

Proof) $\text{E}(e^{t(x+a)})=\text{E}(e^{at}e^{tx})=e^{at}\text{E}(e^{tx})=e^{at}\text{M}_X(t)$

::: {#thm-transform_mgf}

$$
\text{M}_{aX}(t) =\text{M}_X(at)
$$
:::

Proof) $\text{E}(e^{atx})=\text{E}(e^{at(x)})=\text{M}_X(at)$


* Example) when $X \sim N(0,1)$, the mgf of $Y=aX+b$ is ?

$$
\begin{aligned}
  \text{M}_Y(t)&=\text{M}_{aX+b}(t)\\
               &=e^{bt}\text{M}_{X}(at)\\
               &=e^{bt}e^{\frac{a^2t^2}{2}}\\
               &=e^{bt+\frac{a^2t^2}{2}}
\end{aligned}
$$



::: {#thm-independent_mgf}

서로 독립인 확률 변수 $X_1,X_2, ..., X_n$ 의 적률 생성 함수가 각 각  $\text{M}_{X_1}(t), \text{M}_{X_2}(t), ..., \text{M}_{X_n}(t)$ 일 때,
확률 변수 $Y=X_1+X_2+...+X_n$ 의 적률 생성함수 $\text{M}_Y(t)$ 는 $\text{M}_{X_1}(t)\text{M}_{X_2}(t) \dots \text{M}_{X_n}(t)$ 이다.

$$
\begin{aligned}
  \text{M}_Y(t) &= E(e^{Yt})\\
                &= E(e^{t(X_1+X_2+ ...+ X_n)})\\
                &= E(e^{tX_1}e^{tX_2}\dots e^{tX_n})\\
                &= E(e^{tX_1})E(e^{tX_2})\dots E(e^{tX_n}) \because X_i \text{ are independent}\\
                &= \text{M}_{X_1}(t)\text{M}_{X_2}(t) \dots \text{M}_{X_n}(t)
\end{aligned}
$$
:::

* Example)  $X_1, X_2, ..., X_n$ 가 서로 독립이고 parameter 가 각 각 $\lambda_1, \lambda_2, ..., \lambda_n$ 인 poisson 분포를 따른다면 $Y=X_1+X_2+...+X_n$ 의 mgf는

$$
\begin{aligned}
  \text{M}_X(t) &= e^{\lambda(e^t-1)}\\
  \text{M}_Y(t) &= E(e^{Yt})\\
                &= E(e^{t(X_1+X_2+ ...+ X_n)})\\
                &= E(e^{tX_1}e^{tX_2}\dots e^{tX_n})\\
                &= E(e^{tX_1})E(e^{tX_2})\dots E(e^{tX_n}) \because X_i \text{ are independent}\\
                &= \text{M}_{X_1}(t)\text{M}_{X_2}(t) \dots \text{M}_{X_n}(t)\\
                &= e^{\lambda_1(e^t-1)}+e^{\lambda_2(e^t-1)}+\dots+e^{\lambda_n(e^t-1)}\\
                &= e^{(\lambda_1+\lambda_2+\dots+\lambda_n)(e^t-1)}\\
                &= e^{\sum_{i=1}^{n}\lambda_i(e^t-1)}\\
\end{aligned}

$$

이다. 즉, Y는 parameter가 $\sum_{i=1}^{n}\lambda_i$ 인 poisson 분포를 따른다. 뿐만 아니라, 정규 분포, poisson 분포, 카이제곱 분포의 경우 독립 변수들의 합으로 만든 분포도 같은 종류의 분포를 따르게 된다.

</div>


## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)



