<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="dcterms.date" content="2023-01-07">
<meta name="description" content="When we conduct a comparison testing of multiple groups such as A, B, and C on each with numeric data, the statistical test for a significant difference among the groups is called analysis of variance, or ANOVA.">

<title>Kwangmin Kim - ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/CV/index.html">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/projects/index.html">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
 <span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"><i class="bi bi-github" role="img" aria-label="Github">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"><i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ANOVA</h1>
<p class="subtitle lead">ANOVA, one-way ANOVA, Two-way ANOVA, ANCOVA, repeated measures ANOVA, MANOVA, MANCOVA</p>
  <div class="quarto-categories">
    <div class="quarto-category">Statistics</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>When we conduct a comparison testing of multiple groups such as A, B, and C on each with numeric data, the statistical test for a significant difference among the groups is called analysis of variance, or ANOVA.</p>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kwangmin Kim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 7, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>(<strong>draft</strong>)</p>
<p>## CF</p>
<ul>
<li>1111-11-11, <a href="../../../../../docs/blog/posts/statistics/2023-01-07-anova/index.html">ANCOVA</a></li>
<li>1111-11-11, <a href="../../../../../docs/blog/posts/statistics/2023-01-07-anova/index.html">repeated measures ANOVA</a></li>
<li>1111-11-11, <a href="../../../../../docs/blog/posts/statistics/2023-01-07-anova/index.html">MANOVA</a></li>
<li>1111-11-11, <a href="../../../../../docs/blog/posts/statistics/2023-01-07-anova/index.html">MANCOVA</a></li>
</ul>
<ul class="nav nav-pills" id="language-tab" role="tablist">
<li class="nav-item" role="presentation">
<button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">
<p>Korean</p>
</button>
</li>
<li class="nav-item" role="presentation">
<button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">
<p>English</p>
</button>
</li>
<div class="tab-content" id="language-tabcontent">

<div id="Korean" class="tab-pane fade show active" role="tabpanel" aria-labelledby="Korean-tab">
<section id="terms" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="terms"><span class="header-section-number">1</span> Terms</h2>
<ul>
<li>pairwise comparison: A hypothesis test (e.g., of means) between two groups among multiple groups.</li>
<li>obmnibus set: A single hypothesis test of the overall variance among multiple group means.</li>
<li>decomposition of variance : Separation of components contributing to an individual value (e.g., from the overall average, from a treatment mean, and from a residual error).</li>
<li>F-test</li>
<li>F statistic: A standardized statistic that measures the extent to which differences among group means exceed what might be expected in a chance model.</li>
<li>sum of squares: deviations from some average value</li>
</ul>
<section id="description" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="description"><span class="header-section-number">1.1</span> Description</h3>
<p>ANOVA는 <strong>3개 이상의 모집단</strong> 사이의 <strong>평균</strong>의 동일성을 검정하는 통계 분석 방법이다.</p>
<ul>
<li>일원 분산 분석 (One-way ANOVA)
<ul>
<li>그룹을 구분하는 변수가 1개</li>
<li>Between-Groups one-way ANOVA(집단간 일원분산분석): 관측치를 grouping하는 범주형 변수가 <strong>1개</strong>이며 각 관측치는 범주형 변수에 의해 구분되는 그룹들 가운데 반드시 하나에만 할당되어야한다. 즉, 어떠한 경우에도 하나의 관측치 또는 샘플이 여러 groups에 동시에 들어가면 안된다. 이 때 이렇게 그룹을 나누는 범주형 변수를 집단간 요인이라고 한다.</li>
<li>Within-groups one-way ANOVA (집단 내 일원분산분석) or repeated measures ANOVA: 시간과 같은 하나의 범주형 변수로 샘플들을 측정한다. 시간의 경과에 따라 측정된 샘플들을 범주형 변수의 여러 기간에 걸쳐 모두 할당시킨다. 즉, 하나의 샘플이 여러 그룹에 다른 측정치로 관찰될 수 있다. 예를들어, sample A가 4주, 8주, 12주, 16주 그룹에 모두 측정 된다. 이때 기간변수는 집단 내 요인이라고 부른다.</li>
</ul></li>
<li>이원 분산 분석 (Two-way ANOVA)
<ul>
<li>집단을 구분하는 변수가 2개이며 각 집단 간 요인과 집단 내 요인을 나타낸다.</li>
<li>이원 분석 부터는 main effect와 interaction effect가 존재한다.</li>
<li>범주형 변수 A와 범주형 변수 B의 Main effect 계산</li>
<li>범주형 변수 A와 범주형 변수 B의 상호 작용 효과 or 교호 작용 효과 (Interaction effect) 계산</li>
<li>group을 구분하는 독립변수가 2개 일때 모집단 간 평균의 동일성 검정<br>
</li>
<li>2개의 주효과(main effect) 검정: 각 독립 변수에 의해 만들어지는 집단 간 평균의 차이에 대한 검정
<ul>
<li>먼저, 두 독립변수가 종속변수에 개별적으로 영향을 미치는지 검정<br>
</li>
</ul></li>
<li>1개의 상호작용효과(interaction effect) 검정: 두 독립 변수의 조합에 의해 만들어지는 집단 간 평균의 차이에 대한 검정
<ul>
<li>두 독립변수의 조합이 종속변수와 유의한 영향관계를 갖는지 검정<br>
</li>
<li>만약에 유의하다면 2개의 독립변수가 합쳐져서 나온 파생효과이기 때문에 1개만 골라서 분석해서 해석 할 수 없음</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="how-to-conduct-anova" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="how-to-conduct-anova"><span class="header-section-number">1.2</span> How to conduct ANOVA?</h3>
<ul>
<li>분산 분석은 F검정(F test)을 통해 수행한다.</li>
<li>F 검정은 <strong>집단 간 분산</strong> (between-groups variability)과 <strong>집단 내 분산</strong> (within-groups variability)의 <strong>ratio</strong>로 계산된 F값 (F value or F statistic)을 토대로 가설검정을 수행한다. 이때 F value or F statistic을 통계 검정을 위한 검정통계량 (test statistic) 라고 부른다.</li>
<li>F 검정 결과가 통계적으로 유의하면 집단 간 평균의 차이가 존재한다. (즉, 독립 변수가 종속변수에 영향을 미침)</li>
<li>F 분포 2개의 자유도에 의해 분포의 모양이 결정되며 대체로 오른쪽으로 긴 꼬리를 갖는다
<ul>
<li>첫 번째 자유도: 집단 간(between-group)의 자유도</li>
<li>두 번째 자유도: 집단 내(within-group)의 자유도</li>
</ul></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gplots)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">FALSE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">5</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20230109</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>종속 변수의 변동성은 다음과 같이 설명되기 때문에 아래의 식을 만족한다.</p>
<p><span class="math display">\[SS_{total}=SS_A+SS_B+SS_{AB}+SS_{error}\]</span></p>
<p><span class="math inline">\(SS_{total}\)</span>은 쉽게 구할 수 있고 <span class="math inline">\(SS_A\)</span>, <span class="math inline">\(SS_B\)</span>, <span class="math inline">\(SS_{error}\)</span>를 계산하여 빼준다.</p>
<p><a href="http://atomic.phys.uni-sofia.bg/local/nist-e-handbook/e-handbook/prc/section4/prc437.htm">Two Way Anova SS 계산 공식 링크</a></p>
<p><span class="math inline">\(SS_{AB}\)</span> 즉,</p>
<p><span class="math display">\[ SS_{AB}=SS_{total}-SS_A-SS_B-SS_{error} \]</span></p>
</section>
<section id="meaning" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="meaning"><span class="header-section-number">1.3</span> Meaning</h3>
<p>ANOVA는 집단 간 분산과 집단 내 분산의 비교하는 방식으로, 좀 더 구체적으로는 집단 간 분산과 집단 내 분산의 비를 계산하여, 집단 간 분산이 클수록 그리고 집단 분산이 작을 수록 집단 평균이 다를 가능성이 증가한다는 알고리즘에 기초한다.</p>
</section>
</section>
<section id="application-to-example" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="application-to-example"><span class="header-section-number">2</span> Application to Example</h2>
<section id="data-description" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="data-description"><span class="header-section-number">2.1</span> Data Description</h3>
<section id="raw-data" class="level4" data-number="2.1.1">
<h4 data-number="2.1.1" class="anchored" data-anchor-id="raw-data"><span class="header-section-number">2.1.1</span> Raw Data</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     sample Day Run    Ct
1   patient   1   1 38.33
2   patient   1   1 36.58
3   patient   1   1 36.67
4   patient   1   2 38.41
5   patient   1   2 37.86
6   patient   1   2 38.51
7   patient   2   1 36.51
8   patient   2   1 37.38
9   patient   2   1 38.26
10  patient   2   2 37.31
11  patient   2   2 38.13
12  patient   2   2 37.04
13  patient   3   1 37.88
14  patient   3   1 37.41
15  patient   3   1 35.89
16  patient   3   2 36.95
17  patient   3   2 37.23
18  patient   3   2 39.85
19  patient   4   1 36.34
20  patient   4   1 37.67
21  patient   4   1 37.67
22  patient   4   2 36.88
23  patient   4   2 36.53
24  patient   4   2 37.24
25  patient   5   1 37.82
26  patient   5   1 37.56
27  patient   5   1 37.39
28  patient   5   2 37.01
29  patient   5   2 37.60
30  patient   5   2 38.04
31  patient   6   1 36.50
32  patient   6   1 38.72
33  patient   6   1 37.74
34  patient   6   2 37.78
35  patient   6   2 36.98
36  patient   6   2 36.72
37  patient   7   1 37.12
38  patient   7   1 37.02
39  patient   7   1 38.07
40  patient   7   2 38.68
41  patient   7   2 37.75
42  patient   7   2 35.91
43  patient   8   1 39.70
44  patient   8   1 37.22
45  patient   8   1 36.79
46  patient   8   2 37.22
47  patient   8   2 37.66
48  patient   8   2 36.54
49  patient   9   1 38.39
50  patient   9   1 38.88
51  patient   9   1 39.10
52  patient   9   2 38.99
53  patient   9   2 37.26
54  patient   9   2 36.15
55  patient  10   1 36.94
56  patient  10   1 36.65
57  patient  10   1 36.67
58  patient  10   2 37.63
59  patient  10   2 37.09
60  patient  10   2 37.80
61  patient  11   1 38.31
62  patient  11   1 40.20
63  patient  11   1 37.57
64  patient  11   2 37.04
65  patient  11   2 36.46
66  patient  11   2 37.30
67  patient  12   1 36.65
68  patient  12   1 36.49
69  patient  12   1 37.03
70  patient  12   2 37.44
71  patient  12   2 36.77
72  patient  12   2 36.23
73  patient  13   1 37.95
74  patient  13   1 36.60
75  patient  13   1 37.68
76  patient  13   2 37.82
77  patient  13   2 38.00
78  patient  13   2 37.33
79  patient  14   1 36.63
80  patient  14   1 36.37
81  patient  14   1 37.15
82  patient  14   2 38.11
83  patient  14   2 37.28
84  patient  14   2 35.60
85  patient  15   1 36.29
86  patient  15   1 36.21
87  patient  15   1 36.61
88  patient  15   2 37.62
89  patient  15   2 38.82
90  patient  15   2 35.55
91  patient  16   1 36.27
92  patient  16   1 37.51
93  patient  16   1 37.93
94  patient  16   2 36.79
95  patient  16   2 36.64
96  patient  16   2 36.76
97  patient  17   1 36.86
98  patient  17   1 37.40
99  patient  17   1 38.11
100 patient  17   2 36.09
101 patient  17   2 36.23
102 patient  17   2 36.80
103 patient  18   1 37.61
104 patient  18   1 37.27
105 patient  18   1 37.05
106 patient  18   2 38.17
107 patient  18   2 36.62
108 patient  18   2 36.24
109 patient  19   1 37.20
110 patient  19   1 37.05
111 patient  19   1 38.73
112 patient  19   2 36.52
113 patient  19   2 36.41
114 patient  19   2 36.40
115 patient  20   1 37.62
116 patient  20   1 37.36
117 patient  20   1    NA
118 patient  20   2 38.41
119 patient  20   2 37.26
120 patient  20   2 37.28</code></pre>
</div>
</div>
<p>공유해주신 example data는 sample, Day, Run, Ct의 변수들을 포함하고 있습니다. 특히 sample은 여기서 같은 값을 갖고있기 때문에 의미가 없는 변수입니다. 공유해주신 정보에 따르면 아마도 Run은 오전과 오후를 나누는 변수인 것으로 생각 됩니다. 이 data만 보면 아마도 같은 샘플에 대해서 시약 제품이 시간에 따라 얼마나 안정적인 performance (Ct값)를 보여주는지 검사하는 실험으로 추측됩니다. 좀 더 분석하기 용이한 형태로 data structure를 바꾸겠습니다.</p>
</section>
<section id="processed-data" class="level4" data-number="2.1.2">
<h4 data-number="2.1.2" class="anchored" data-anchor-id="processed-data"><span class="header-section-number">2.1.2</span> Processed Data</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 120 × 5
      id Day   noon    Run    Ct
   &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;int&gt; &lt;dbl&gt;
 1     1 1     AM        1  38.3
 2     2 1     AM        2  36.6
 3     3 1     AM        3  36.7
 4     4 1     PM        1  38.4
 5     5 1     PM        2  37.9
 6     6 1     PM        3  38.5
 7     7 2     AM        1  36.5
 8     8 2     AM        2  37.4
 9     9 2     AM        3  38.3
10    10 2     PM        1  37.3
# … with 110 more rows</code></pre>
</div>
</div>
<p>재가공된 data는 120개의 샘플과 5개의 변수를 갖고있습니다. 변수 목록은 다음과 같습니다.</p>
<ul>
<li>sample: 검체이름, 같은 검체 혹은 의미없음<br>
</li>
<li>id: 열번호, 총 20일간 하루 2회 구동(AM, PM) 구동, 오전 오후 각 각 3번씩 구동 총 120 <span class="math inline">\((=20 \times 3 \times 2)\)</span> 샘플<br>
</li>
<li>Day: Day1~20<br>
</li>
<li>noon: AM= before noon, PM= after noon</li>
<li>Run: 1회 구동당 3번 반복씩1, 2, 3<br>
</li>
<li>Ct: Ct values</li>
</ul>
<p>ANOVA의 Assumption</p>
<ul>
<li>response variable should follow normal distribution.<br>
</li>
<li>homoscedasticity, equality of variance: 각 집단의 분포는 모두 동일한 분산을 가짐<br>
ANOVA의 가정들을 반드시 충족하지 않아도 되지만 충족하면 Power 가 올라감</li>
</ul>
</section>
</section>
<section id="eda-explorator-data-analysis" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="eda-explorator-data-analysis"><span class="header-section-number">2.2</span> EDA (Explorator Data Analysis)</h3>
<p>이 data는 아래 처럼 1의 결측치를 갖고 있습니다.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">id</th>
<th style="text-align: left;">Day</th>
<th style="text-align: left;">noon</th>
<th style="text-align: right;">Run</th>
<th style="text-align: right;">Ct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">117</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ct에 대한 Global Statistics는 다음과 같습니다.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">count</th>
<th style="text-align: right;">global_Ct_mean</th>
<th style="text-align: right;">global_Ct_sd</th>
<th style="text-align: left;">global_Ct_CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">119</td>
<td style="text-align: right;">37.322</td>
<td style="text-align: right;">0.86754</td>
<td style="text-align: left;">2.324 %</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Day groups의 Statistics은 다음과 같습니다.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Day</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">Day_group_Ct_mean</th>
<th style="text-align: right;">Day_group_Ct_sd</th>
<th style="text-align: left;">Day_group_Ct_CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.727</td>
<td style="text-align: right;">0.88247</td>
<td style="text-align: left;">2.339 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.438</td>
<td style="text-align: right;">0.66240</td>
<td style="text-align: left;">1.769 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.535</td>
<td style="text-align: right;">1.31417</td>
<td style="text-align: left;">3.501 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.055</td>
<td style="text-align: right;">0.56712</td>
<td style="text-align: left;">1.53 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.570</td>
<td style="text-align: right;">0.35508</td>
<td style="text-align: left;">0.945 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.407</td>
<td style="text-align: right;">0.83077</td>
<td style="text-align: left;">2.221 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.425</td>
<td style="text-align: right;">0.96426</td>
<td style="text-align: left;">2.577 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.522</td>
<td style="text-align: right;">1.13537</td>
<td style="text-align: left;">3.026 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">38.128</td>
<td style="text-align: right;">1.18219</td>
<td style="text-align: left;">3.101 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.130</td>
<td style="text-align: right;">0.48551</td>
<td style="text-align: left;">1.308 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.813</td>
<td style="text-align: right;">1.31872</td>
<td style="text-align: left;">3.487 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.768</td>
<td style="text-align: right;">0.42447</td>
<td style="text-align: left;">1.154 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.563</td>
<td style="text-align: right;">0.52955</td>
<td style="text-align: left;">1.41 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.857</td>
<td style="text-align: right;">0.86064</td>
<td style="text-align: left;">2.335 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.850</td>
<td style="text-align: right;">1.17852</td>
<td style="text-align: left;">3.198 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.983</td>
<td style="text-align: right;">0.61442</td>
<td style="text-align: left;">1.661 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.915</td>
<td style="text-align: right;">0.75224</td>
<td style="text-align: left;">2.038 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.160</td>
<td style="text-align: right;">0.69062</td>
<td style="text-align: left;">1.859 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.052</td>
<td style="text-align: right;">0.88971</td>
<td style="text-align: left;">2.401 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">37.586</td>
<td style="text-align: right;">0.48247</td>
<td style="text-align: left;">1.284 %</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>AM/PM groups의 Statistics은 다음과 같습니다.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">noon</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">noon_group_Ct_mean</th>
<th style="text-align: right;">noon_group_Ct_sd</th>
<th style="text-align: left;">noon_group_Ct_CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AM</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">37.400</td>
<td style="text-align: right;">0.87839</td>
<td style="text-align: left;">2.349 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">PM</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">37.246</td>
<td style="text-align: right;">0.85722</td>
<td style="text-align: left;">2.302 %</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Days와 AM/PM 조합 groups의 Statistics은 다음과 같습니다.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 28%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Day</th>
<th style="text-align: left;">noon</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">combi_group_Ct_mean</th>
<th style="text-align: right;">combi_group_Ct_sd</th>
<th style="text-align: left;">combi_group_Ct_CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.193</td>
<td style="text-align: right;">0.98541</td>
<td style="text-align: left;">2.649 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">38.260</td>
<td style="text-align: right;">0.35000</td>
<td style="text-align: left;">0.915 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.383</td>
<td style="text-align: right;">0.87500</td>
<td style="text-align: left;">2.341 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.493</td>
<td style="text-align: right;">0.56766</td>
<td style="text-align: left;">1.514 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.060</td>
<td style="text-align: right;">1.04014</td>
<td style="text-align: left;">2.807 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">38.010</td>
<td style="text-align: right;">1.59962</td>
<td style="text-align: left;">4.208 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.227</td>
<td style="text-align: right;">0.76788</td>
<td style="text-align: left;">2.063 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.883</td>
<td style="text-align: right;">0.35501</td>
<td style="text-align: left;">0.963 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.590</td>
<td style="text-align: right;">0.21656</td>
<td style="text-align: left;">0.576 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.550</td>
<td style="text-align: right;">0.51682</td>
<td style="text-align: left;">1.376 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.653</td>
<td style="text-align: right;">1.11253</td>
<td style="text-align: left;">2.955 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.160</td>
<td style="text-align: right;">0.55245</td>
<td style="text-align: left;">1.487 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.403</td>
<td style="text-align: right;">0.57951</td>
<td style="text-align: left;">1.549 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.447</td>
<td style="text-align: right;">1.40969</td>
<td style="text-align: left;">3.765 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.903</td>
<td style="text-align: right;">1.57074</td>
<td style="text-align: left;">4.144 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.140</td>
<td style="text-align: right;">0.56427</td>
<td style="text-align: left;">1.519 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">38.790</td>
<td style="text-align: right;">0.36346</td>
<td style="text-align: left;">0.937 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.467</td>
<td style="text-align: right;">1.43123</td>
<td style="text-align: left;">3.82 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.753</td>
<td style="text-align: right;">0.16197</td>
<td style="text-align: left;">0.441 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.507</td>
<td style="text-align: right;">0.37072</td>
<td style="text-align: left;">0.988 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">38.693</td>
<td style="text-align: right;">1.35626</td>
<td style="text-align: left;">3.505 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.933</td>
<td style="text-align: right;">0.43004</td>
<td style="text-align: left;">1.164 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.723</td>
<td style="text-align: right;">0.27737</td>
<td style="text-align: left;">0.755 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.813</td>
<td style="text-align: right;">0.60616</td>
<td style="text-align: left;">1.647 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.410</td>
<td style="text-align: right;">0.71435</td>
<td style="text-align: left;">1.91 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.717</td>
<td style="text-align: right;">0.34675</td>
<td style="text-align: left;">0.919 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.717</td>
<td style="text-align: right;">0.39716</td>
<td style="text-align: left;">1.082 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.997</td>
<td style="text-align: right;">1.27876</td>
<td style="text-align: left;">3.456 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.370</td>
<td style="text-align: right;">0.21166</td>
<td style="text-align: left;">0.582 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.330</td>
<td style="text-align: right;">1.65418</td>
<td style="text-align: left;">4.431 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.237</td>
<td style="text-align: right;">0.86310</td>
<td style="text-align: left;">2.318 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.730</td>
<td style="text-align: right;">0.07937</td>
<td style="text-align: left;">0.216 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.457</td>
<td style="text-align: right;">0.62692</td>
<td style="text-align: left;">1.674 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.373</td>
<td style="text-align: right;">0.37608</td>
<td style="text-align: left;">1.034 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">18</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.310</td>
<td style="text-align: right;">0.28213</td>
<td style="text-align: left;">0.756 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.010</td>
<td style="text-align: right;">1.02240</td>
<td style="text-align: left;">2.762 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.660</td>
<td style="text-align: right;">0.92968</td>
<td style="text-align: left;">2.469 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">19</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36.443</td>
<td style="text-align: right;">0.06658</td>
<td style="text-align: left;">0.183 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: left;">AM</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">37.490</td>
<td style="text-align: right;">0.18385</td>
<td style="text-align: left;">0.49 %</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">PM</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">37.650</td>
<td style="text-align: right;">0.65826</td>
<td style="text-align: left;">1.748 %</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>이제 ANOVA를 수행하기 위한 basic statistics는 모두 구했습니다. ANOVA를 수행하기 위해 집단 간 분산과 집단 내 분산을 계산하도록 하겠습니다.</p>
</section>
<section id="집단-간-분산" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="집단-간-분산"><span class="header-section-number">2.3</span> 집단 간 분산</h3>
<p>앞에서 설명 드린바로 유추해보면 예시 data의 집단 간 분산의 범주형 변수는 Day로 설정하는 것이 합리적인 것으로 보입니다.</p>
<ul>
<li><span class="math inline">\(g=g\)</span> Day의 sample size = 20, 자유도 = 20-1 = 19 입니다.</li>
<li><span class="math inline">\(n_g=g\)</span> group의 sample size, <span class="math inline">\(\overline{X}_g=g\)</span> 의 sample mean은 다음과 같습니다.</li>
<li><span class="math inline">\(\overline{X}\)</span> = global sample mean = 37.32202</li>
<li>집단 간 분산: <span class="math inline">\(\frac{집단 간 제곱합}{자유도}=\frac{\sum_g[(\overline{X}_g-\overline{X})^2n_g]}{g-1}\)</span></li>
</ul>
<section id="ss_day-집단간-분산-day" class="level4" data-number="2.3.1">
<h4 data-number="2.3.1" class="anchored" data-anchor-id="ss_day-집단간-분산-day"><span class="header-section-number">2.3.1</span> SS_Day (집단간 분산 Day)</h4>
<p>Day sq = <span class="math inline">\([(\overline{X}_g-\overline{X})^2n_g]\)</span> 집단(Day)간 분산 계산, 집단(Day)간 분산 = <span class="math inline">\(\frac{\sum_g[(\overline{X}_g-\overline{X})^2n_g]}{g-1}\)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 2%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Day</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">Day_group_Ct_mean</th>
<th style="text-align: right;">Day_group_Ct_sd</th>
<th style="text-align: left;">Day_group_Ct_CV</th>
<th style="text-align: right;">day_sq</th>
<th style="text-align: right;">sum_day_ssq</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">day_mean_ssq</th>
<th style="text-align: right;">day_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.727</td>
<td style="text-align: right;">0.88247</td>
<td style="text-align: left;">2.339 %</td>
<td style="text-align: right;">0.98245</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.438</td>
<td style="text-align: right;">0.66240</td>
<td style="text-align: left;">1.769 %</td>
<td style="text-align: right;">0.08118</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.535</td>
<td style="text-align: right;">1.31417</td>
<td style="text-align: left;">3.501 %</td>
<td style="text-align: right;">0.27217</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.055</td>
<td style="text-align: right;">0.56712</td>
<td style="text-align: left;">1.53 %</td>
<td style="text-align: right;">0.42779</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.570</td>
<td style="text-align: right;">0.35508</td>
<td style="text-align: left;">0.945 %</td>
<td style="text-align: right;">0.36897</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.407</td>
<td style="text-align: right;">0.83077</td>
<td style="text-align: left;">2.221 %</td>
<td style="text-align: right;">0.04299</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.425</td>
<td style="text-align: right;">0.96426</td>
<td style="text-align: left;">2.577 %</td>
<td style="text-align: right;">0.06363</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.522</td>
<td style="text-align: right;">1.13537</td>
<td style="text-align: left;">3.026 %</td>
<td style="text-align: right;">0.23916</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">38.128</td>
<td style="text-align: right;">1.18219</td>
<td style="text-align: left;">3.101 %</td>
<td style="text-align: right;">3.90088</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.130</td>
<td style="text-align: right;">0.48551</td>
<td style="text-align: left;">1.308 %</td>
<td style="text-align: right;">0.22122</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.813</td>
<td style="text-align: right;">1.31872</td>
<td style="text-align: left;">3.487 %</td>
<td style="text-align: right;">1.44835</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.768</td>
<td style="text-align: right;">0.42447</td>
<td style="text-align: left;">1.154 %</td>
<td style="text-align: right;">1.83939</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.563</td>
<td style="text-align: right;">0.52955</td>
<td style="text-align: left;">1.41 %</td>
<td style="text-align: right;">0.34940</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.857</td>
<td style="text-align: right;">0.86064</td>
<td style="text-align: left;">2.335 %</td>
<td style="text-align: right;">1.29930</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.850</td>
<td style="text-align: right;">1.17852</td>
<td style="text-align: left;">3.198 %</td>
<td style="text-align: right;">1.33680</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.983</td>
<td style="text-align: right;">0.61442</td>
<td style="text-align: left;">1.661 %</td>
<td style="text-align: right;">0.68824</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">36.915</td>
<td style="text-align: right;">0.75224</td>
<td style="text-align: left;">2.038 %</td>
<td style="text-align: right;">0.99398</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.160</td>
<td style="text-align: right;">0.69062</td>
<td style="text-align: left;">1.859 %</td>
<td style="text-align: right;">0.15750</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">37.052</td>
<td style="text-align: right;">0.88971</td>
<td style="text-align: left;">2.401 %</td>
<td style="text-align: right;">0.43854</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">37.586</td>
<td style="text-align: right;">0.48247</td>
<td style="text-align: left;">1.284 %</td>
<td style="text-align: right;">0.34844</td>
<td style="text-align: right;">15.5</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.81581</td>
<td style="text-align: right;">0.90322</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Analysis-In program의 ANOVA결과값과 일치하는 것을 볼 수 있습니다. $SS_{day} $= 15.50038 with <span class="math inline">\(df=19\)</span>.</p>
</section>
<section id="ss_noon-집단간-분산-noon" class="level4" data-number="2.3.2">
<h4 data-number="2.3.2" class="anchored" data-anchor-id="ss_noon-집단간-분산-noon"><span class="header-section-number">2.3.2</span> SS_noon (집단간 분산 noon)</h4>
<p>noon sq = <span class="math inline">\([(\overline{X}_g-\overline{X})^2n_g]\)</span> 집단(noon)간 분산 계산, 집단(noon)간 분산 = <span class="math inline">\(\frac{\sum_g[(\overline{X}_g-\overline{X})^2n_g]}{g-1}\)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 2%">
<col style="width: 12%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">noon</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">noon_group_Ct_mean</th>
<th style="text-align: right;">noon_group_Ct_sd</th>
<th style="text-align: left;">noon_group_Ct_CV</th>
<th style="text-align: right;">noon_sq</th>
<th style="text-align: right;">sum_noon_ssq</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">noon_mean_ssq</th>
<th style="text-align: right;">noon_sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AM</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">37.400</td>
<td style="text-align: right;">0.87839</td>
<td style="text-align: left;">2.349 %</td>
<td style="text-align: right;">0.35569</td>
<td style="text-align: right;">0.70545</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.70545</td>
<td style="text-align: right;">0.83991</td>
</tr>
<tr class="even">
<td style="text-align: left;">PM</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">37.246</td>
<td style="text-align: right;">0.85722</td>
<td style="text-align: left;">2.302 %</td>
<td style="text-align: right;">0.34976</td>
<td style="text-align: right;">0.70545</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.70545</td>
<td style="text-align: right;">0.83991</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Analysis-In program의 결과에서 찾아 볼 수 없죠? 이 결과는 숨어 있습니다. 상호 작용에 대한 분산값을 구하고 나면 정체를 알 수 있습니다.</p>
<p><span class="math inline">\(SS_{noon}\)</span> = 0.70545 with <span class="math inline">\(df=1\)</span>.</p>
</section>
<section id="ss_error-집단내-분산" class="level4" data-number="2.3.3">
<h4 data-number="2.3.3" class="anchored" data-anchor-id="ss_error-집단내-분산"><span class="header-section-number">2.3.3</span> SS_error (집단내 분산)</h4>
<ul>
<li>집단 내 분산 (within-groups variability)</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 119 × 10
   Day   noon    Run    Ct count combi_group_Ct_…¹ resid…²    df resid…³ mean_…⁴
   &lt;fct&gt; &lt;fct&gt; &lt;int&gt; &lt;dbl&gt; &lt;int&gt;             &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 1     AM        1  38.3     3              37.2 1.29e+0    79    54.5   0.690
 2 1     AM        2  36.6     3              37.2 3.76e-1    79    54.5   0.690
 3 1     AM        3  36.7     3              37.2 2.74e-1    79    54.5   0.690
 4 1     PM        1  38.4     3              38.3 2.25e-2    79    54.5   0.690
 5 1     PM        2  37.9     3              38.3 1.60e-1    79    54.5   0.690
 6 1     PM        3  38.5     3              38.3 6.25e-2    79    54.5   0.690
 7 2     AM        1  36.5     3              37.4 7.63e-1    79    54.5   0.690
 8 2     AM        2  37.4     3              37.4 1.11e-5    79    54.5   0.690
 9 2     AM        3  38.3     3              37.4 7.69e-1    79    54.5   0.690
10 2     PM        1  37.3     3              37.5 3.36e-2    79    54.5   0.690
# … with 109 more rows, and abbreviated variable names ¹​combi_group_Ct_mean,
#   ²​residual_sq, ³​residual_ssq, ⁴​mean_residual_ssq</code></pre>
</div>
</div>
<p><span class="math inline">\(SS_{error}\)</span> = 54.50093</p>
<p>Analysis-In program의 결과와 일치하는 것을 확인할 수 있습니다.</p>
</section>
<section id="ss_total" class="level4" data-number="2.3.4">
<h4 data-number="2.3.4" class="anchored" data-anchor-id="ss_total"><span class="header-section-number">2.3.4</span> SS_total</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 119 × 6
      id Day   noon    Run    Ct total_ssq
   &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;int&gt; &lt;dbl&gt;     &lt;dbl&gt;
 1     1 1     AM        1  38.3      88.8
 2     2 1     AM        2  36.6      88.8
 3     3 1     AM        3  36.7      88.8
 4     4 1     PM        1  38.4      88.8
 5     5 1     PM        2  37.9      88.8
 6     6 1     PM        3  38.5      88.8
 7     7 2     AM        1  36.5      88.8
 8     8 2     AM        2  37.4      88.8
 9     9 2     AM        3  38.3      88.8
10    10 2     PM        1  37.3      88.8
# … with 109 more rows</code></pre>
</div>
</div>
<p><span class="math inline">\(SS_{total}\)</span> = 88.81032</p>
<p>Analysis-In program의 ANOVA 결과 table에 있는 SS들의 합과 일치하는 것을 확인할 수 있습니다.</p>
</section>
<section id="상호-작용-분산" class="level4" data-number="2.3.5">
<h4 data-number="2.3.5" class="anchored" data-anchor-id="상호-작용-분산"><span class="header-section-number">2.3.5</span> 상호 작용 분산</h4>
<div class="cell">

</div>
<p><span class="math inline">\(SS_{interaction}=SS_{DayNoon}= SS_{total}-SS_{Day}-SS_{noon}-SS_{error}\)</span> = 88.81032-54.50093-0.70545-15.50038 = 18.10355</p>
<p>Analysis-In program의 ANOVA 결과 table과 일치하는 것을 확인할 수 있습니다.</p>
<p>위의 결과들을 종합하면 아래와 같이 요약됩니다.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Day         19   15.5   0.816    1.18   0.29
noon         1    0.7   0.748    1.08   0.30
Day:noon    19   18.1   0.951    1.38   0.16
Residuals   79   54.5   0.690               
1 observation deleted due to missingness</code></pre>
</div>
</div>
<ul>
<li>Repeatability SD = <span class="math inline">\(\sqrt{V_{error}}=\sqrt{MS_{error}}\)</span> = 0.83059</li>
<li>Repeatability CV = <span class="math inline">\(\frac{repeatability \space SD}{global \space mean \space Ct}\)</span> = 0.02225</li>
</ul>
<p>(생략, 다른 통계량들은 ANOVA_A repeat2.xlsx 참조)</p>
<p>위의 결과를 간단히 해석해 보면</p>
<ul>
<li>집단간 범주 변수인 Day는 p-value =0.29&gt;0.05 이므로 5% 유의 수준에서, 유의하지 않습니다.
<ul>
<li>즉, 5% 유의 수준에서, 일별로 평균 Ct값이 같다는 가설을 기각하는데 실패했습니다.</li>
<li>다시 말하면, 5% 유의 수준에서, 일별로 평균 Ct값이 다르지 않습니다.</li>
</ul></li>
<li>집단간 범주 변수인 noon은 p-value =0.30&gt;0.05 이므로 5% 유의 수준에서, 유의하지 않습니다.
<ul>
<li>즉, 5% 유의 수준에서, 오전/오후별 평균 Ct값이 같다는 가설을 기각하는데 실패했습니다.</li>
<li>다시 말하면, 5% 유의 수준에서, 오전/오후별 평균 Ct값이 다르지 않습니다.</li>
</ul></li>
<li>Day와 noon두 변수의 상호작용 변수는 p-value =0.16&gt;0.05 이므로 5% 유의 수준에서, 유의하지 않습니다.
<ul>
<li>즉, 5% 유의 수준에서, Day별 Noon(오전/오후)별 평균 Ct값이 같다는 가설을 기각하는데 실패했습니다.</li>
<li>다시 말하면, 5% 유의 수준에서, Day별 Noon(오전/오후)별 평균 Ct값이 다르지 않습니다.</li>
</ul></li>
</ul>
<p>최종 결론, 제품의 Ct값이 Day별 오전/오후별 안정적인 performance를 보인다고 조심스럽게 결론을 내릴 수 있습니다.</p>
<p>이제 까지는 질문에 대한 답이 되는 ANOVA의 원리 및 통계량의 재현 및 해석법에 대하여 알아봤습니다. 하지만 직관적으로 어떤 의미가 있을 까요? 원래는 시각화를 통해 데이터의 패턴을 짐작하고 통계 검정 결과를 예상하는데 우리는 반대로 가고 있네요 ㅎㅎ 시각화를 통해 ANOVA 결과가 얼마나 직관적인지 알아보겠습니다.</p>
</section>
</section>
<section id="visualization" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="visualization"><span class="header-section-number">2.4</span> Visualization</h3>
<section id="one-way-day" class="level4" data-number="2.4.1">
<h4 data-number="2.4.1" class="anchored" data-anchor-id="one-way-day"><span class="header-section-number">2.4.1</span> One-way: Day</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>자세히 보면 일별로 시간의 경과에 따라 전체적으로 평균 Ct값이 약간 하향하는 것으로 보입니다. 하지만 좀 더 세부적으로 관찰하면 1일~8일 평균 Ct의 경향이 constant한 패턴을 보입니다. 9일~13일 평균 Ct가 진동 하향하는 패턴을 보입니다. 14일~20일 평균 Ct가 상향하는 패턴을 보입니다.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Tables of means
Grand mean
       
37.322 

 Day 
        1     2     3     4     5     6     7     8     9    10    11    12
    37.73 37.44 37.53 37.05 37.57 37.41 37.42 37.52 38.13 37.13 37.81 36.77
rep  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00
       13    14    15    16    17    18    19    20
    37.56 36.86 36.85 36.98 36.91 37.16 37.05 37.59
rep  6.00  6.00  6.00  6.00  6.00  6.00  6.00  5.00</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of effects

 Day 
         1      2     3      4     5       6     7      8      9     10     11
    0.4046 0.1163 0.213 -0.267 0.248 0.08465 0.103 0.1996 0.8063 -0.192 0.4913
rep 6.0000 6.0000 6.000  6.000 6.000 6.00000 6.000 6.0000 6.0000  6.000 6.0000
         12     13      14     15      16     17     18      19    20
    -0.5537 0.2413 -0.4654 -0.472 -0.3387 -0.407 -0.162 -0.2704 0.264
rep  6.0000 6.0000  6.0000  6.000  6.0000  6.000  6.000  6.0000 5.000</code></pre>
</div>
</div>
<p>위에 첫 번째표에서 Global Sample Ct Mean = 37.322 과 각 집단의 평균 Ct를 확인할 수 있습니다. 위에 두 번째표에서 Global Sample Ct Mean = 37.322 과 각 집단의 평균 Ct의 차이를 확인할 수 있습니다.</p>
<ul>
<li>Day 9에서 차이가 가장 큰 것으로 보아 9일째 실험에서 performance가 가장 낮은 것이 관측됐습니다.</li>
<li>반대로, 12일에 performance 가장 좋은 것으로 관측됐습니다.</li>
</ul>
<p>9일과 12일에 Ct값에 영향을 미쳤던 요인이 있었는지 복기 하는것도 도움이 되겠군요.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Day         19   15.5   0.816     1.1   0.36
Residuals   99   73.3   0.741               
1 observation deleted due to missingness</code></pre>
</div>
</div>
<p>One-way ANOVA의 결과값입니다. Day별 평균 Ct의 차이는 거의 없는 것으로 보입니다. 따라서 Day 별 평균 Ct의 경향이 일관되지 않고 One-way ANOVA에서 역시 통계적으로 유의하지 않아 Day 변수는 평균 Ct에 영향을 미치지 않는 것 같습니다.</p>
</section>
<section id="one-way-ampm" class="level4" data-number="2.4.2">
<h4 data-number="2.4.2" class="anchored" data-anchor-id="one-way-ampm"><span class="header-section-number">2.4.2</span> One-way: AM/PM</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>오후에 시간의 경과에 따라 전체적으로 평균 Ct값이 약간 하향하는 것으로 보입니다.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Tables of means
Grand mean
       
37.322 

 noon 
      AM    PM
    37.4 37.25
rep 59.0 60.00</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of effects

 noon 
          AM       PM
     0.07764 -0.07635
rep 59.00000 60.00000</code></pre>
</div>
</div>
<p>위 첫 번째 표에서 AM/PM 간의 평균 Ct차이는 0.15 (농도가 약 0.5배) 차이가 나는 것을 확인할 수 있습니다. 생물학적으로 의미가 있는 수치일까요? 위 두 번째 표에서 Global Sample Mean 37.322와 오전/오후 별 약 0.07씩(농도가 약 0.25배) 차이가 납니다.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
noon          1    0.7   0.705    0.94   0.34
Residuals   117   88.1   0.753               
1 observation deleted due to missingness</code></pre>
</div>
</div>
<p>오전 오후별 One way ANOVA를 실행한 결과가 오전/오부 평균 Ct값의 차이가 다르지 않다는 것을 시사하고 있습니다. 아무래도 위의 차이는 우연에 의해 발생한 현상인 것 같습니다.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>일별로 평균 Ct값이 차이를 모든 경우의 수에서 차이가 나는지 확인한 결과 신뢰구간 모두가 0을 포함하고 있으므로 Day 변수는 유의하다고 볼 수 없습니다.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>오전/오후별로 평균 Ct값이 차이를 모든 경우의 수에서 차이가 나는지 확인한 결과 신뢰구간 모두가 0을 포함하고 있으므로 오전/오후 변수는 유의하다고 볼 수 없습니다.</p>
<p>여기 까지 각 변수별 평균 Ct로의 영향도를 통계적으로 시각적으로 관찰했습니다. 하지만 Day별 오전/오후별 영향도가 있는지 확인하겠습니다. (이미 위에서 통계적으로 없다고 검정됐습니다.)</p>
</section>
</section>
<section id="two-way-anova" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="two-way-anova"><span class="header-section-number">2.5</span> Two way Anova</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Tables of means
Grand mean
       
37.322 

 Day 
        1     2     3     4     5     6     7     8     9    10    11    12
    37.73 37.44 37.53 37.05 37.57 37.41 37.42 37.52 38.13 37.13 37.81 36.77
rep  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00  6.00
       13    14    15    16    17    18    19    20
    37.56 36.86 36.85 36.98 36.91 37.16 37.05 37.59
rep  6.00  6.00  6.00  6.00  6.00  6.00  6.00  5.00

 noon 
      AM    PM
    37.4 37.24
rep 59.0 60.00

 Day:noon 
     noon
Day   AM    PM   
  1   37.19 38.26
  rep  3.00  3.00
  2   37.38 37.49
  rep  3.00  3.00
  3   37.06 38.01
  rep  3.00  3.00
  4   37.23 36.88
  rep  3.00  3.00
  5   37.59 37.55
  rep  3.00  3.00
  6   37.65 37.16
  rep  3.00  3.00
  7   37.40 37.45
  rep  3.00  3.00
  8   37.90 37.14
  rep  3.00  3.00
  9   38.79 37.47
  rep  3.00  3.00
  10  36.75 37.51
  rep  3.00  3.00
  11  38.69 36.93
  rep  3.00  3.00
  12  36.72 36.81
  rep  3.00  3.00
  13  37.41 37.72
  rep  3.00  3.00
  14  36.72 37.00
  rep  3.00  3.00
  15  36.37 37.33
  rep  3.00  3.00
  16  37.24 36.73
  rep  3.00  3.00
  17  37.46 36.37
  rep  3.00  3.00
  18  37.31 37.01
  rep  3.00  3.00
  19  37.66 36.44
  rep  3.00  3.00
  20  37.49 37.65
  rep  2.00  3.00</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Tables of effects

 Day 
         1      2     3      4     5       6     7      8      9     10     11
    0.4046 0.1163 0.213 -0.267 0.248 0.08465 0.103 0.1996 0.8063 -0.192 0.4913
rep 6.0000 6.0000 6.000  6.000 6.000 6.00000 6.000 6.0000 6.0000  6.000 6.0000
         12     13      14     15      16     17     18      19    20
    -0.5537 0.2413 -0.4654 -0.472 -0.3387 -0.407 -0.162 -0.2704 0.264
rep  6.0000 6.0000  6.0000  6.000  6.0000  6.000  6.000  6.0000 5.000

 noon 
          AM       PM
     0.07988 -0.07855
rep 59.00000 60.00000

 Day:noon 
     noon
Day   AM      PM     
  1   -0.6127  0.6127
  rep  3.0000  3.0000
  2   -0.1343  0.1343
  rep  3.0000  3.0000
  3   -0.5543  0.5543
  rep  3.0000  3.0000
  4    0.0923 -0.0923
  rep  3.0000  3.0000
  5   -0.0593  0.0593
  rep  3.0000  3.0000
  6    0.1673 -0.1673
  rep  3.0000  3.0000
  7   -0.1010  0.1010
  rep  3.0000  3.0000
  8    0.3023 -0.3023
  rep  3.0000  3.0000
  9    0.5823 -0.5823
  rep  3.0000  3.0000
  10  -0.4560  0.4560
  rep  3.0000  3.0000
  11   0.8007 -0.8007
  rep  3.0000  3.0000
  12  -0.1243  0.1243
  rep  3.0000  3.0000
  13  -0.2327  0.2327
  rep  3.0000  3.0000
  14  -0.2193  0.2193
  rep  3.0000  3.0000
  15  -0.5593  0.5593
  rep  3.0000  3.0000
  16   0.1740 -0.1740
  rep  3.0000  3.0000
  17   0.4623 -0.4623
  rep  3.0000  3.0000
  18   0.0707 -0.0707
  rep  3.0000  3.0000
  19   0.5290 -0.5290
  rep  3.0000  3.0000
  20  -0.1912  0.1275
  rep  2.0000  3.0000</code></pre>
</div>
</div>
<p>one way ANOVA와 같이 해석</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Day         19   15.5   0.816    1.18   0.29
noon         1    0.7   0.748    1.08   0.30
Day:noon    19   18.1   0.951    1.38   0.16
Residuals   79   54.5   0.690               
1 observation deleted due to missingness</code></pre>
</div>
</div>
<p>위 그림을 보듯이 두 변수의 영향도가 없음, ANOVA 역시 유의하지 않음</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Missing rows: 117 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Ct ~ Day + noon + Day:noon, data = data)

$Day
            diff      lwr     upr   p adj
2-1   -0.2883333 -2.04672 1.47005 1.00000
3-1   -0.1916667 -1.95005 1.56672 1.00000
4-1   -0.6716667 -2.43005 1.08672 0.99700
5-1   -0.1566667 -1.91505 1.60172 1.00000
6-1   -0.3200000 -2.07839 1.43839 1.00000
7-1   -0.3016667 -2.06005 1.45672 1.00000
8-1   -0.2050000 -1.96339 1.55339 1.00000
9-1    0.4016667 -1.35672 2.16005 1.00000
10-1  -0.5966667 -2.35505 1.16172 0.99934
11-1   0.0866667 -1.67172 1.84505 1.00000
12-1  -0.9583333 -2.71672 0.80005 0.89330
13-1  -0.1633333 -1.92172 1.59505 1.00000
14-1  -0.8700000 -2.62839 0.88839 0.95243
15-1  -0.8766667 -2.63505 0.88172 0.94905
16-1  -0.7433333 -2.50172 1.01505 0.99024
17-1  -0.8116667 -2.57005 0.94672 0.97539
18-1  -0.5666667 -2.32505 1.19172 0.99968
19-1  -0.6750000 -2.43339 1.08339 0.99682
20-1  -0.1406667 -1.98488 1.70355 1.00000
3-2    0.0966667 -1.66172 1.85505 1.00000
4-2   -0.3833333 -2.14172 1.37505 1.00000
5-2    0.1316667 -1.62672 1.89005 1.00000
6-2   -0.0316667 -1.79005 1.72672 1.00000
7-2   -0.0133333 -1.77172 1.74505 1.00000
8-2    0.0833333 -1.67505 1.84172 1.00000
9-2    0.6900000 -1.06839 2.44839 0.99585
10-2  -0.3083333 -2.06672 1.45005 1.00000
11-2   0.3750000 -1.38339 2.13339 1.00000
12-2  -0.6700000 -2.42839 1.08839 0.99709
13-2   0.1250000 -1.63339 1.88339 1.00000
14-2  -0.5816667 -2.34005 1.17672 0.99953
15-2  -0.5883333 -2.34672 1.17005 0.99946
16-2  -0.4550000 -2.21339 1.30339 0.99999
17-2  -0.5233333 -2.28172 1.23505 0.99990
18-2  -0.2783333 -2.03672 1.48005 1.00000
19-2  -0.3866667 -2.14505 1.37172 1.00000
20-2   0.1476667 -1.69655 1.99188 1.00000
4-3   -0.4800000 -2.23839 1.27839 0.99997
5-3    0.0350000 -1.72339 1.79339 1.00000
6-3   -0.1283333 -1.88672 1.63005 1.00000
7-3   -0.1100000 -1.86839 1.64839 1.00000
8-3   -0.0133333 -1.77172 1.74505 1.00000
9-3    0.5933333 -1.16505 2.35172 0.99939
10-3  -0.4050000 -2.16339 1.35339 1.00000
11-3   0.2783333 -1.48005 2.03672 1.00000
12-3  -0.7666667 -2.52505 0.99172 0.98634
13-3   0.0283333 -1.73005 1.78672 1.00000
14-3  -0.6783333 -2.43672 1.08005 0.99662
15-3  -0.6850000 -2.44339 1.07339 0.99620
16-3  -0.5516667 -2.31005 1.20672 0.99978
17-3  -0.6200000 -2.37839 1.13839 0.99891
18-3  -0.3750000 -2.13339 1.38339 1.00000
19-3  -0.4833333 -2.24172 1.27505 0.99997
20-3   0.0510000 -1.79321 1.89521 1.00000
5-4    0.5150000 -1.24339 2.27339 0.99992
6-4    0.3516667 -1.40672 2.11005 1.00000
7-4    0.3700000 -1.38839 2.12839 1.00000
8-4    0.4666667 -1.29172 2.22505 0.99998
9-4    1.0733333 -0.68505 2.83172 0.76824
10-4   0.0750000 -1.68339 1.83339 1.00000
11-4   0.7583333 -1.00005 2.51672 0.98785
12-4  -0.2866667 -2.04505 1.47172 1.00000
13-4   0.5083333 -1.25005 2.26672 0.99993
14-4  -0.1983333 -1.95672 1.56005 1.00000
15-4  -0.2050000 -1.96339 1.55339 1.00000
16-4  -0.0716667 -1.83005 1.68672 1.00000
17-4  -0.1400000 -1.89839 1.61839 1.00000
18-4   0.1050000 -1.65339 1.86339 1.00000
19-4  -0.0033333 -1.76172 1.75505 1.00000
20-4   0.5310000 -1.31321 2.37521 0.99994
6-5   -0.1633333 -1.92172 1.59505 1.00000
7-5   -0.1450000 -1.90339 1.61339 1.00000
8-5   -0.0483333 -1.80672 1.71005 1.00000
9-5    0.5583333 -1.20005 2.31672 0.99974
10-5  -0.4400000 -2.19839 1.31839 0.99999
11-5   0.2433333 -1.51505 2.00172 1.00000
12-5  -0.8016667 -2.56005 0.95672 0.97827
13-5  -0.0066667 -1.76505 1.75172 1.00000
14-5  -0.7133333 -2.47172 1.04505 0.99387
15-5  -0.7200000 -2.47839 1.03839 0.99318
16-5  -0.5866667 -2.34505 1.17172 0.99948
17-5  -0.6550000 -2.41339 1.10339 0.99780
18-5  -0.4100000 -2.16839 1.34839 1.00000
19-5  -0.5183333 -2.27672 1.24005 0.99991
20-5   0.0160000 -1.82821 1.86021 1.00000
7-6    0.0183333 -1.74005 1.77672 1.00000
8-6    0.1150000 -1.64339 1.87339 1.00000
9-6    0.7216667 -1.03672 2.48005 0.99300
10-6  -0.2766667 -2.03505 1.48172 1.00000
11-6   0.4066667 -1.35172 2.16505 1.00000
12-6  -0.6383333 -2.39672 1.12005 0.99841
13-6   0.1566667 -1.60172 1.91505 1.00000
14-6  -0.5500000 -2.30839 1.20839 0.99979
15-6  -0.5566667 -2.31505 1.20172 0.99975
16-6  -0.4233333 -2.18172 1.33505 1.00000
17-6  -0.4916667 -2.25005 1.26672 0.99996
18-6  -0.2466667 -2.00505 1.51172 1.00000
19-6  -0.3550000 -2.11339 1.40339 1.00000
20-6   0.1793333 -1.66488 2.02355 1.00000
8-7    0.0966667 -1.66172 1.85505 1.00000
9-7    0.7033333 -1.05505 2.46172 0.99480
10-7  -0.2950000 -2.05339 1.46339 1.00000
11-7   0.3883333 -1.37005 2.14672 1.00000
12-7  -0.6566667 -2.41505 1.10172 0.99773
13-7   0.1383333 -1.62005 1.89672 1.00000
14-7  -0.5683333 -2.32672 1.19005 0.99966
15-7  -0.5750000 -2.33339 1.18339 0.99960
16-7  -0.4416667 -2.20005 1.31672 0.99999
17-7  -0.5100000 -2.26839 1.24839 0.99993
18-7  -0.2650000 -2.02339 1.49339 1.00000
19-7  -0.3733333 -2.13172 1.38505 1.00000
20-7   0.1610000 -1.68321 2.00521 1.00000
9-8    0.6066667 -1.15172 2.36505 0.99918
10-8  -0.3916667 -2.15005 1.36672 1.00000
11-8   0.2916667 -1.46672 2.05005 1.00000
12-8  -0.7533333 -2.51172 1.00505 0.98869
13-8   0.0416667 -1.71672 1.80005 1.00000
14-8  -0.6650000 -2.42339 1.09339 0.99735
15-8  -0.6716667 -2.43005 1.08672 0.99700
16-8  -0.5383333 -2.29672 1.22005 0.99984
17-8  -0.6066667 -2.36505 1.15172 0.99918
18-8  -0.3616667 -2.12005 1.39672 1.00000
19-8  -0.4700000 -2.22839 1.28839 0.99998
20-8   0.0643333 -1.77988 1.90855 1.00000
10-9  -0.9983333 -2.75672 0.76005 0.85576
11-9  -0.3150000 -2.07339 1.44339 1.00000
12-9  -1.3600000 -3.11839 0.39839 0.35269
13-9  -0.5650000 -2.32339 1.19339 0.99969
14-9  -1.2716667 -3.03005 0.48672 0.47719
15-9  -1.2783333 -3.03672 0.48005 0.46731
16-9  -1.1450000 -2.90339 0.61339 0.66832
17-9  -1.2133333 -2.97172 0.54505 0.56535
18-9  -0.9683333 -2.72672 0.79005 0.88455
19-9  -1.0766667 -2.83505 0.68172 0.76389
20-9  -0.5423333 -2.38655 1.30188 0.99991
11-10  0.6833333 -1.07505 2.44172 0.99631
12-10 -0.3616667 -2.12005 1.39672 1.00000
13-10  0.4333333 -1.32505 2.19172 0.99999
14-10 -0.2733333 -2.03172 1.48505 1.00000
15-10 -0.2800000 -2.03839 1.47839 1.00000
16-10 -0.1466667 -1.90505 1.61172 1.00000
17-10 -0.2150000 -1.97339 1.54339 1.00000
18-10  0.0300000 -1.72839 1.78839 1.00000
19-10 -0.0783333 -1.83672 1.68005 1.00000
20-10  0.4560000 -1.38821 2.30021 0.99999
12-11 -1.0450000 -2.80339 0.71339 0.80373
13-11 -0.2500000 -2.00839 1.50839 1.00000
14-11 -0.9566667 -2.71505 0.80172 0.89472
15-11 -0.9633333 -2.72172 0.79505 0.88898
16-11 -0.8300000 -2.58839 0.92839 0.96936
17-11 -0.8983333 -2.65672 0.86005 0.93692
18-11 -0.6533333 -2.41172 1.10505 0.99787
19-11 -0.7616667 -2.52005 0.99672 0.98726
20-11 -0.2273333 -2.07155 1.61688 1.00000
13-12  0.7950000 -0.96339 2.55339 0.98004
14-12  0.0883333 -1.67005 1.84672 1.00000
15-12  0.0816667 -1.67672 1.84005 1.00000
16-12  0.2150000 -1.54339 1.97339 1.00000
17-12  0.1466667 -1.61172 1.90505 1.00000
18-12  0.3916667 -1.36672 2.15005 1.00000
19-12  0.2833333 -1.47505 2.04172 1.00000
20-12  0.8176667 -1.02655 2.66188 0.98369
14-13 -0.7066667 -2.46505 1.05172 0.99450
15-13 -0.7133333 -2.47172 1.04505 0.99387
16-13 -0.5800000 -2.33839 1.17839 0.99955
17-13 -0.6483333 -2.40672 1.11005 0.99807
18-13 -0.4033333 -2.16172 1.35505 1.00000
19-13 -0.5116667 -2.27005 1.24672 0.99992
20-13  0.0226667 -1.82155 1.86688 1.00000
15-14 -0.0066667 -1.76505 1.75172 1.00000
16-14  0.1266667 -1.63172 1.88505 1.00000
17-14  0.0583333 -1.70005 1.81672 1.00000
18-14  0.3033333 -1.45505 2.06172 1.00000
19-14  0.1950000 -1.56339 1.95339 1.00000
20-14  0.7293333 -1.11488 2.57355 0.99545
16-15  0.1333333 -1.62505 1.89172 1.00000
17-15  0.0650000 -1.69339 1.82339 1.00000
18-15  0.3100000 -1.44839 2.06839 1.00000
19-15  0.2016667 -1.55672 1.96005 1.00000
20-15  0.7360000 -1.10821 2.58021 0.99493
17-16 -0.0683333 -1.82672 1.69005 1.00000
18-16  0.1766667 -1.58172 1.93505 1.00000
19-16  0.0683333 -1.69005 1.82672 1.00000
20-16  0.6026667 -1.24155 2.44688 0.99961
18-17  0.2450000 -1.51339 2.00339 1.00000
19-17  0.1366667 -1.62172 1.89505 1.00000
20-17  0.6710000 -1.17321 2.51521 0.99837
19-18 -0.1083333 -1.86672 1.65005 1.00000
20-18  0.4260000 -1.41821 2.27021 1.00000
20-19  0.5343333 -1.30988 2.37855 0.99993

$noon
          diff      lwr     upr   p adj
PM-AM -0.15843 -0.46155 0.14469 0.30135

$`Day:noon`
                  diff      lwr     upr   p adj
2:AM-1:AM    0.1900000 -2.55252 2.93252 1.00000
3:AM-1:AM   -0.1333333 -2.87586 2.60919 1.00000
4:AM-1:AM    0.0333333 -2.70919 2.77586 1.00000
5:AM-1:AM    0.3966667 -2.34586 3.13919 1.00000
6:AM-1:AM    0.4600000 -2.28252 3.20252 1.00000
7:AM-1:AM    0.2100000 -2.53252 2.95252 1.00000
8:AM-1:AM    0.7100000 -2.03252 3.45252 1.00000
9:AM-1:AM    1.5966667 -1.14586 4.33919 0.92887
10:AM-1:AM  -0.4400000 -3.18252 2.30252 1.00000
11:AM-1:AM   1.5000000 -1.24252 4.24252 0.96592
12:AM-1:AM  -0.4700000 -3.21252 2.27252 1.00000
13:AM-1:AM   0.2166667 -2.52586 2.95919 1.00000
14:AM-1:AM  -0.4766667 -3.21919 2.26586 1.00000
15:AM-1:AM  -0.8233333 -3.56586 1.91919 1.00000
16:AM-1:AM   0.0433333 -2.69919 2.78586 1.00000
17:AM-1:AM   0.2633333 -2.47919 3.00586 1.00000
18:AM-1:AM   0.1166667 -2.62586 2.85919 1.00000
19:AM-1:AM   0.4666667 -2.27586 3.20919 1.00000
20:AM-1:AM   0.2966667 -2.76957 3.36290 1.00000
1:PM-1:AM    1.0666667 -1.67586 3.80919 0.99990
2:PM-1:AM    0.3000000 -2.44252 3.04252 1.00000
3:PM-1:AM    0.8166667 -1.92586 3.55919 1.00000
4:PM-1:AM   -0.3100000 -3.05252 2.43252 1.00000
5:PM-1:AM    0.3566667 -2.38586 3.09919 1.00000
6:PM-1:AM   -0.0333333 -2.77586 2.70919 1.00000
7:PM-1:AM    0.2533333 -2.48919 2.99586 1.00000
8:PM-1:AM   -0.0533333 -2.79586 2.68919 1.00000
9:PM-1:AM    0.2733333 -2.46919 3.01586 1.00000
10:PM-1:AM   0.3133333 -2.42919 3.05586 1.00000
11:PM-1:AM  -0.2600000 -3.00252 2.48252 1.00000
12:PM-1:AM  -0.3800000 -3.12252 2.36252 1.00000
13:PM-1:AM   0.5233333 -2.21919 3.26586 1.00000
14:PM-1:AM  -0.1966667 -2.93919 2.54586 1.00000
15:PM-1:AM   0.1366667 -2.60586 2.87919 1.00000
16:PM-1:AM  -0.4633333 -3.20586 2.27919 1.00000
17:PM-1:AM  -0.8200000 -3.56252 1.92252 1.00000
18:PM-1:AM  -0.1833333 -2.92586 2.55919 1.00000
19:PM-1:AM  -0.7500000 -3.49252 1.99252 1.00000
20:PM-1:AM   0.4566667 -2.28586 3.19919 1.00000
3:AM-2:AM   -0.3233333 -3.06586 2.41919 1.00000
4:AM-2:AM   -0.1566667 -2.89919 2.58586 1.00000
5:AM-2:AM    0.2066667 -2.53586 2.94919 1.00000
6:AM-2:AM    0.2700000 -2.47252 3.01252 1.00000
7:AM-2:AM    0.0200000 -2.72252 2.76252 1.00000
8:AM-2:AM    0.5200000 -2.22252 3.26252 1.00000
9:AM-2:AM    1.4066667 -1.33586 4.14919 0.98570
10:AM-2:AM  -0.6300000 -3.37252 2.11252 1.00000
11:AM-2:AM   1.3100000 -1.43252 4.05252 0.99521
12:AM-2:AM  -0.6600000 -3.40252 2.08252 1.00000
13:AM-2:AM   0.0266667 -2.71586 2.76919 1.00000
14:AM-2:AM  -0.6666667 -3.40919 2.07586 1.00000
15:AM-2:AM  -1.0133333 -3.75586 1.72919 0.99997
16:AM-2:AM  -0.1466667 -2.88919 2.59586 1.00000
17:AM-2:AM   0.0733333 -2.66919 2.81586 1.00000
18:AM-2:AM  -0.0733333 -2.81586 2.66919 1.00000
19:AM-2:AM   0.2766667 -2.46586 3.01919 1.00000
20:AM-2:AM   0.1066667 -2.95957 3.17290 1.00000
1:PM-2:AM    0.8766667 -1.86586 3.61919 1.00000
2:PM-2:AM    0.1100000 -2.63252 2.85252 1.00000
3:PM-2:AM    0.6266667 -2.11586 3.36919 1.00000
4:PM-2:AM   -0.5000000 -3.24252 2.24252 1.00000
5:PM-2:AM    0.1666667 -2.57586 2.90919 1.00000
6:PM-2:AM   -0.2233333 -2.96586 2.51919 1.00000
7:PM-2:AM    0.0633333 -2.67919 2.80586 1.00000
8:PM-2:AM   -0.2433333 -2.98586 2.49919 1.00000
9:PM-2:AM    0.0833333 -2.65919 2.82586 1.00000
10:PM-2:AM   0.1233333 -2.61919 2.86586 1.00000
11:PM-2:AM  -0.4500000 -3.19252 2.29252 1.00000
12:PM-2:AM  -0.5700000 -3.31252 2.17252 1.00000
13:PM-2:AM   0.3333333 -2.40919 3.07586 1.00000
14:PM-2:AM  -0.3866667 -3.12919 2.35586 1.00000
15:PM-2:AM  -0.0533333 -2.79586 2.68919 1.00000
16:PM-2:AM  -0.6533333 -3.39586 2.08919 1.00000
17:PM-2:AM  -1.0100000 -3.75252 1.73252 0.99997
18:PM-2:AM  -0.3733333 -3.11586 2.36919 1.00000
19:PM-2:AM  -0.9400000 -3.68252 1.80252 0.99999
20:PM-2:AM   0.2666667 -2.47586 3.00919 1.00000
4:AM-3:AM    0.1666667 -2.57586 2.90919 1.00000
5:AM-3:AM    0.5300000 -2.21252 3.27252 1.00000
6:AM-3:AM    0.5933333 -2.14919 3.33586 1.00000
7:AM-3:AM    0.3433333 -2.39919 3.08586 1.00000
8:AM-3:AM    0.8433333 -1.89919 3.58586 1.00000
9:AM-3:AM    1.7300000 -1.01252 4.47252 0.84321
10:AM-3:AM  -0.3066667 -3.04919 2.43586 1.00000
11:AM-3:AM   1.6333333 -1.10919 4.37586 0.90946
12:AM-3:AM  -0.3366667 -3.07919 2.40586 1.00000
13:AM-3:AM   0.3500000 -2.39252 3.09252 1.00000
14:AM-3:AM  -0.3433333 -3.08586 2.39919 1.00000
15:AM-3:AM  -0.6900000 -3.43252 2.05252 1.00000
16:AM-3:AM   0.1766667 -2.56586 2.91919 1.00000
17:AM-3:AM   0.3966667 -2.34586 3.13919 1.00000
18:AM-3:AM   0.2500000 -2.49252 2.99252 1.00000
19:AM-3:AM   0.6000000 -2.14252 3.34252 1.00000
20:AM-3:AM   0.4300000 -2.63623 3.49623 1.00000
1:PM-3:AM    1.2000000 -1.54252 3.94252 0.99897
2:PM-3:AM    0.4333333 -2.30919 3.17586 1.00000
3:PM-3:AM    0.9500000 -1.79252 3.69252 0.99999
4:PM-3:AM   -0.1766667 -2.91919 2.56586 1.00000
5:PM-3:AM    0.4900000 -2.25252 3.23252 1.00000
6:PM-3:AM    0.1000000 -2.64252 2.84252 1.00000
7:PM-3:AM    0.3866667 -2.35586 3.12919 1.00000
8:PM-3:AM    0.0800000 -2.66252 2.82252 1.00000
9:PM-3:AM    0.4066667 -2.33586 3.14919 1.00000
10:PM-3:AM   0.4466667 -2.29586 3.18919 1.00000
11:PM-3:AM  -0.1266667 -2.86919 2.61586 1.00000
12:PM-3:AM  -0.2466667 -2.98919 2.49586 1.00000
13:PM-3:AM   0.6566667 -2.08586 3.39919 1.00000
14:PM-3:AM  -0.0633333 -2.80586 2.67919 1.00000
15:PM-3:AM   0.2700000 -2.47252 3.01252 1.00000
16:PM-3:AM  -0.3300000 -3.07252 2.41252 1.00000
17:PM-3:AM  -0.6866667 -3.42919 2.05586 1.00000
18:PM-3:AM  -0.0500000 -2.79252 2.69252 1.00000
19:PM-3:AM  -0.6166667 -3.35919 2.12586 1.00000
20:PM-3:AM   0.5900000 -2.15252 3.33252 1.00000
5:AM-4:AM    0.3633333 -2.37919 3.10586 1.00000
6:AM-4:AM    0.4266667 -2.31586 3.16919 1.00000
7:AM-4:AM    0.1766667 -2.56586 2.91919 1.00000
8:AM-4:AM    0.6766667 -2.06586 3.41919 1.00000
9:AM-4:AM    1.5633333 -1.17919 4.30586 0.94386
10:AM-4:AM  -0.4733333 -3.21586 2.26919 1.00000
11:AM-4:AM   1.4666667 -1.27586 4.20919 0.97452
12:AM-4:AM  -0.5033333 -3.24586 2.23919 1.00000
13:AM-4:AM   0.1833333 -2.55919 2.92586 1.00000
14:AM-4:AM  -0.5100000 -3.25252 2.23252 1.00000
15:AM-4:AM  -0.8566667 -3.59919 1.88586 1.00000
16:AM-4:AM   0.0100000 -2.73252 2.75252 1.00000
17:AM-4:AM   0.2300000 -2.51252 2.97252 1.00000
18:AM-4:AM   0.0833333 -2.65919 2.82586 1.00000
19:AM-4:AM   0.4333333 -2.30919 3.17586 1.00000
20:AM-4:AM   0.2633333 -2.80290 3.32957 1.00000
1:PM-4:AM    1.0333333 -1.70919 3.77586 0.99995
2:PM-4:AM    0.2666667 -2.47586 3.00919 1.00000
3:PM-4:AM    0.7833333 -1.95919 3.52586 1.00000
4:PM-4:AM   -0.3433333 -3.08586 2.39919 1.00000
5:PM-4:AM    0.3233333 -2.41919 3.06586 1.00000
6:PM-4:AM   -0.0666667 -2.80919 2.67586 1.00000
7:PM-4:AM    0.2200000 -2.52252 2.96252 1.00000
8:PM-4:AM   -0.0866667 -2.82919 2.65586 1.00000
9:PM-4:AM    0.2400000 -2.50252 2.98252 1.00000
10:PM-4:AM   0.2800000 -2.46252 3.02252 1.00000
11:PM-4:AM  -0.2933333 -3.03586 2.44919 1.00000
12:PM-4:AM  -0.4133333 -3.15586 2.32919 1.00000
13:PM-4:AM   0.4900000 -2.25252 3.23252 1.00000
14:PM-4:AM  -0.2300000 -2.97252 2.51252 1.00000
15:PM-4:AM   0.1033333 -2.63919 2.84586 1.00000
16:PM-4:AM  -0.4966667 -3.23919 2.24586 1.00000
17:PM-4:AM  -0.8533333 -3.59586 1.88919 1.00000
18:PM-4:AM  -0.2166667 -2.95919 2.52586 1.00000
19:PM-4:AM  -0.7833333 -3.52586 1.95919 1.00000
20:PM-4:AM   0.4233333 -2.31919 3.16586 1.00000
6:AM-5:AM    0.0633333 -2.67919 2.80586 1.00000
7:AM-5:AM   -0.1866667 -2.92919 2.55586 1.00000
8:AM-5:AM    0.3133333 -2.42919 3.05586 1.00000
9:AM-5:AM    1.2000000 -1.54252 3.94252 0.99897
10:AM-5:AM  -0.8366667 -3.57919 1.90586 1.00000
11:AM-5:AM   1.1033333 -1.63919 3.84586 0.99980
12:AM-5:AM  -0.8666667 -3.60919 1.87586 1.00000
13:AM-5:AM  -0.1800000 -2.92252 2.56252 1.00000
14:AM-5:AM  -0.8733333 -3.61586 1.86919 1.00000
15:AM-5:AM  -1.2200000 -3.96252 1.52252 0.99860
16:AM-5:AM  -0.3533333 -3.09586 2.38919 1.00000
17:AM-5:AM  -0.1333333 -2.87586 2.60919 1.00000
18:AM-5:AM  -0.2800000 -3.02252 2.46252 1.00000
19:AM-5:AM   0.0700000 -2.67252 2.81252 1.00000
20:AM-5:AM  -0.1000000 -3.16623 2.96623 1.00000
1:PM-5:AM    0.6700000 -2.07252 3.41252 1.00000
2:PM-5:AM   -0.0966667 -2.83919 2.64586 1.00000
3:PM-5:AM    0.4200000 -2.32252 3.16252 1.00000
4:PM-5:AM   -0.7066667 -3.44919 2.03586 1.00000
5:PM-5:AM   -0.0400000 -2.78252 2.70252 1.00000
6:PM-5:AM   -0.4300000 -3.17252 2.31252 1.00000
7:PM-5:AM   -0.1433333 -2.88586 2.59919 1.00000
8:PM-5:AM   -0.4500000 -3.19252 2.29252 1.00000
9:PM-5:AM   -0.1233333 -2.86586 2.61919 1.00000
10:PM-5:AM  -0.0833333 -2.82586 2.65919 1.00000
11:PM-5:AM  -0.6566667 -3.39919 2.08586 1.00000
12:PM-5:AM  -0.7766667 -3.51919 1.96586 1.00000
13:PM-5:AM   0.1266667 -2.61586 2.86919 1.00000
14:PM-5:AM  -0.5933333 -3.33586 2.14919 1.00000
15:PM-5:AM  -0.2600000 -3.00252 2.48252 1.00000
16:PM-5:AM  -0.8600000 -3.60252 1.88252 1.00000
17:PM-5:AM  -1.2166667 -3.95919 1.52586 0.99867
18:PM-5:AM  -0.5800000 -3.32252 2.16252 1.00000
19:PM-5:AM  -1.1466667 -3.88919 1.59586 0.99957
20:PM-5:AM   0.0600000 -2.68252 2.80252 1.00000
7:AM-6:AM   -0.2500000 -2.99252 2.49252 1.00000
8:AM-6:AM    0.2500000 -2.49252 2.99252 1.00000
9:AM-6:AM    1.1366667 -1.60586 3.87919 0.99964
10:AM-6:AM  -0.9000000 -3.64252 1.84252 1.00000
11:AM-6:AM   1.0400000 -1.70252 3.78252 0.99994
12:AM-6:AM  -0.9300000 -3.67252 1.81252 1.00000
13:AM-6:AM  -0.2433333 -2.98586 2.49919 1.00000
14:AM-6:AM  -0.9366667 -3.67919 1.80586 1.00000
15:AM-6:AM  -1.2833333 -4.02586 1.45919 0.99660
16:AM-6:AM  -0.4166667 -3.15919 2.32586 1.00000
17:AM-6:AM  -0.1966667 -2.93919 2.54586 1.00000
18:AM-6:AM  -0.3433333 -3.08586 2.39919 1.00000
19:AM-6:AM   0.0066667 -2.73586 2.74919 1.00000
20:AM-6:AM  -0.1633333 -3.22957 2.90290 1.00000
1:PM-6:AM    0.6066667 -2.13586 3.34919 1.00000
2:PM-6:AM   -0.1600000 -2.90252 2.58252 1.00000
3:PM-6:AM    0.3566667 -2.38586 3.09919 1.00000
4:PM-6:AM   -0.7700000 -3.51252 1.97252 1.00000
5:PM-6:AM   -0.1033333 -2.84586 2.63919 1.00000
6:PM-6:AM   -0.4933333 -3.23586 2.24919 1.00000
7:PM-6:AM   -0.2066667 -2.94919 2.53586 1.00000
8:PM-6:AM   -0.5133333 -3.25586 2.22919 1.00000
9:PM-6:AM   -0.1866667 -2.92919 2.55586 1.00000
10:PM-6:AM  -0.1466667 -2.88919 2.59586 1.00000
11:PM-6:AM  -0.7200000 -3.46252 2.02252 1.00000
12:PM-6:AM  -0.8400000 -3.58252 1.90252 1.00000
13:PM-6:AM   0.0633333 -2.67919 2.80586 1.00000
14:PM-6:AM  -0.6566667 -3.39919 2.08586 1.00000
15:PM-6:AM  -0.3233333 -3.06586 2.41919 1.00000
16:PM-6:AM  -0.9233333 -3.66586 1.81919 1.00000
17:PM-6:AM  -1.2800000 -4.02252 1.46252 0.99674
18:PM-6:AM  -0.6433333 -3.38586 2.09919 1.00000
19:PM-6:AM  -1.2100000 -3.95252 1.53252 0.99880
20:PM-6:AM  -0.0033333 -2.74586 2.73919 1.00000
8:AM-7:AM    0.5000000 -2.24252 3.24252 1.00000
9:AM-7:AM    1.3866667 -1.35586 4.12919 0.98840
10:AM-7:AM  -0.6500000 -3.39252 2.09252 1.00000
11:AM-7:AM   1.2900000 -1.45252 4.03252 0.99629
12:AM-7:AM  -0.6800000 -3.42252 2.06252 1.00000
13:AM-7:AM   0.0066667 -2.73586 2.74919 1.00000
14:AM-7:AM  -0.6866667 -3.42919 2.05586 1.00000
15:AM-7:AM  -1.0333333 -3.77586 1.70919 0.99995
16:AM-7:AM  -0.1666667 -2.90919 2.57586 1.00000
17:AM-7:AM   0.0533333 -2.68919 2.79586 1.00000
18:AM-7:AM  -0.0933333 -2.83586 2.64919 1.00000
19:AM-7:AM   0.2566667 -2.48586 2.99919 1.00000
20:AM-7:AM   0.0866667 -2.97957 3.15290 1.00000
1:PM-7:AM    0.8566667 -1.88586 3.59919 1.00000
2:PM-7:AM    0.0900000 -2.65252 2.83252 1.00000
3:PM-7:AM    0.6066667 -2.13586 3.34919 1.00000
4:PM-7:AM   -0.5200000 -3.26252 2.22252 1.00000
5:PM-7:AM    0.1466667 -2.59586 2.88919 1.00000
6:PM-7:AM   -0.2433333 -2.98586 2.49919 1.00000
7:PM-7:AM    0.0433333 -2.69919 2.78586 1.00000
8:PM-7:AM   -0.2633333 -3.00586 2.47919 1.00000
9:PM-7:AM    0.0633333 -2.67919 2.80586 1.00000
10:PM-7:AM   0.1033333 -2.63919 2.84586 1.00000
11:PM-7:AM  -0.4700000 -3.21252 2.27252 1.00000
12:PM-7:AM  -0.5900000 -3.33252 2.15252 1.00000
13:PM-7:AM   0.3133333 -2.42919 3.05586 1.00000
14:PM-7:AM  -0.4066667 -3.14919 2.33586 1.00000
15:PM-7:AM  -0.0733333 -2.81586 2.66919 1.00000
16:PM-7:AM  -0.6733333 -3.41586 2.06919 1.00000
17:PM-7:AM  -1.0300000 -3.77252 1.71252 0.99996
18:PM-7:AM  -0.3933333 -3.13586 2.34919 1.00000
19:PM-7:AM  -0.9600000 -3.70252 1.78252 0.99999
20:PM-7:AM   0.2466667 -2.49586 2.98919 1.00000
9:AM-8:AM    0.8866667 -1.85586 3.62919 1.00000
10:AM-8:AM  -1.1500000 -3.89252 1.59252 0.99954
11:AM-8:AM   0.7900000 -1.95252 3.53252 1.00000
12:AM-8:AM  -1.1800000 -3.92252 1.56252 0.99925
13:AM-8:AM  -0.4933333 -3.23586 2.24919 1.00000
14:AM-8:AM  -1.1866667 -3.92919 1.55586 0.99916
15:AM-8:AM  -1.5333333 -4.27586 1.20919 0.95531
16:AM-8:AM  -0.6666667 -3.40919 2.07586 1.00000
17:AM-8:AM  -0.4466667 -3.18919 2.29586 1.00000
18:AM-8:AM  -0.5933333 -3.33586 2.14919 1.00000
19:AM-8:AM  -0.2433333 -2.98586 2.49919 1.00000
20:AM-8:AM  -0.4133333 -3.47957 2.65290 1.00000
1:PM-8:AM    0.3566667 -2.38586 3.09919 1.00000
2:PM-8:AM   -0.4100000 -3.15252 2.33252 1.00000
3:PM-8:AM    0.1066667 -2.63586 2.84919 1.00000
4:PM-8:AM   -1.0200000 -3.76252 1.72252 0.99996
5:PM-8:AM   -0.3533333 -3.09586 2.38919 1.00000
6:PM-8:AM   -0.7433333 -3.48586 1.99919 1.00000
7:PM-8:AM   -0.4566667 -3.19919 2.28586 1.00000
8:PM-8:AM   -0.7633333 -3.50586 1.97919 1.00000
9:PM-8:AM   -0.4366667 -3.17919 2.30586 1.00000
10:PM-8:AM  -0.3966667 -3.13919 2.34586 1.00000
11:PM-8:AM  -0.9700000 -3.71252 1.77252 0.99999
12:PM-8:AM  -1.0900000 -3.83252 1.65252 0.99985
13:PM-8:AM  -0.1866667 -2.92919 2.55586 1.00000
14:PM-8:AM  -0.9066667 -3.64919 1.83586 1.00000
15:PM-8:AM  -0.5733333 -3.31586 2.16919 1.00000
16:PM-8:AM  -1.1733333 -3.91586 1.56919 0.99933
17:PM-8:AM  -1.5300000 -4.27252 1.21252 0.95647
18:PM-8:AM  -0.8933333 -3.63586 1.84919 1.00000
19:PM-8:AM  -1.4600000 -4.20252 1.28252 0.97602
20:PM-8:AM  -0.2533333 -2.99586 2.48919 1.00000
10:AM-9:AM  -2.0366667 -4.77919 0.70586 0.52759
11:AM-9:AM  -0.0966667 -2.83919 2.64586 1.00000
12:AM-9:AM  -2.0666667 -4.80919 0.67586 0.49403
13:AM-9:AM  -1.3800000 -4.12252 1.36252 0.98920
14:AM-9:AM  -2.0733333 -4.81586 0.66919 0.48663
15:AM-9:AM  -2.4200000 -5.16252 0.32252 0.17781
16:AM-9:AM  -1.5533333 -4.29586 1.18919 0.94789
17:AM-9:AM  -1.3333333 -4.07586 1.40919 0.99364
18:AM-9:AM  -1.4800000 -4.22252 1.26252 0.97131
19:AM-9:AM  -1.1300000 -3.87252 1.61252 0.99968
20:AM-9:AM  -1.3000000 -4.36623 1.76623 0.99943
1:PM-9:AM   -0.5300000 -3.27252 2.21252 1.00000
2:PM-9:AM   -1.2966667 -4.03919 1.44586 0.99595
3:PM-9:AM   -0.7800000 -3.52252 1.96252 1.00000
4:PM-9:AM   -1.9066667 -4.64919 0.83586 0.67322
5:PM-9:AM   -1.2400000 -3.98252 1.50252 0.99812
6:PM-9:AM   -1.6300000 -4.37252 1.11252 0.91136
7:PM-9:AM   -1.3433333 -4.08586 1.39919 0.99284
8:PM-9:AM   -1.6500000 -4.39252 1.09252 0.89961
9:PM-9:AM   -1.3233333 -4.06586 1.41919 0.99436
10:PM-9:AM  -1.2833333 -4.02586 1.45919 0.99660
11:PM-9:AM  -1.8566667 -4.59919 0.88586 0.72631
12:PM-9:AM  -1.9766667 -4.71919 0.76586 0.59536
13:PM-9:AM  -1.0733333 -3.81586 1.66919 0.99989
14:PM-9:AM  -1.7933333 -4.53586 0.94919 0.78850
15:PM-9:AM  -1.4600000 -4.20252 1.28252 0.97602
16:PM-9:AM  -2.0600000 -4.80252 0.68252 0.50145
17:PM-9:AM  -2.4166667 -5.15919 0.32586 0.17988
18:PM-9:AM  -1.7800000 -4.52252 0.96252 0.80070
19:PM-9:AM  -2.3466667 -5.08919 0.39586 0.22767
20:PM-9:AM  -1.1400000 -3.88252 1.60252 0.99962
11:AM-10:AM  1.9400000 -0.80252 4.68252 0.63649
12:AM-10:AM -0.0300000 -2.77252 2.71252 1.00000
13:AM-10:AM  0.6566667 -2.08586 3.39919 1.00000
14:AM-10:AM -0.0366667 -2.77919 2.70586 1.00000
15:AM-10:AM -0.3833333 -3.12586 2.35919 1.00000
16:AM-10:AM  0.4833333 -2.25919 3.22586 1.00000
17:AM-10:AM  0.7033333 -2.03919 3.44586 1.00000
18:AM-10:AM  0.5566667 -2.18586 3.29919 1.00000
19:AM-10:AM  0.9066667 -1.83586 3.64919 1.00000
20:AM-10:AM  0.7366667 -2.32957 3.80290 1.00000
1:PM-10:AM   1.5066667 -1.23586 4.24919 0.96397
2:PM-10:AM   0.7400000 -2.00252 3.48252 1.00000
3:PM-10:AM   1.2566667 -1.48586 3.99919 0.99763
4:PM-10:AM   0.1300000 -2.61252 2.87252 1.00000
5:PM-10:AM   0.7966667 -1.94586 3.53919 1.00000
6:PM-10:AM   0.4066667 -2.33586 3.14919 1.00000
7:PM-10:AM   0.6933333 -2.04919 3.43586 1.00000
8:PM-10:AM   0.3866667 -2.35586 3.12919 1.00000
9:PM-10:AM   0.7133333 -2.02919 3.45586 1.00000
10:PM-10:AM  0.7533333 -1.98919 3.49586 1.00000
11:PM-10:AM  0.1800000 -2.56252 2.92252 1.00000
12:PM-10:AM  0.0600000 -2.68252 2.80252 1.00000
13:PM-10:AM  0.9633333 -1.77919 3.70586 0.99999
14:PM-10:AM  0.2433333 -2.49919 2.98586 1.00000
15:PM-10:AM  0.5766667 -2.16586 3.31919 1.00000
16:PM-10:AM -0.0233333 -2.76586 2.71919 1.00000
17:PM-10:AM -0.3800000 -3.12252 2.36252 1.00000
18:PM-10:AM  0.2566667 -2.48586 2.99919 1.00000
19:PM-10:AM -0.3100000 -3.05252 2.43252 1.00000
20:PM-10:AM  0.8966667 -1.84586 3.63919 1.00000
12:AM-11:AM -1.9700000 -4.71252 0.77252 0.60287
13:AM-11:AM -1.2833333 -4.02586 1.45919 0.99660
14:AM-11:AM -1.9766667 -4.71919 0.76586 0.59536
15:AM-11:AM -2.3233333 -5.06586 0.41919 0.24541
16:AM-11:AM -1.4566667 -4.19919 1.28586 0.97675
17:AM-11:AM -1.2366667 -3.97919 1.50586 0.99821
18:AM-11:AM -1.3833333 -4.12586 1.35919 0.98880
19:AM-11:AM -1.0333333 -3.77586 1.70919 0.99995
20:AM-11:AM -1.2033333 -4.26957 1.86290 0.99988
1:PM-11:AM  -0.4333333 -3.17586 2.30919 1.00000
2:PM-11:AM  -1.2000000 -3.94252 1.54252 0.99897
3:PM-11:AM  -0.6833333 -3.42586 2.05919 1.00000
4:PM-11:AM  -1.8100000 -4.55252 0.93252 0.77279
5:PM-11:AM  -1.1433333 -3.88586 1.59919 0.99959
6:PM-11:AM  -1.5333333 -4.27586 1.20919 0.95531
7:PM-11:AM  -1.2466667 -3.98919 1.49586 0.99794
8:PM-11:AM  -1.5533333 -4.29586 1.18919 0.94789
9:PM-11:AM  -1.2266667 -3.96919 1.51586 0.99846
10:PM-11:AM -1.1866667 -3.92919 1.55586 0.99916
11:PM-11:AM -1.7600000 -4.50252 0.98252 0.81833
12:PM-11:AM -1.8800000 -4.62252 0.86252 0.70190
13:PM-11:AM -0.9766667 -3.71919 1.76586 0.99999
14:PM-11:AM -1.6966667 -4.43919 1.04586 0.86852
15:PM-11:AM -1.3633333 -4.10586 1.37919 0.99101
16:PM-11:AM -1.9633333 -4.70586 0.77919 0.61038
17:PM-11:AM -2.3200000 -5.06252 0.42252 0.24802
18:PM-11:AM -1.6833333 -4.42586 1.05919 0.87792
19:PM-11:AM -2.2500000 -4.99252 0.49252 0.30702
20:PM-11:AM -1.0433333 -3.78586 1.69919 0.99994
13:AM-12:AM  0.6866667 -2.05586 3.42919 1.00000
14:AM-12:AM -0.0066667 -2.74919 2.73586 1.00000
15:AM-12:AM -0.3533333 -3.09586 2.38919 1.00000
16:AM-12:AM  0.5133333 -2.22919 3.25586 1.00000
17:AM-12:AM  0.7333333 -2.00919 3.47586 1.00000
18:AM-12:AM  0.5866667 -2.15586 3.32919 1.00000
19:AM-12:AM  0.9366667 -1.80586 3.67919 1.00000
20:AM-12:AM  0.7666667 -2.29957 3.83290 1.00000
1:PM-12:AM   1.5366667 -1.20586 4.27919 0.95413
2:PM-12:AM   0.7700000 -1.97252 3.51252 1.00000
3:PM-12:AM   1.2866667 -1.45586 4.02919 0.99645
4:PM-12:AM   0.1600000 -2.58252 2.90252 1.00000
5:PM-12:AM   0.8266667 -1.91586 3.56919 1.00000
6:PM-12:AM   0.4366667 -2.30586 3.17919 1.00000
7:PM-12:AM   0.7233333 -2.01919 3.46586 1.00000
8:PM-12:AM   0.4166667 -2.32586 3.15919 1.00000
9:PM-12:AM   0.7433333 -1.99919 3.48586 1.00000
10:PM-12:AM  0.7833333 -1.95919 3.52586 1.00000
11:PM-12:AM  0.2100000 -2.53252 2.95252 1.00000
12:PM-12:AM  0.0900000 -2.65252 2.83252 1.00000
13:PM-12:AM  0.9933333 -1.74919 3.73586 0.99998
14:PM-12:AM  0.2733333 -2.46919 3.01586 1.00000
15:PM-12:AM  0.6066667 -2.13586 3.34919 1.00000
16:PM-12:AM  0.0066667 -2.73586 2.74919 1.00000
17:PM-12:AM -0.3500000 -3.09252 2.39252 1.00000
18:PM-12:AM  0.2866667 -2.45586 3.02919 1.00000
19:PM-12:AM -0.2800000 -3.02252 2.46252 1.00000
20:PM-12:AM  0.9266667 -1.81586 3.66919 1.00000
14:AM-13:AM -0.6933333 -3.43586 2.04919 1.00000
15:AM-13:AM -1.0400000 -3.78252 1.70252 0.99994
16:AM-13:AM -0.1733333 -2.91586 2.56919 1.00000
17:AM-13:AM  0.0466667 -2.69586 2.78919 1.00000
18:AM-13:AM -0.1000000 -2.84252 2.64252 1.00000
19:AM-13:AM  0.2500000 -2.49252 2.99252 1.00000
20:AM-13:AM  0.0800000 -2.98623 3.14623 1.00000
1:PM-13:AM   0.8500000 -1.89252 3.59252 1.00000
2:PM-13:AM   0.0833333 -2.65919 2.82586 1.00000
3:PM-13:AM   0.6000000 -2.14252 3.34252 1.00000
4:PM-13:AM  -0.5266667 -3.26919 2.21586 1.00000
5:PM-13:AM   0.1400000 -2.60252 2.88252 1.00000
6:PM-13:AM  -0.2500000 -2.99252 2.49252 1.00000
7:PM-13:AM   0.0366667 -2.70586 2.77919 1.00000
8:PM-13:AM  -0.2700000 -3.01252 2.47252 1.00000
9:PM-13:AM   0.0566667 -2.68586 2.79919 1.00000
10:PM-13:AM  0.0966667 -2.64586 2.83919 1.00000
11:PM-13:AM -0.4766667 -3.21919 2.26586 1.00000
12:PM-13:AM -0.5966667 -3.33919 2.14586 1.00000
13:PM-13:AM  0.3066667 -2.43586 3.04919 1.00000
14:PM-13:AM -0.4133333 -3.15586 2.32919 1.00000
15:PM-13:AM -0.0800000 -2.82252 2.66252 1.00000
16:PM-13:AM -0.6800000 -3.42252 2.06252 1.00000
17:PM-13:AM -1.0366667 -3.77919 1.70586 0.99995
18:PM-13:AM -0.4000000 -3.14252 2.34252 1.00000
19:PM-13:AM -0.9666667 -3.70919 1.77586 0.99999
20:PM-13:AM  0.2400000 -2.50252 2.98252 1.00000
15:AM-14:AM -0.3466667 -3.08919 2.39586 1.00000
16:AM-14:AM  0.5200000 -2.22252 3.26252 1.00000
17:AM-14:AM  0.7400000 -2.00252 3.48252 1.00000
18:AM-14:AM  0.5933333 -2.14919 3.33586 1.00000
19:AM-14:AM  0.9433333 -1.79919 3.68586 0.99999
20:AM-14:AM  0.7733333 -2.29290 3.83957 1.00000
1:PM-14:AM   1.5433333 -1.19919 4.28586 0.95170
2:PM-14:AM   0.7766667 -1.96586 3.51919 1.00000
3:PM-14:AM   1.2933333 -1.44919 4.03586 0.99612
4:PM-14:AM   0.1666667 -2.57586 2.90919 1.00000
5:PM-14:AM   0.8333333 -1.90919 3.57586 1.00000
6:PM-14:AM   0.4433333 -2.29919 3.18586 1.00000
7:PM-14:AM   0.7300000 -2.01252 3.47252 1.00000
8:PM-14:AM   0.4233333 -2.31919 3.16586 1.00000
9:PM-14:AM   0.7500000 -1.99252 3.49252 1.00000
10:PM-14:AM  0.7900000 -1.95252 3.53252 1.00000
11:PM-14:AM  0.2166667 -2.52586 2.95919 1.00000
12:PM-14:AM  0.0966667 -2.64586 2.83919 1.00000
13:PM-14:AM  1.0000000 -1.74252 3.74252 0.99998
14:PM-14:AM  0.2800000 -2.46252 3.02252 1.00000
15:PM-14:AM  0.6133333 -2.12919 3.35586 1.00000
16:PM-14:AM  0.0133333 -2.72919 2.75586 1.00000
17:PM-14:AM -0.3433333 -3.08586 2.39919 1.00000
18:PM-14:AM  0.2933333 -2.44919 3.03586 1.00000
19:PM-14:AM -0.2733333 -3.01586 2.46919 1.00000
20:PM-14:AM  0.9333333 -1.80919 3.67586 1.00000
16:AM-15:AM  0.8666667 -1.87586 3.60919 1.00000
17:AM-15:AM  1.0866667 -1.65586 3.82919 0.99986
18:AM-15:AM  0.9400000 -1.80252 3.68252 0.99999
19:AM-15:AM  1.2900000 -1.45252 4.03252 0.99629
20:AM-15:AM  1.1200000 -1.94623 4.18623 0.99998
1:PM-15:AM   1.8900000 -0.85252 4.63252 0.69123
2:PM-15:AM   1.1233333 -1.61919 3.86586 0.99972
3:PM-15:AM   1.6400000 -1.10252 4.38252 0.90560
4:PM-15:AM   0.5133333 -2.22919 3.25586 1.00000
5:PM-15:AM   1.1800000 -1.56252 3.92252 0.99925
6:PM-15:AM   0.7900000 -1.95252 3.53252 1.00000
7:PM-15:AM   1.0766667 -1.66586 3.81919 0.99988
8:PM-15:AM   0.7700000 -1.97252 3.51252 1.00000
9:PM-15:AM   1.0966667 -1.64586 3.83919 0.99983
10:PM-15:AM  1.1366667 -1.60586 3.87919 0.99964
11:PM-15:AM  0.5633333 -2.17919 3.30586 1.00000
12:PM-15:AM  0.4433333 -2.29919 3.18586 1.00000
13:PM-15:AM  1.3466667 -1.39586 4.08919 0.99256
14:PM-15:AM  0.6266667 -2.11586 3.36919 1.00000
15:PM-15:AM  0.9600000 -1.78252 3.70252 0.99999
16:PM-15:AM  0.3600000 -2.38252 3.10252 1.00000
17:PM-15:AM  0.0033333 -2.73919 2.74586 1.00000
18:PM-15:AM  0.6400000 -2.10252 3.38252 1.00000
19:PM-15:AM  0.0733333 -2.66919 2.81586 1.00000
20:PM-15:AM  1.2800000 -1.46252 4.02252 0.99674
17:AM-16:AM  0.2200000 -2.52252 2.96252 1.00000
18:AM-16:AM  0.0733333 -2.66919 2.81586 1.00000
19:AM-16:AM  0.4233333 -2.31919 3.16586 1.00000
20:AM-16:AM  0.2533333 -2.81290 3.31957 1.00000
1:PM-16:AM   1.0233333 -1.71919 3.76586 0.99996
2:PM-16:AM   0.2566667 -2.48586 2.99919 1.00000
3:PM-16:AM   0.7733333 -1.96919 3.51586 1.00000
4:PM-16:AM  -0.3533333 -3.09586 2.38919 1.00000
5:PM-16:AM   0.3133333 -2.42919 3.05586 1.00000
6:PM-16:AM  -0.0766667 -2.81919 2.66586 1.00000
7:PM-16:AM   0.2100000 -2.53252 2.95252 1.00000
8:PM-16:AM  -0.0966667 -2.83919 2.64586 1.00000
9:PM-16:AM   0.2300000 -2.51252 2.97252 1.00000
10:PM-16:AM  0.2700000 -2.47252 3.01252 1.00000
11:PM-16:AM -0.3033333 -3.04586 2.43919 1.00000
12:PM-16:AM -0.4233333 -3.16586 2.31919 1.00000
13:PM-16:AM  0.4800000 -2.26252 3.22252 1.00000
14:PM-16:AM -0.2400000 -2.98252 2.50252 1.00000
15:PM-16:AM  0.0933333 -2.64919 2.83586 1.00000
16:PM-16:AM -0.5066667 -3.24919 2.23586 1.00000
17:PM-16:AM -0.8633333 -3.60586 1.87919 1.00000
18:PM-16:AM -0.2266667 -2.96919 2.51586 1.00000
19:PM-16:AM -0.7933333 -3.53586 1.94919 1.00000
20:PM-16:AM  0.4133333 -2.32919 3.15586 1.00000
18:AM-17:AM -0.1466667 -2.88919 2.59586 1.00000
19:AM-17:AM  0.2033333 -2.53919 2.94586 1.00000
20:AM-17:AM  0.0333333 -3.03290 3.09957 1.00000
1:PM-17:AM   0.8033333 -1.93919 3.54586 1.00000
2:PM-17:AM   0.0366667 -2.70586 2.77919 1.00000
3:PM-17:AM   0.5533333 -2.18919 3.29586 1.00000
4:PM-17:AM  -0.5733333 -3.31586 2.16919 1.00000
5:PM-17:AM   0.0933333 -2.64919 2.83586 1.00000
6:PM-17:AM  -0.2966667 -3.03919 2.44586 1.00000
7:PM-17:AM  -0.0100000 -2.75252 2.73252 1.00000
8:PM-17:AM  -0.3166667 -3.05919 2.42586 1.00000
9:PM-17:AM   0.0100000 -2.73252 2.75252 1.00000
10:PM-17:AM  0.0500000 -2.69252 2.79252 1.00000
11:PM-17:AM -0.5233333 -3.26586 2.21919 1.00000
12:PM-17:AM -0.6433333 -3.38586 2.09919 1.00000
13:PM-17:AM  0.2600000 -2.48252 3.00252 1.00000
14:PM-17:AM -0.4600000 -3.20252 2.28252 1.00000
15:PM-17:AM -0.1266667 -2.86919 2.61586 1.00000
16:PM-17:AM -0.7266667 -3.46919 2.01586 1.00000
17:PM-17:AM -1.0833333 -3.82586 1.65919 0.99987
18:PM-17:AM -0.4466667 -3.18919 2.29586 1.00000
19:PM-17:AM -1.0133333 -3.75586 1.72919 0.99997
20:PM-17:AM  0.1933333 -2.54919 2.93586 1.00000
19:AM-18:AM  0.3500000 -2.39252 3.09252 1.00000
20:AM-18:AM  0.1800000 -2.88623 3.24623 1.00000
1:PM-18:AM   0.9500000 -1.79252 3.69252 0.99999
2:PM-18:AM   0.1833333 -2.55919 2.92586 1.00000
3:PM-18:AM   0.7000000 -2.04252 3.44252 1.00000
4:PM-18:AM  -0.4266667 -3.16919 2.31586 1.00000
5:PM-18:AM   0.2400000 -2.50252 2.98252 1.00000
6:PM-18:AM  -0.1500000 -2.89252 2.59252 1.00000
7:PM-18:AM   0.1366667 -2.60586 2.87919 1.00000
8:PM-18:AM  -0.1700000 -2.91252 2.57252 1.00000
9:PM-18:AM   0.1566667 -2.58586 2.89919 1.00000
10:PM-18:AM  0.1966667 -2.54586 2.93919 1.00000
11:PM-18:AM -0.3766667 -3.11919 2.36586 1.00000
12:PM-18:AM -0.4966667 -3.23919 2.24586 1.00000
13:PM-18:AM  0.4066667 -2.33586 3.14919 1.00000
14:PM-18:AM -0.3133333 -3.05586 2.42919 1.00000
15:PM-18:AM  0.0200000 -2.72252 2.76252 1.00000
16:PM-18:AM -0.5800000 -3.32252 2.16252 1.00000
17:PM-18:AM -0.9366667 -3.67919 1.80586 1.00000
18:PM-18:AM -0.3000000 -3.04252 2.44252 1.00000
19:PM-18:AM -0.8666667 -3.60919 1.87586 1.00000
20:PM-18:AM  0.3400000 -2.40252 3.08252 1.00000
20:AM-19:AM -0.1700000 -3.23623 2.89623 1.00000
1:PM-19:AM   0.6000000 -2.14252 3.34252 1.00000
2:PM-19:AM  -0.1666667 -2.90919 2.57586 1.00000
3:PM-19:AM   0.3500000 -2.39252 3.09252 1.00000
4:PM-19:AM  -0.7766667 -3.51919 1.96586 1.00000
5:PM-19:AM  -0.1100000 -2.85252 2.63252 1.00000
6:PM-19:AM  -0.5000000 -3.24252 2.24252 1.00000
7:PM-19:AM  -0.2133333 -2.95586 2.52919 1.00000
8:PM-19:AM  -0.5200000 -3.26252 2.22252 1.00000
9:PM-19:AM  -0.1933333 -2.93586 2.54919 1.00000
10:PM-19:AM -0.1533333 -2.89586 2.58919 1.00000
11:PM-19:AM -0.7266667 -3.46919 2.01586 1.00000
12:PM-19:AM -0.8466667 -3.58919 1.89586 1.00000
13:PM-19:AM  0.0566667 -2.68586 2.79919 1.00000
14:PM-19:AM -0.6633333 -3.40586 2.07919 1.00000
15:PM-19:AM -0.3300000 -3.07252 2.41252 1.00000
16:PM-19:AM -0.9300000 -3.67252 1.81252 1.00000
17:PM-19:AM -1.2866667 -4.02919 1.45586 0.99645
18:PM-19:AM -0.6500000 -3.39252 2.09252 1.00000
19:PM-19:AM -1.2166667 -3.95919 1.52586 0.99867
20:PM-19:AM -0.0100000 -2.75252 2.73252 1.00000
1:PM-20:AM   0.7700000 -2.29623 3.83623 1.00000
2:PM-20:AM   0.0033333 -3.06290 3.06957 1.00000
3:PM-20:AM   0.5200000 -2.54623 3.58623 1.00000
4:PM-20:AM  -0.6066667 -3.67290 2.45957 1.00000
5:PM-20:AM   0.0600000 -3.00623 3.12623 1.00000
6:PM-20:AM  -0.3300000 -3.39623 2.73623 1.00000
7:PM-20:AM  -0.0433333 -3.10957 3.02290 1.00000
8:PM-20:AM  -0.3500000 -3.41623 2.71623 1.00000
9:PM-20:AM  -0.0233333 -3.08957 3.04290 1.00000
10:PM-20:AM  0.0166667 -3.04957 3.08290 1.00000
11:PM-20:AM -0.5566667 -3.62290 2.50957 1.00000
12:PM-20:AM -0.6766667 -3.74290 2.38957 1.00000
13:PM-20:AM  0.2266667 -2.83957 3.29290 1.00000
14:PM-20:AM -0.4933333 -3.55957 2.57290 1.00000
15:PM-20:AM -0.1600000 -3.22623 2.90623 1.00000
16:PM-20:AM -0.7600000 -3.82623 2.30623 1.00000
17:PM-20:AM -1.1166667 -4.18290 1.94957 0.99998
18:PM-20:AM -0.4800000 -3.54623 2.58623 1.00000
19:PM-20:AM -1.0466667 -4.11290 2.01957 1.00000
20:PM-20:AM  0.1600000 -2.90623 3.22623 1.00000
2:PM-1:PM   -0.7666667 -3.50919 1.97586 1.00000
3:PM-1:PM   -0.2500000 -2.99252 2.49252 1.00000
4:PM-1:PM   -1.3766667 -4.11919 1.36586 0.98958
5:PM-1:PM   -0.7100000 -3.45252 2.03252 1.00000
6:PM-1:PM   -1.1000000 -3.84252 1.64252 0.99982
7:PM-1:PM   -0.8133333 -3.55586 1.92919 1.00000
8:PM-1:PM   -1.1200000 -3.86252 1.62252 0.99973
9:PM-1:PM   -0.7933333 -3.53586 1.94919 1.00000
10:PM-1:PM  -0.7533333 -3.49586 1.98919 1.00000
11:PM-1:PM  -1.3266667 -4.06919 1.41586 0.99413
12:PM-1:PM  -1.4466667 -4.18919 1.29586 0.97882
13:PM-1:PM  -0.5433333 -3.28586 2.19919 1.00000
14:PM-1:PM  -1.2633333 -4.00586 1.47919 0.99740
15:PM-1:PM  -0.9300000 -3.67252 1.81252 1.00000
16:PM-1:PM  -1.5300000 -4.27252 1.21252 0.95647
17:PM-1:PM  -1.8866667 -4.62919 0.85586 0.69480
18:PM-1:PM  -1.2500000 -3.99252 1.49252 0.99784
19:PM-1:PM  -1.8166667 -4.55919 0.92586 0.76637
20:PM-1:PM  -0.6100000 -3.35252 2.13252 1.00000
3:PM-2:PM    0.5166667 -2.22586 3.25919 1.00000
4:PM-2:PM   -0.6100000 -3.35252 2.13252 1.00000
5:PM-2:PM    0.0566667 -2.68586 2.79919 1.00000
6:PM-2:PM   -0.3333333 -3.07586 2.40919 1.00000
7:PM-2:PM   -0.0466667 -2.78919 2.69586 1.00000
8:PM-2:PM   -0.3533333 -3.09586 2.38919 1.00000
9:PM-2:PM   -0.0266667 -2.76919 2.71586 1.00000
10:PM-2:PM   0.0133333 -2.72919 2.75586 1.00000
11:PM-2:PM  -0.5600000 -3.30252 2.18252 1.00000
12:PM-2:PM  -0.6800000 -3.42252 2.06252 1.00000
13:PM-2:PM   0.2233333 -2.51919 2.96586 1.00000
14:PM-2:PM  -0.4966667 -3.23919 2.24586 1.00000
15:PM-2:PM  -0.1633333 -2.90586 2.57919 1.00000
16:PM-2:PM  -0.7633333 -3.50586 1.97919 1.00000
17:PM-2:PM  -1.1200000 -3.86252 1.62252 0.99973
18:PM-2:PM  -0.4833333 -3.22586 2.25919 1.00000
19:PM-2:PM  -1.0500000 -3.79252 1.69252 0.99993
20:PM-2:PM   0.1566667 -2.58586 2.89919 1.00000
4:PM-3:PM   -1.1266667 -3.86919 1.61586 0.99970
5:PM-3:PM   -0.4600000 -3.20252 2.28252 1.00000
6:PM-3:PM   -0.8500000 -3.59252 1.89252 1.00000
7:PM-3:PM   -0.5633333 -3.30586 2.17919 1.00000
8:PM-3:PM   -0.8700000 -3.61252 1.87252 1.00000
9:PM-3:PM   -0.5433333 -3.28586 2.19919 1.00000
10:PM-3:PM  -0.5033333 -3.24586 2.23919 1.00000
11:PM-3:PM  -1.0766667 -3.81919 1.66586 0.99988
12:PM-3:PM  -1.1966667 -3.93919 1.54586 0.99902
13:PM-3:PM  -0.2933333 -3.03586 2.44919 1.00000
14:PM-3:PM  -1.0133333 -3.75586 1.72919 0.99997
15:PM-3:PM  -0.6800000 -3.42252 2.06252 1.00000
16:PM-3:PM  -1.2800000 -4.02252 1.46252 0.99674
17:PM-3:PM  -1.6366667 -4.37919 1.10586 0.90755
18:PM-3:PM  -1.0000000 -3.74252 1.74252 0.99998
19:PM-3:PM  -1.5666667 -4.30919 1.17586 0.94247
20:PM-3:PM  -0.3600000 -3.10252 2.38252 1.00000
5:PM-4:PM    0.6666667 -2.07586 3.40919 1.00000
6:PM-4:PM    0.2766667 -2.46586 3.01919 1.00000
7:PM-4:PM    0.5633333 -2.17919 3.30586 1.00000
8:PM-4:PM    0.2566667 -2.48586 2.99919 1.00000
9:PM-4:PM    0.5833333 -2.15919 3.32586 1.00000
10:PM-4:PM   0.6233333 -2.11919 3.36586 1.00000
11:PM-4:PM   0.0500000 -2.69252 2.79252 1.00000
12:PM-4:PM  -0.0700000 -2.81252 2.67252 1.00000
13:PM-4:PM   0.8333333 -1.90919 3.57586 1.00000
14:PM-4:PM   0.1133333 -2.62919 2.85586 1.00000
15:PM-4:PM   0.4466667 -2.29586 3.18919 1.00000
16:PM-4:PM  -0.1533333 -2.89586 2.58919 1.00000
17:PM-4:PM  -0.5100000 -3.25252 2.23252 1.00000
18:PM-4:PM   0.1266667 -2.61586 2.86919 1.00000
19:PM-4:PM  -0.4400000 -3.18252 2.30252 1.00000
20:PM-4:PM   0.7666667 -1.97586 3.50919 1.00000
6:PM-5:PM   -0.3900000 -3.13252 2.35252 1.00000
7:PM-5:PM   -0.1033333 -2.84586 2.63919 1.00000
8:PM-5:PM   -0.4100000 -3.15252 2.33252 1.00000
9:PM-5:PM   -0.0833333 -2.82586 2.65919 1.00000
10:PM-5:PM  -0.0433333 -2.78586 2.69919 1.00000
11:PM-5:PM  -0.6166667 -3.35919 2.12586 1.00000
12:PM-5:PM  -0.7366667 -3.47919 2.00586 1.00000
13:PM-5:PM   0.1666667 -2.57586 2.90919 1.00000
14:PM-5:PM  -0.5533333 -3.29586 2.18919 1.00000
15:PM-5:PM  -0.2200000 -2.96252 2.52252 1.00000
16:PM-5:PM  -0.8200000 -3.56252 1.92252 1.00000
17:PM-5:PM  -1.1766667 -3.91919 1.56586 0.99929
18:PM-5:PM  -0.5400000 -3.28252 2.20252 1.00000
19:PM-5:PM  -1.1066667 -3.84919 1.63586 0.99979
20:PM-5:PM   0.1000000 -2.64252 2.84252 1.00000
7:PM-6:PM    0.2866667 -2.45586 3.02919 1.00000
8:PM-6:PM   -0.0200000 -2.76252 2.72252 1.00000
9:PM-6:PM    0.3066667 -2.43586 3.04919 1.00000
10:PM-6:PM   0.3466667 -2.39586 3.08919 1.00000
11:PM-6:PM  -0.2266667 -2.96919 2.51586 1.00000
12:PM-6:PM  -0.3466667 -3.08919 2.39586 1.00000
13:PM-6:PM   0.5566667 -2.18586 3.29919 1.00000
14:PM-6:PM  -0.1633333 -2.90586 2.57919 1.00000
15:PM-6:PM   0.1700000 -2.57252 2.91252 1.00000
16:PM-6:PM  -0.4300000 -3.17252 2.31252 1.00000
17:PM-6:PM  -0.7866667 -3.52919 1.95586 1.00000
18:PM-6:PM  -0.1500000 -2.89252 2.59252 1.00000
19:PM-6:PM  -0.7166667 -3.45919 2.02586 1.00000
20:PM-6:PM   0.4900000 -2.25252 3.23252 1.00000
8:PM-7:PM   -0.3066667 -3.04919 2.43586 1.00000
9:PM-7:PM    0.0200000 -2.72252 2.76252 1.00000
10:PM-7:PM   0.0600000 -2.68252 2.80252 1.00000
11:PM-7:PM  -0.5133333 -3.25586 2.22919 1.00000
12:PM-7:PM  -0.6333333 -3.37586 2.10919 1.00000
13:PM-7:PM   0.2700000 -2.47252 3.01252 1.00000
14:PM-7:PM  -0.4500000 -3.19252 2.29252 1.00000
15:PM-7:PM  -0.1166667 -2.85919 2.62586 1.00000
16:PM-7:PM  -0.7166667 -3.45919 2.02586 1.00000
17:PM-7:PM  -1.0733333 -3.81586 1.66919 0.99989
18:PM-7:PM  -0.4366667 -3.17919 2.30586 1.00000
19:PM-7:PM  -1.0033333 -3.74586 1.73919 0.99998
20:PM-7:PM   0.2033333 -2.53919 2.94586 1.00000
9:PM-8:PM    0.3266667 -2.41586 3.06919 1.00000
10:PM-8:PM   0.3666667 -2.37586 3.10919 1.00000
11:PM-8:PM  -0.2066667 -2.94919 2.53586 1.00000
12:PM-8:PM  -0.3266667 -3.06919 2.41586 1.00000
13:PM-8:PM   0.5766667 -2.16586 3.31919 1.00000
14:PM-8:PM  -0.1433333 -2.88586 2.59919 1.00000
15:PM-8:PM   0.1900000 -2.55252 2.93252 1.00000
16:PM-8:PM  -0.4100000 -3.15252 2.33252 1.00000
17:PM-8:PM  -0.7666667 -3.50919 1.97586 1.00000
18:PM-8:PM  -0.1300000 -2.87252 2.61252 1.00000
19:PM-8:PM  -0.6966667 -3.43919 2.04586 1.00000
20:PM-8:PM   0.5100000 -2.23252 3.25252 1.00000
10:PM-9:PM   0.0400000 -2.70252 2.78252 1.00000
11:PM-9:PM  -0.5333333 -3.27586 2.20919 1.00000
12:PM-9:PM  -0.6533333 -3.39586 2.08919 1.00000
13:PM-9:PM   0.2500000 -2.49252 2.99252 1.00000
14:PM-9:PM  -0.4700000 -3.21252 2.27252 1.00000
15:PM-9:PM  -0.1366667 -2.87919 2.60586 1.00000
16:PM-9:PM  -0.7366667 -3.47919 2.00586 1.00000
17:PM-9:PM  -1.0933333 -3.83586 1.64919 0.99984
18:PM-9:PM  -0.4566667 -3.19919 2.28586 1.00000
19:PM-9:PM  -1.0233333 -3.76586 1.71919 0.99996
20:PM-9:PM   0.1833333 -2.55919 2.92586 1.00000
11:PM-10:PM -0.5733333 -3.31586 2.16919 1.00000
12:PM-10:PM -0.6933333 -3.43586 2.04919 1.00000
13:PM-10:PM  0.2100000 -2.53252 2.95252 1.00000
14:PM-10:PM -0.5100000 -3.25252 2.23252 1.00000
15:PM-10:PM -0.1766667 -2.91919 2.56586 1.00000
16:PM-10:PM -0.7766667 -3.51919 1.96586 1.00000
17:PM-10:PM -1.1333333 -3.87586 1.60919 0.99966
18:PM-10:PM -0.4966667 -3.23919 2.24586 1.00000
19:PM-10:PM -1.0633333 -3.80586 1.67919 0.99991
20:PM-10:PM  0.1433333 -2.59919 2.88586 1.00000
12:PM-11:PM -0.1200000 -2.86252 2.62252 1.00000
13:PM-11:PM  0.7833333 -1.95919 3.52586 1.00000
14:PM-11:PM  0.0633333 -2.67919 2.80586 1.00000
15:PM-11:PM  0.3966667 -2.34586 3.13919 1.00000
16:PM-11:PM -0.2033333 -2.94586 2.53919 1.00000
17:PM-11:PM -0.5600000 -3.30252 2.18252 1.00000
18:PM-11:PM  0.0766667 -2.66586 2.81919 1.00000
19:PM-11:PM -0.4900000 -3.23252 2.25252 1.00000
20:PM-11:PM  0.7166667 -2.02586 3.45919 1.00000
13:PM-12:PM  0.9033333 -1.83919 3.64586 1.00000
14:PM-12:PM  0.1833333 -2.55919 2.92586 1.00000
15:PM-12:PM  0.5166667 -2.22586 3.25919 1.00000
16:PM-12:PM -0.0833333 -2.82586 2.65919 1.00000
17:PM-12:PM -0.4400000 -3.18252 2.30252 1.00000
18:PM-12:PM  0.1966667 -2.54586 2.93919 1.00000
19:PM-12:PM -0.3700000 -3.11252 2.37252 1.00000
20:PM-12:PM  0.8366667 -1.90586 3.57919 1.00000
14:PM-13:PM -0.7200000 -3.46252 2.02252 1.00000
15:PM-13:PM -0.3866667 -3.12919 2.35586 1.00000
16:PM-13:PM -0.9866667 -3.72919 1.75586 0.99998
17:PM-13:PM -1.3433333 -4.08586 1.39919 0.99284
18:PM-13:PM -0.7066667 -3.44919 2.03586 1.00000
19:PM-13:PM -1.2733333 -4.01586 1.46919 0.99702
20:PM-13:PM -0.0666667 -2.80919 2.67586 1.00000
15:PM-14:PM  0.3333333 -2.40919 3.07586 1.00000
16:PM-14:PM -0.2666667 -3.00919 2.47586 1.00000
17:PM-14:PM -0.6233333 -3.36586 2.11919 1.00000
18:PM-14:PM  0.0133333 -2.72919 2.75586 1.00000
19:PM-14:PM -0.5533333 -3.29586 2.18919 1.00000
20:PM-14:PM  0.6533333 -2.08919 3.39586 1.00000
16:PM-15:PM -0.6000000 -3.34252 2.14252 1.00000
17:PM-15:PM -0.9566667 -3.69919 1.78586 0.99999
18:PM-15:PM -0.3200000 -3.06252 2.42252 1.00000
19:PM-15:PM -0.8866667 -3.62919 1.85586 1.00000
20:PM-15:PM  0.3200000 -2.42252 3.06252 1.00000
17:PM-16:PM -0.3566667 -3.09919 2.38586 1.00000
18:PM-16:PM  0.2800000 -2.46252 3.02252 1.00000
19:PM-16:PM -0.2866667 -3.02919 2.45586 1.00000
20:PM-16:PM  0.9200000 -1.82252 3.66252 1.00000
18:PM-17:PM  0.6366667 -2.10586 3.37919 1.00000
19:PM-17:PM  0.0700000 -2.67252 2.81252 1.00000
20:PM-17:PM  1.2766667 -1.46586 4.01919 0.99689
19:PM-18:PM -0.5666667 -3.30919 2.17586 1.00000
20:PM-18:PM  0.6400000 -2.10252 3.38252 1.00000
20:PM-19:PM  1.2066667 -1.53586 3.94919 0.99886</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    99% family-wise confidence level

Fit: aov(formula = Ct ~ Day + noon + Day:noon, data = data)

$Day
            diff      lwr     upr   p adj
2-1   -0.2883333 -2.29705 1.72039 1.00000
3-1   -0.1916667 -2.20039 1.81705 1.00000
4-1   -0.6716667 -2.68039 1.33705 0.99700
5-1   -0.1566667 -2.16539 1.85205 1.00000
6-1   -0.3200000 -2.32872 1.68872 1.00000
7-1   -0.3016667 -2.31039 1.70705 1.00000
8-1   -0.2050000 -2.21372 1.80372 1.00000
9-1    0.4016667 -1.60705 2.41039 1.00000
10-1  -0.5966667 -2.60539 1.41205 0.99934
11-1   0.0866667 -1.92205 2.09539 1.00000
12-1  -0.9583333 -2.96705 1.05039 0.89330
13-1  -0.1633333 -2.17205 1.84539 1.00000
14-1  -0.8700000 -2.87872 1.13872 0.95243
15-1  -0.8766667 -2.88539 1.13205 0.94905
16-1  -0.7433333 -2.75205 1.26539 0.99024
17-1  -0.8116667 -2.82039 1.19705 0.97539
18-1  -0.5666667 -2.57539 1.44205 0.99968
19-1  -0.6750000 -2.68372 1.33372 0.99682
20-1  -0.1406667 -2.24743 1.96610 1.00000
3-2    0.0966667 -1.91205 2.10539 1.00000
4-2   -0.3833333 -2.39205 1.62539 1.00000
5-2    0.1316667 -1.87705 2.14039 1.00000
6-2   -0.0316667 -2.04039 1.97705 1.00000
7-2   -0.0133333 -2.02205 1.99539 1.00000
8-2    0.0833333 -1.92539 2.09205 1.00000
9-2    0.6900000 -1.31872 2.69872 0.99585
10-2  -0.3083333 -2.31705 1.70039 1.00000
11-2   0.3750000 -1.63372 2.38372 1.00000
12-2  -0.6700000 -2.67872 1.33872 0.99709
13-2   0.1250000 -1.88372 2.13372 1.00000
14-2  -0.5816667 -2.59039 1.42705 0.99953
15-2  -0.5883333 -2.59705 1.42039 0.99946
16-2  -0.4550000 -2.46372 1.55372 0.99999
17-2  -0.5233333 -2.53205 1.48539 0.99990
18-2  -0.2783333 -2.28705 1.73039 1.00000
19-2  -0.3866667 -2.39539 1.62205 1.00000
20-2   0.1476667 -1.95910 2.25443 1.00000
4-3   -0.4800000 -2.48872 1.52872 0.99997
5-3    0.0350000 -1.97372 2.04372 1.00000
6-3   -0.1283333 -2.13705 1.88039 1.00000
7-3   -0.1100000 -2.11872 1.89872 1.00000
8-3   -0.0133333 -2.02205 1.99539 1.00000
9-3    0.5933333 -1.41539 2.60205 0.99939
10-3  -0.4050000 -2.41372 1.60372 1.00000
11-3   0.2783333 -1.73039 2.28705 1.00000
12-3  -0.7666667 -2.77539 1.24205 0.98634
13-3   0.0283333 -1.98039 2.03705 1.00000
14-3  -0.6783333 -2.68705 1.33039 0.99662
15-3  -0.6850000 -2.69372 1.32372 0.99620
16-3  -0.5516667 -2.56039 1.45705 0.99978
17-3  -0.6200000 -2.62872 1.38872 0.99891
18-3  -0.3750000 -2.38372 1.63372 1.00000
19-3  -0.4833333 -2.49205 1.52539 0.99997
20-3   0.0510000 -2.05576 2.15776 1.00000
5-4    0.5150000 -1.49372 2.52372 0.99992
6-4    0.3516667 -1.65705 2.36039 1.00000
7-4    0.3700000 -1.63872 2.37872 1.00000
8-4    0.4666667 -1.54205 2.47539 0.99998
9-4    1.0733333 -0.93539 3.08205 0.76824
10-4   0.0750000 -1.93372 2.08372 1.00000
11-4   0.7583333 -1.25039 2.76705 0.98785
12-4  -0.2866667 -2.29539 1.72205 1.00000
13-4   0.5083333 -1.50039 2.51705 0.99993
14-4  -0.1983333 -2.20705 1.81039 1.00000
15-4  -0.2050000 -2.21372 1.80372 1.00000
16-4  -0.0716667 -2.08039 1.93705 1.00000
17-4  -0.1400000 -2.14872 1.86872 1.00000
18-4   0.1050000 -1.90372 2.11372 1.00000
19-4  -0.0033333 -2.01205 2.00539 1.00000
20-4   0.5310000 -1.57576 2.63776 0.99994
6-5   -0.1633333 -2.17205 1.84539 1.00000
7-5   -0.1450000 -2.15372 1.86372 1.00000
8-5   -0.0483333 -2.05705 1.96039 1.00000
9-5    0.5583333 -1.45039 2.56705 0.99974
10-5  -0.4400000 -2.44872 1.56872 0.99999
11-5   0.2433333 -1.76539 2.25205 1.00000
12-5  -0.8016667 -2.81039 1.20705 0.97827
13-5  -0.0066667 -2.01539 2.00205 1.00000
14-5  -0.7133333 -2.72205 1.29539 0.99387
15-5  -0.7200000 -2.72872 1.28872 0.99318
16-5  -0.5866667 -2.59539 1.42205 0.99948
17-5  -0.6550000 -2.66372 1.35372 0.99780
18-5  -0.4100000 -2.41872 1.59872 1.00000
19-5  -0.5183333 -2.52705 1.49039 0.99991
20-5   0.0160000 -2.09076 2.12276 1.00000
7-6    0.0183333 -1.99039 2.02705 1.00000
8-6    0.1150000 -1.89372 2.12372 1.00000
9-6    0.7216667 -1.28705 2.73039 0.99300
10-6  -0.2766667 -2.28539 1.73205 1.00000
11-6   0.4066667 -1.60205 2.41539 1.00000
12-6  -0.6383333 -2.64705 1.37039 0.99841
13-6   0.1566667 -1.85205 2.16539 1.00000
14-6  -0.5500000 -2.55872 1.45872 0.99979
15-6  -0.5566667 -2.56539 1.45205 0.99975
16-6  -0.4233333 -2.43205 1.58539 1.00000
17-6  -0.4916667 -2.50039 1.51705 0.99996
18-6  -0.2466667 -2.25539 1.76205 1.00000
19-6  -0.3550000 -2.36372 1.65372 1.00000
20-6   0.1793333 -1.92743 2.28610 1.00000
8-7    0.0966667 -1.91205 2.10539 1.00000
9-7    0.7033333 -1.30539 2.71205 0.99480
10-7  -0.2950000 -2.30372 1.71372 1.00000
11-7   0.3883333 -1.62039 2.39705 1.00000
12-7  -0.6566667 -2.66539 1.35205 0.99773
13-7   0.1383333 -1.87039 2.14705 1.00000
14-7  -0.5683333 -2.57705 1.44039 0.99966
15-7  -0.5750000 -2.58372 1.43372 0.99960
16-7  -0.4416667 -2.45039 1.56705 0.99999
17-7  -0.5100000 -2.51872 1.49872 0.99993
18-7  -0.2650000 -2.27372 1.74372 1.00000
19-7  -0.3733333 -2.38205 1.63539 1.00000
20-7   0.1610000 -1.94576 2.26776 1.00000
9-8    0.6066667 -1.40205 2.61539 0.99918
10-8  -0.3916667 -2.40039 1.61705 1.00000
11-8   0.2916667 -1.71705 2.30039 1.00000
12-8  -0.7533333 -2.76205 1.25539 0.98869
13-8   0.0416667 -1.96705 2.05039 1.00000
14-8  -0.6650000 -2.67372 1.34372 0.99735
15-8  -0.6716667 -2.68039 1.33705 0.99700
16-8  -0.5383333 -2.54705 1.47039 0.99984
17-8  -0.6066667 -2.61539 1.40205 0.99918
18-8  -0.3616667 -2.37039 1.64705 1.00000
19-8  -0.4700000 -2.47872 1.53872 0.99998
20-8   0.0643333 -2.04243 2.17110 1.00000
10-9  -0.9983333 -3.00705 1.01039 0.85576
11-9  -0.3150000 -2.32372 1.69372 1.00000
12-9  -1.3600000 -3.36872 0.64872 0.35269
13-9  -0.5650000 -2.57372 1.44372 0.99969
14-9  -1.2716667 -3.28039 0.73705 0.47719
15-9  -1.2783333 -3.28705 0.73039 0.46731
16-9  -1.1450000 -3.15372 0.86372 0.66832
17-9  -1.2133333 -3.22205 0.79539 0.56535
18-9  -0.9683333 -2.97705 1.04039 0.88455
19-9  -1.0766667 -3.08539 0.93205 0.76389
20-9  -0.5423333 -2.64910 1.56443 0.99991
11-10  0.6833333 -1.32539 2.69205 0.99631
12-10 -0.3616667 -2.37039 1.64705 1.00000
13-10  0.4333333 -1.57539 2.44205 0.99999
14-10 -0.2733333 -2.28205 1.73539 1.00000
15-10 -0.2800000 -2.28872 1.72872 1.00000
16-10 -0.1466667 -2.15539 1.86205 1.00000
17-10 -0.2150000 -2.22372 1.79372 1.00000
18-10  0.0300000 -1.97872 2.03872 1.00000
19-10 -0.0783333 -2.08705 1.93039 1.00000
20-10  0.4560000 -1.65076 2.56276 0.99999
12-11 -1.0450000 -3.05372 0.96372 0.80373
13-11 -0.2500000 -2.25872 1.75872 1.00000
14-11 -0.9566667 -2.96539 1.05205 0.89472
15-11 -0.9633333 -2.97205 1.04539 0.88898
16-11 -0.8300000 -2.83872 1.17872 0.96936
17-11 -0.8983333 -2.90705 1.11039 0.93692
18-11 -0.6533333 -2.66205 1.35539 0.99787
19-11 -0.7616667 -2.77039 1.24705 0.98726
20-11 -0.2273333 -2.33410 1.87943 1.00000
13-12  0.7950000 -1.21372 2.80372 0.98004
14-12  0.0883333 -1.92039 2.09705 1.00000
15-12  0.0816667 -1.92705 2.09039 1.00000
16-12  0.2150000 -1.79372 2.22372 1.00000
17-12  0.1466667 -1.86205 2.15539 1.00000
18-12  0.3916667 -1.61705 2.40039 1.00000
19-12  0.2833333 -1.72539 2.29205 1.00000
20-12  0.8176667 -1.28910 2.92443 0.98369
14-13 -0.7066667 -2.71539 1.30205 0.99450
15-13 -0.7133333 -2.72205 1.29539 0.99387
16-13 -0.5800000 -2.58872 1.42872 0.99955
17-13 -0.6483333 -2.65705 1.36039 0.99807
18-13 -0.4033333 -2.41205 1.60539 1.00000
19-13 -0.5116667 -2.52039 1.49705 0.99992
20-13  0.0226667 -2.08410 2.12943 1.00000
15-14 -0.0066667 -2.01539 2.00205 1.00000
16-14  0.1266667 -1.88205 2.13539 1.00000
17-14  0.0583333 -1.95039 2.06705 1.00000
18-14  0.3033333 -1.70539 2.31205 1.00000
19-14  0.1950000 -1.81372 2.20372 1.00000
20-14  0.7293333 -1.37743 2.83610 0.99545
16-15  0.1333333 -1.87539 2.14205 1.00000
17-15  0.0650000 -1.94372 2.07372 1.00000
18-15  0.3100000 -1.69872 2.31872 1.00000
19-15  0.2016667 -1.80705 2.21039 1.00000
20-15  0.7360000 -1.37076 2.84276 0.99493
17-16 -0.0683333 -2.07705 1.94039 1.00000
18-16  0.1766667 -1.83205 2.18539 1.00000
19-16  0.0683333 -1.94039 2.07705 1.00000
20-16  0.6026667 -1.50410 2.70943 0.99961
18-17  0.2450000 -1.76372 2.25372 1.00000
19-17  0.1366667 -1.87205 2.14539 1.00000
20-17  0.6710000 -1.43576 2.77776 0.99837
19-18 -0.1083333 -2.11705 1.90039 1.00000
20-18  0.4260000 -1.68076 2.53276 1.00000
20-19  0.5343333 -1.57243 2.64110 0.99993</code></pre>
</div>
</div>
<p>유의한 패턴 없음 Tukey 검정 결과 (보통 유의할때 함) 테이블 도 유의한 수치가 없음</p>
</section>
</section>
</div>
<div id="English" class="tab-pane fade" role="tabpanel" aria-labelledby="English-tab">
<p>## Terms</p>
<ul>
<li>pairwise comparison: A hypothesis test (e.g., of means) between two groups among multiple groups.</li>
<li>obmnibus set: A single hypothesis test of the overall variance among multiple group means.</li>
<li>decomposition of variance : Separation of components contributing to an individual value (e.g., from the overall average, from a treatment mean, and from a residual error).</li>
<li>F-test</li>
<li>F statistic: A standardized statistic that measures the extent to which differences among group means exceed what might be expected in a chance model.</li>
<li>sum of squares: deviations from some average value</li>
</ul>
</div>



</div></ul></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>