---
title: "WSL Install"
subtitle: WSL
description: |
  template
categories:
  - Engineering
author: Kwangmin Kim
date: 05/01/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
comments: 
  utterances: 
    repo: ./docs/comments
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

# Frequently Used Linux Commands

* `pwd` : (print working directory) 현재 디렉토리 경로 출력
* `ls` : (list) 현재 디렉토리의 파일 목록 출력
    * `ls -a` : -a 옵션은 숨겨진 파일 출력
    * `ls -l` : -l 자세한 정보 출력
    * `ls -al` :  숨김 파일 (.파일명) 까지 볼 수 있음
* `cd` : (change directory) 디렉토리 변경
    * `cd ..` : 상위 디렉토리로 이동
    * `cd ~` or `cd` : 홈 디렉토리로 이동
    * `cd /` : root(최상위) 디렉토리로 이동
* `mkdir` : (make directory) 디렉토리 생성
    * directory와 file의 구분은 `ls -al`에서 파일권한 column에서 맨앞이 file은 `-` directory는 `d`로 표시되어 있음
* `touch` : (touch) 새로운 파일 생성
* `rm` : (remove) 파일 삭제 (디렉토리 포함: 옵션 r, `rm -r`)
    * `rm -rf`: 강제 삭제
* `cp` : (copy) file 및 directory 복사
    * `cp file1-to-copy file2-name-to-be-copied` : `cp file1 file2`
    * `cp -r dir1-to-copy dir2-name-to-be-copied` : `cp dir1 dir2`
* `mv` : (move) 파일 이동 및 이름 변경
    * 파일 이동: `mv file1 dir1`. 이때 dir1은 existing directory
    * 파일명 변경: `mv file2 file3` file2를 file3로 renaming. 이때 file3은 non-existing file
* `tar` : (Tape ARchiver) 파일 및 디렉토리를 압축 (여러 directories 및 files을 하나의 file로 압축) 및 해제
    * 압축 : `tar cvf name.tar file-to-zip` $\rightarrow$ `tar cvf dir_1.tar dir_1`
    * 해제 : `tar xvf name.tar` $\rightarrow$ `tar xvf dir_1.tar`
* `cat` : 파일을 읽는 명령어
*  vi 편집기에서의 방향키
  * `j`: down, `k`:up, `h`:left, `l`:right
* file 편집
  * `i` : (insertion) 커서의 위치에서 `i` 누르면 편집 가능. 커서를 방향키로 편집할 위치까지 움직여서 `i` 누르면 insertion됨
  * `o`: cursor 바로 밑 한줄 개행하면서 편집권한 생김
* file 닫기
  * `ESC + :wq!`: 저장 후 exit
* 권한 부여
  * `chmod +x file_name`: file_name에 실행 권한 부여
* 라인 복제
  * `yy`: 복제하고 싶은 라인에 커서를 놓고 yy를 누르면 복제됨
* line number 보기
  * `se nu`
* 문서내 커서 이동
  * `G` : 문서 맨 밑으로 이동
:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>


# Go to Blog Content List

[Blog Content List](../../content_list.qmd)