---
title: Conditional Probability
subtitle: Conditional Probability
description: | 
  Probability for statistics, machine learning and deep learning. Studying conditional probability is fundamental to stochastic processes, reinforcement learning, and naive Bayes classification, so it's important to understand the concept.
categories:
  - Statistics
author: Kwangmin Kim
date: 02/05/2023
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}



## Conditional Probability

조건부 확률은 조건이 주어졌을 때 한 사건이 발생할 확률이며 하나의 사건이 다른 사건에 영향을 미쳐 그 확률값이 달라지는 것을 의미한다. 즉, 한 사건, B가 조건으로 주어지고 다른 사건A가 발생할 확률 $P(A|B)$ 가 사건 A가 발생할 확률 $P(A)$ 와 다르다는 것을 의미한다 ($P(A)\not=P(A|B)$).

예를 들어, 주사위를 던질 때 특정 주사위의 눈 (1~6)이 나올 확률은 **$\frac{1}{6}$ 으로 같다 (eqaully likely)라고 가정할 때** 주사위의 눈이 나올 수 있는 모든 집합 표본 공간 $S$ 에 대한 특정 주사위의 눈이 나오는 사건 $A$ 가 발생할 확률은 $\frac{n(A)}{n(S)}$ 와 같다. 다시 말해서, 조건부 확률은 2개 이상의 사건에 대해서 하나의 사건이 다른 사건이 발생할 확률에 영향을 미치는 개념을 말한다. 가장 간단한 2개의 사건 $A, B$ 에 대해서 살펴볼 때 조건부 확률은 다음과 (@eq-conditional_probability)과 같다.

::: {#def-conditional_probability}

If $A$ and $B$ are events in sample space $S$, and $P(B)>0$, then the conditional probability of $A$ given $B$, written $P(A|B)$, is
$$
P(A|B)=\frac{P(A\cap B)}{P(B)}
$$ {#eq-conditional_probability}

where $0 < P(B) \le 1$
:::
위의 정의에서 볼 수 있듯이, sample space $S$ 가 B로 update 되어 P(B|B)=1이 되고 사건 A의 outcome이 B에 관해서 조정된다. 

예를 들어, 사건 $A$ 는  주사위의 눈이 1이 나오는 사건, 사건 $B$ 는 주사위의 눈이 3 이하가 나오는 사건이라고 했을 때 사건 $A$ 가 사건 $B$ 의 부분 집합이므로 두 사건이 서로 독립이 아니다. 즉, $ A\cap B $ 사건에서 주사위의 눈이 1 나오는 경우 밖에 없다. 이렇게 사건 $B$ 가 주어졌을 때 혹은 $B$ 가 먼저 일어났을 때 1이 나올 확률은 달라지게 된다. 즉, $A$ 의 sample space = $\{1,2,3,4,5,6\}$ 이고 $A|B$ 의 sample space = $\{1,2,3\}$ 이 되기 때문에 $P(A) \not= P(A|B)$ 가 된다. 

좀 더 구체적으로 계산을 하게 되면, $P(A)=\frac{1}{6}, P(B)=\frac{3}{6}, P(A\cap B)=\frac{1}{6}$ 일 때, 

$$
P(A|B)=\frac{P(A\cap B)}{P(B)}=\frac{\frac{1}{6}}{\frac{3}{6}}=\frac{1}{3}
$$ 

인 것을 알 수 있다.

::: {#def-independence}

Independence 
$$
\begin{aligned}
P(A)&=P(A|B)\\
P(B)&=P(B|A)\\
\end{aligned}
$$ {#eq-independence}

A and B are independent.
:::

사건 A, B가 독립일 때 두 두사건이 동시에 발생할 확률은 $P(A \cap B)=P(A)P(B)=P(B)P(A)$ 이다. 반면에, 두 사건이 독립이 아니라면 @eq-conditional_probability 을 이용하여 $P(A \cap B)$ 는 $P(B|A)P(A)$ 또는 $P(A|B)P(B)$ 로 표현될 수 있다.독립일 때 동시에 발생할 확률에서 $P(A)$ 가 B를 조건으로 봤을 때 동시에 발생할 확률 $P(A|B)$ 로 바뀐 것을 볼 수 있다.

::: {#thm-multiplicativeRule}

Multiplicative Rule
A,B dependent
$$
\begin{aligned}
P(A\cap B)&=P(A)P(B|A)
\end{aligned}
$$

A,B independent
$$
\begin{aligned}
P(A\cap B)&=P(A)P(B)
\end{aligned}
$$ 

:::

::: {#thm-generalMultiplicativeRule}

Generalized multiplicative rule
$$

$$ 

:::

::: {#thm-totalProbabilityRule}

Total Probability Rule
$$

$$ 

:::


:::

</div>



## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)



