---
title: "Measures of Risk: Relative Risk & Odds Ratio"
subtitle: Measures of Association using Relative Risk & Odds Ratio
description: |
  By considering relative risk and odds ratio instead of solely relying on counts in a contingency table, you gain a more comprehensive understanding of the relationship between an exposure and an outcome. These measures provide a standardized way to quantify the association and assess the impact of exposure on the risk of the outcome. They facilitate comparisons between different groups or populations and help guide decision-making in areas such as public health interventions, clinical practice, and research studies.
categories:
  - Epidemiology
author: Kwangmin Kim
date: 05/23/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
comments: 
  utterances: 
    repo: ./docs/comments
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

Knowing the relative risk and odds ratio provides important insights beyond just looking at the counts in a contingency table. 

## Motivation

Relative Risk (RR) and Odds Ratio (OR) provides a more comprehensive understanding of the relationship between an exposure and an outcome by quantifying the association between the exposure and the outcome.

**Relative Risk(RR)**

* Measures the strength of association between an exposure and an outcome.
* Indicates the ratio of the risk of developing the outcome in the exposed group compared to the unexposed group.
* Helps determine the magnitude of the effect of an exposure on the outcome.
* Enables comparison of the risk between different groups or populations.
* Allows for assessing the impact of interventions or treatments on the risk of the outcome.

**Relative Risk(OR)**

* Estimates the odds of an event occurring in one group compared to another group.
* Widely used in case-control studies and logistic regression.
* Useful when the outcome is rare, as it approximates the relative risk.
* Can be used to assess the strength of association between an exposure and an outcome.
* Enables comparison of the odds between different groups or populations.

## Relative Risk

:::{#def-risk}
## Risk

The risk can be represented as:

$$
\begin{array}{c|c|c}
 & \text{Event} & \text{Non-Event} \\ \hline
\text{Exposed} & a & b \\
\text{Unexposed} & c & d \\
\end{array}
$$

The risk of the event occurring in the exposed group is given by:

$$
\text{Risk}_\text{exposed} = \frac{a}{a + b}
$$

Similarly, the risk of the event occurring in the unexposed group is given by:

$$
\text{Risk}_\text{unexposed} = \frac{c}{c + d}
$$
:::


### Properties

* Probability: Risk is a measure of the probability or likelihood of an event or outcome occurring. It quantifies the chance that an undesired event will happen.
* Magnitude: Risk can vary in terms of its magnitude, reflecting the potential impact or severity of the event. High-risk situations involve events with significant consequences, while low-risk situations involve events with minor consequences.
* Contextual Dependence: Risk is influenced by the specific context or domain under consideration. The same event may be perceived as higher or lower risk depending on the circumstances, individuals involved, and external factors.
* Subjectivity: Risk perception can be subjective, varying from person to person. Individuals may perceive and assess risk differently based on their experiences, knowledge, beliefs, and personal characteristics.
* Uncertainty: Risk assessment often involves dealing with uncertainties, as it is challenging to predict outcomes with absolute certainty. Uncertainty arises from limited information, variability, and potential unknown factors.
* Trade-offs: Risk often involves trade-offs, where accepting or managing one risk may introduce or mitigate another. Decision-makers may need to consider and weigh different risks against each other to make informed choices.
* Time Dependency: Risk can change over time. It may evolve due to external factors, interventions, or natural processes. Long-term risks may require considering trends, projections, and potential future scenarios.

### Interpretation

#### Risk in Exposed Group

$$
\text{Risk}_\text{exposed} = \frac{a}{a + b}
$$

This represents the proportion of individuals in the exposed group who experience the event.

* If the risk is low (close to 0), it indicates a lower likelihood of the event occurring in the exposed group.
* If the risk is high (close to 1), it suggests a higher likelihood of the event occurring in the exposed group.

#### Risk in Unexposed Group

$$
\text{Risk}_\text{exposed} = \frac{a}{a + b}
$$

This represents the proportion of individuals in the unexposed group who experience the event.

* If the risk is low (close to 0), it indicates a lower likelihood of the event occurring in the unexposed group.
* If the risk is high (close to 1), it suggests a higher likelihood of the event occurring in the unexposed group.

#### Comparing Risks

Compare the risks between the exposed and unexposed groups to assess the association between the exposure and the event.

* If the risk in the exposed group is significantly higher than the risk in the unexposed group, it suggests a positive association. The exposure may be a risk factor for the event.
* If the risk in the exposed group is significantly lower than the risk in the unexposed group, it suggests a negative association. The exposure may be protective against the event.
* If the risks are similar between the exposed and unexposed groups, it suggests no significant association between the exposure and the event.

:::{.callout-note}
Interpreting risk requires considering other factors such as study design, sample size, confidence intervals, and potential confounders. Additionally, the specific context and domain of the study should be taken into account when interpreting risk.

Remember to interpret risk in conjunction with other measures such as relative risk, odds ratio, and confidence intervals to gain a comprehensive understanding of the relationship between exposure and event occurrence.
:::

:::{#def-relative_risk}
## Relative Risk

the relative risk (RR) is calculated by dividing the risk in the exposed group by the risk in the unexposed group.

$$
\text{Relative Risk (RR)} = \frac{{\text{Risk in exposed group}}}{{\text{Risk in unexposed group}}}
$$

The relative risk (RR) can be calculated as the formula:
$$
\text{RR} = \frac{{\frac{a}{{a+b}}}}{{\frac{c}{{c+d}}}}
$$
:::

### Properties

* Comparison of Risks: Relative risk compares the risk of an outcome between two groups exposed to different levels of a factor or intervention. It provides a quantitative measure of the association between exposure and outcome.
* Interpretability: Relative risk is easily interpretable as a ratio of risks. An RR of 1 indicates no difference in risk between the exposed and unexposed groups. An RR greater than 1 suggests an increased risk associated with exposure, while an RR less than 1 indicates a decreased risk.
* Contextual Interpretation: The interpretation of relative risk depends on the specific context, exposure, outcome, and population under study. 
* Causality: Relative risk is a useful measure for assessing causal relationships between exposures and outcomes, although it does not establish causality alone. Additional evidence from other study designs and criteria for causality should be considered.
* Directionality: Relative risk indicates the direction of the association between exposure and outcome. An RR greater than 1 signifies a positive association, indicating that exposure increases the risk of the outcome. An RR less than 1 indicates a negative association, suggesting a decreased risk with exposure.
* Strength of Association: The magnitude of the relative risk reflects the strength of the association between exposure and outcome. 
* Confidence Interval: Relative risk is often reported with a confidence interval (CI) to quantify the uncertainty around the point estimate. 
* Temporality: Relative risk is typically measured in prospective or retrospective cohort studies, where exposure is assessed before the outcome occurrence. This temporal relationship supports the assessment of causality between exposure and outcome.
* Effect Modification: Relative risk can be used to evaluate effect modification, where the strength of the association between exposure and outcome varies based on the levels of another factor. Stratified analyses can help identify effect modifiers.
* Generalizability: The generalizability of relative risk depends on the study population, exposure assessment methods, outcome measurement, and other characteristics of the study. Generalizability should be considered when interpreting and applying relative risk estimates to other populations or settings.

### Interpretation

* RR = 1: If the relative risk is equal to 1, it indicates no difference in risk between the exposed and unexposed groups. In other words, the exposure does not have an impact on the outcome.
* RR > 1: A relative risk greater than 1 signifies an increased risk associated with exposure. This suggests that the exposed group has a higher risk of experiencing the outcome compared to the unexposed group.
* RR < 1: A relative risk less than 1 indicates a decreased risk associated with exposure. This suggests that the exposed group has a lower risk of experiencing the outcome compared to the unexposed group.
* Magnitude: The higher the RR value, the stronger the association. 
    * risk effect: an RR of 1.5 indicates a 50% higher risk in the exposed group compared to the unexposed group.
    * protective effect: an RR of 0.5 indicates a 50% lower risk in the exposed group compared to the unexposed group.
* Direction
    * An RR > 1 indicates a positive association, suggesting that the exposure is a risk factor for the outcome.
    * An RR < 1 indicates a negative association, suggesting that the exposure is protective against the outcome.
* Confidence Interval (CI): The relative risk is often reported with a confidence interval, which indicates the range of plausible values for the true relative risk. If the CI includes 1, it suggests that the observed association is not statistically significant, and the risk difference between the groups may be due to chance.
* Clinical and Public Health Significance: When interpreting relative risk, consider the clinical or public health significance of the observed association. A small or modest relative risk may have limited practical importance, whereas a large relative risk may have substantial implications for intervention or preventive measures.

### Example

$$
\begin{array}{c|c|c|c}
 & & \text{Outcome} & \\
 & & \text{Yes} & \text{No} \\
\hline
\text{Exposure} & \text{Exposed} & 50 & 100 \\
 & \text{Unexposed} & 30 & 120 \\
\end{array}
$$

The contingency table above represents the relationship between exposure and outcome. 
$$
\text{RR} = \frac{{\frac{{50}}{{50+100}}}}{{\frac{{30}}{{30+120}}}} = \frac{{50 \times (30+120)}}{{30 \times (50+100)}}
$$

To interpret the relative risk:

* If RR = 1, there is no difference in risk between the exposed and unexposed groups.
* If RR > 1, the exposed group has a higher risk of the outcome compared to the unexposed group.
* If RR < 1, the exposed group has a lower risk of the outcome compared to the unexposed group.

Let's calculate the relative risk using the given values:

$$
\text{RR} = \frac{{50 \times (30+120)}}{{30 \times (50+100)}} = \frac{{50 \times 150}}{{30 \times 150}} = \frac{{7500}}{{4500}} = 1.67
$$

Based on the calculated RR of 1.67, we can conclude that the exposed group has a 1.67 times higher risk of the outcome compared to the unexposed group.

## Odds Ratio

:::{#def-odds}
## Odds

The odds are defined as the probability that the event will occur divided by the probability that the event will not occur a.k.a $\frac{\text{P}(\text{Sucess})}{\text{P}(\text{Failure})}$. The odds can be denoted as:

$$
\frac{\text{P}(X=\text{the event will occur})}{\text{P}(\overline{X}=\text{the event will not occur})} = \frac{\text{P}(X)}{1-\text{P}(X)}
$$.

In other words, odds is a ratio of probabilities.

The odds can be calcuated as the formula:

$$
\begin{array}{c|c|c}
 & \text{Event} & \text{Non-Event} \\ \hline
\text{Exposed} & a & b \\
\text{Unexposed} & c & d \\
\end{array}
$$

The odds of the event occurring in the exposed group are given by:

$$
\text{Odds}_\text{exposed} = \frac{a}{b}
$$

Similarly, the odds of the event occurring in the unexposed group are given by:

$$
\text{Odds}_\text{unexposed} = \frac{c}{d}
$$

:::

### Properties

* Ratio of Probabilities: Odds represent the ratio of the probability of an event occurring to the probability of the event not occurring. Mathematically, odds are defined as the probability of an event divided by the probability of its complement.
* Range: Odds $\in [0,\infty)$. An event with a probability of 0 corresponds to odds of 0, while an event with a probability of 1 corresponds to odds of infinity. Values between 0 and 1 represent odds less than 1, indicating the event is less likely to occur than not.
* Interpretability: Odds are often interpreted as the number of times an event is likely to occur compared to the number of times it is unlikely to occur. For example, odds of 2:1 indicate that the event is twice as likely to occur as not to occur.
* Non-symmetry: Odds are not symmetric around 1. For example, odds of 2:1 and 1:2 represent different scenarios, with the former indicating a higher likelihood of the event and the latter indicating a higher likelihood of the complement.
* Independence: When events are independent, the odds of their joint occurrence can be calculated by multiplying the individual odds. In contrast, probabilities cannot be directly multiplied for independent events.

Odds Ratios: The ratio of two odds is called an odds ratio. Odds ratios are commonly used to measure the association between exposure and outcome in case-control studies and logistic regression analysis.

Logarithmic Transformation: Odds are often transformed using logarithms for ease of analysis. The log-odds, also known as the logit, is commonly used in logistic regression models.

Probability-Odds Conversion: Odds can be converted back to probabilities using the formula: probability = odds / (1 + odds). This conversion allows for the interpretation of odds in terms of probabilities.

Common Use in Gambling: Odds have widespread use in the gambling industry to represent the likelihood of specific outcomes in games of chance, such as sports betting and casino games.

Interpretation Challenges: Odds are not as intuitively interpretable as probabilities, particularly when the odds deviate significantly from 1. Care must be taken when interpreting odds to avoid miscommunication or misunderstanding.

Understanding these properties of odds is essential for their proper application and interpretation in various fields of study. It is crucial to consider the specific context, statistical methods, and other measures of association when working with odds.

:::

</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>

# Go to Project Content List

[Project Content List](./docs/projects/index.qmd)

# Go to Blog Content List

[Blog Content List](../../content_list.qmd)