---
title: Minimizer & Maximizer
subtitle: Local & Global Minimizer and Maximizer, Critical points
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 03/23/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}


A minimizer or a maximizer refer to a point in the domain of a function where the function achieves its minimum or maximum value. More formally, let $f: X → \mathbb R$ be a real-valued function defined on a set $X \subset \mathbb R$. 

:::{#def-minimum}

$f(x^*)$ with a point $x^* \in X$ is called a **minimum** if $f(x^*) \le f(x)$ for all $x \in X$.
$$
\min_{x\in X}{f(x)}
$$
, which means a minimum, $f(x)$.
:::

:::{#def-maximum}

$f(x^*)$  with a point $x^* \in X$ is called a **maximum** if $f(x^*) \ge f(x)$ for all $x \in X$.
$$
\max_{x\in X}{f(x)}
$$
, which means a maximum, $f(x)$.
:::

:::{#def-minimizer}

A point $x^* \in X$ is called a **minimizer** of $f$ if $f(x^*) \le f(x)$ for all $x \in X$.
$$
\arg\min_{x\in X}{f(x)}
$$
, which means $x$ that mainimizes $f(x)$.
:::

:::{#def-maximizer}

A point $x^* \in X$ is called a **maximizer** of $f$ if $f(x^*) \ge f(x)$ for all $x \in X$.
$$
\arg\max_{x\in X}{f(x)}
$$
, which means $x$ that maximizes $f(x)$.
:::

:::{#def-global_minimizer}

A point $x^* \in X$ is called a **global mainimizer** of $f$ if $f(x^*) \ge f(x)$ for all $x \in \mathbb R$.
$$
\arg\min_{x\in \mathbb R}{f(x)}
$$
, which means $x$ that minimizes $f(x)$.
:::

:::{#def-global_maximizer}

A point $x^* \in X$ is called a **global maximizer** of $f$ if $f(x^*) \ge f(x)$ for all $x \in \mathbb R$.
$$
\arg\max_{x\in \mathbb R}{f(x)}
$$
, which means $x$ that maximizes $f(x)$.
:::

:::{#def-strict_global_maximizer}

A point $x^* \in X$ is called a **strict global maximizer** of $f$  
if $f(x^*) > f(x)$ for all $x \in \mathbb R$.

:::

:::{#def-strict_global_miniimizer}
A point $x^* \in X$ is called a **strict global miniimizer** of $f$  
if $f(x^*) < f(x)$ for all $x \in \mathbb R$.
:::

:::{#def-local_minimizer}

A local minimizer of $f$ is a point $x* \in X$ such that there exists a radius, $\delta>0$ of a neighborhood of $x^*$ such that $f(x*) \le f(x)$ for all $x \in (x^*-\delta,x^*+\delta)$ or $|x-x^*|<\delta$ . A local minimizer is at least best possible solution among nearby points.
:::

:::{#def-local_maximizer}

A local maximizer of $f$ is a point $x* \in X$ such that there exists a radius, $\delta>0$ of a neighborhood of $x^*$ such that $f(x*) \ge f(x)$ for all $x \in (x^*-\delta,x^*+\delta)$ or $|x-x^*|<\delta$ . A local maximizer is at least best possible solution among nearby points.
:::

:::{#def-strict_local_minimizer}

A strict local minimizer of $f$ is a point $x* \in X$ such that there exists a radius, $\delta>0$ of a neighborhood of $x^*$ such that $f(x*) < f(x)$ for all $x \in (x^*-\delta,x^*+\delta)$ or $|x-x^*|<\delta$ . A local minimizer is at least best possible solution among nearby points.
:::

:::{#def-strict_local_maximizer}

A strict local maximizer of $f$ is a point $x* \in X$ such that there exists a radius, $\delta>0$ of a neighborhood of $x^*$ such that $f(x*) > f(x)$ for all $x \in (x^*-\delta,x^*+\delta)$ or $|x-x^*|<\delta$ . A local maximizer is at least best possible solution among nearby points.
:::

:::{#def-critical_point}

It is said to be a critical point if $f'(x)$ exists and $f'(x^*)=0$ for $x^* \in X$.
:::

Note that a function may have multiple minimizers, and some functions may not have a minimizer at all. In addition, if a function has multiple minimizers, they may be either global or local minimizers.

* Example
    * If $f(x)=2(x-3)^2+8$, the vertex is $(2,8)$, the global minimizer is $2$, the global minimum is $8$.
    * If $f(x)=x^3-3x^2+4$, then $f'(x)=3x^2-6x=3x(x-2)$ and the critical points are $(0,4), (2,0)$
    * If $f(x)=7x^5-35x+4$, then $f'(x)=35x^4-35=35(x^2+1)(x-1)(x+1)$ critical points are $(-1,0), (1,32)$
    * If $f(x)=\frac{2x}{x^2+1}$, then $f'(x)=\frac{2(1-x)(1+x)}{(1+x^2)^2}$ the critical points are $(-1,-1), (1,1)$.


:::{#thm-theorem}

For $f:X \rightarrow \mathbb R$, let $f(x)$, $f'(x)$, and $f''(x)$ be all continuous. For $x^* \in X$, $f'(x^*)=0$

1. If $f''(x)\ge 0$ for all $x \in X$, $x^*$ is a global minimizer
1. If $f''(x)> 0$ for all $x \in X$, $x^*$ is a strict global minimizer
1. If $f''(x^*)> 0$, $x^*$ is a strict local minimizer
:::

the reverse of the stament 1 in @thm-theorem is not true.

:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>


# Go to Blog Content List

[Blog Content List](./docs/blog/posts/content_list.qmd)