---
title: Content List, Deep Learning
subtitle: Guide Map of Blogs in Deep Learning Section
description: |
  Just enumerating a list of the contents in the Deep Learning (DL) section 
categories:
  - DL
author: Kwangmin Kim
date: 01/01/2100
format: 
  html:
    page-layout: full
    code-fold: true
tbl-colwidths: [50,50]
---

**(Draft)**

# Contents List

## Introduction

* 1111-11-11, Artificial Intelligence
* 1111-11-11, Perceptron
* 1111-11-11, Artificial Neural Netwroks (ANN)
  * 1111-11-11, activation functions
  * 1111-11-11, output layer design
* 1111-11-11, loss function
* 1111-11-11, numerical differentiation
* 1111-11-11, gradient descent
* 1111-11-11, backpropagation
* 1111-11-11, optimizer
  * 1111-11-11, stochastic gradient descent
  * 1111-11-11, momentum
  * 1111-11-11, adaGrad
  * 1111-11-11, adam
  * 1111-11-11, weight initalization
* 1111-11-11, batch normalization
* 1111-11-11, dropout
* 1111-11-11, tuning parameter
* 1111-11-11, auto-encoder
* 1111-11-11, stacked auto-encoder
* 1111-11-11, denoising auto-encoder(DAE)

### Convolutional Neural Network (CNN)
* 2023-03-10, [CNN (1) - Concept](../2023-03-10_cnn/index.qmd)
* 2023-03-10, [CNN (2) - Practice]()

### Natural Language Process (NLP)
* 1111-11-11, word2vec
* 1111-11-11, improved word2vec

### Recurrent Neural Network (RNN)

### Gate Recurrent Unit (GRU)

### Long Short-Term Memory (LSTM)

### Attention (Transformer)

### Bidirectional Encoder Representations from Transformers (BERT)

### Generative Pre-training Transformer (GPT)
  