---
title: Content List, Engineering 
subtitle: Engineering for Python 
description: | 
  Engineering for Data Science
categories:
  - Engineering
author: Kwangmin Kim
date: 01/01/2100
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

## IT Terminology

* 0000-00-00, Terminology

## Data Structure

* 2023-01-17, [Overview](../2023-01-17_data_structure_overview/)
* 2023-01-18, [Array](../2023-01-18_array/)
* 2023-01-18, [Linked List](../2023-01-18_linked_list/)
* 2023-01-18, [Python List](../2023-01-18_python_list/)
* 2023-01-19, [Stack](../2023-01-19_stack/)
* 2023-01-19, [Queue](../2023-01-19_queue/)
* 2023-01-26, [Deque](../2023-01-19_deque/)
* 2023-01-26, [Binary Search Tree](../2023-01-20_binary_search_tree/)
* 2023-01-20, [Priority Queue](../2023-01-20_priority_queue/)
* 2023-01-20, [Graph](../2023-01-20_graph/)

## Development Environment Setting

### WSL2

* 2023-05-01, [Introduction & Installation](../WSL/01.wsl-install.qmd)
* 2023-05-01, [Frequently Used Linux Command](../Linux/01.linux_comands.qmd)

### Docker

* 2023-05-01, [Introduction & Installation](../Docker/01.docker_install.qmd)

### VS code

* 2023-05-01, [Introduction & Installation](../VScode/01.vscode_install.qmd)

### Conda

* 2023-05-01, [Introduction & Installation](../Conda/01.conda_install.qmd)

### Git

* 2023-05-01, [Introduction & Installation](../Git/01.git_install.qmd)

## Documentation

### Dynamic Documentation

* 2023-01-19, [Quarto](https://quarto.org/docs/get-started/)
* 2023-01-19, [xaringan[R]](https://github.com/yihui/xaringan)
* 2023-01-19, [Bookdown[R]](https://bookdown.org/yihui/bookdown/get-started.html)
* 2023-01-19, [DISTL](https://decile-team-distil.readthedocs.io/en/latest/index.html)
* 2023-01-26, [Sphinx[Python]](https://www.sphinx-doc.org/en/master/)

### Diagrams

* 2023-05-01, [Quarto & Diagrams](https://quarto.org/docs/authoring/diagrams.html)
* 2023-05-01, [Graphiz Gallery](https://graphviz.org/gallery/)
* 2023-05-01, [Mermaid Gallery](https://mermaid.js.org/#/)

## AWS Cloud

Coursera Course: AWS Fundamentals

* 2023-03-09, [Computing and Networking](../2023-03-02_aws/computing_networking.qmd)
* 2023-03-12, [Storage and Database](../2023-03-02_aws/storage_database.qmd)
* 2023-03-26, [Monitoring and SharedResponsibility](../2023-03-02_aws/monitoring_sharedresponsibility.qmd)
* 2023-04-05, [Infrastructure Security](../2023-03-02_aws/infra_security.qmd)

## Azure Cloud

## GCP

## Apache Airflow

* 2023-05-01, [introduction](../airflow/01.intro.qmd)
* 2023-05-01, [Airflow Environment Setting](../airflow/02.env_setting.qmd)
* 2023-05-01, [Operator Basics](../airflow/03.operator_basic.qmd)
* 2023-05-01, [Python Operators](../airflow/04.python_operator.qmd)
* 2023-05-01, [Template Variable](../airflow/05.template_variable.qmd)

## Apache Spark

## Data Modeling



## Front End

## Back End