---
title: Transofrmations of Functions
subtitle: template
description: |
  template
categories:
  - Mathematics
author: Kwangmin Kim
date: 02/18/2023
format: 
  html:
    page-layout: full
    code-fold: true
draft: False
---


<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Transformations of Functions

### Translations

Thanslations are about vertical and horizontal sifts. To be more sepecific, if $c$ is a positive number, then

* $y=f(x)+c$, shift the graph of $y=f(x)$ a distance $c$ units upward
* $y=f(x)-c$, shift the graph of $y=f(x)$ a distance $c$ units downward
* $y=f(x-c)$, shift the graph of $y=f(x)$ a distance $c$ units to the right
* $y=f(x+c)$, shift the graph of $y=f(x)$ a distance $c$ units to the left

#### Example 

draw $y=x$, $y=(x-3)$, $y=x-3$, $y=(x+3)$, $y=x+3$

```{python}
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 1000)
y = x
y2 = x-3
y3 = x+3


plt.xlabel('X')
plt.ylabel('Y')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.grid(True, which='both')

plt.plot(x,y,color='black',label='y=x')
plt.plot(x,y2,color='red',label='y=(x-3) or (y+3)=x')
plt.plot(x,y3,color='blue',label='y=(x+3) or (y-3)=x')

plt.title('Traslation of Functions')
plt.legend()
plt.show()

```

### Transformations

There are largely two types of transofrmations of functions: stretching and reflecting. To be more sepecific, if $c$ is larger than 1, then

* $y=cf(x)$, stretch the graph of $y=f(x)$ vertically by a factor of $c$ 
* $y=\frac{1}{c}f(x)$, shrink the graph of $y=f(x)$ vertically by a factor of $c$
* $y=f(cx)$, shrink the graph of $y=f(x)$ horizontally by a factor of $c$
* $y=f(\frac{x}{c})$, stretch the graph of $y=f(x)$ horizontally by a factor of $c$

#### Example 

draw $y=\sin x$, $y=\sin 2x$, $y=\frac{1}{2} \sin x$

```{python}

x = np.linspace(-10, 10, 1000)
y = np.sin(x)
y2 = np.sin(2*x)
y3 = np.sin(x/2)
y4 = 2*np.sin(x)
y5 = np.sin(x)/2

plt.xlabel('X')
plt.ylabel('Y')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.grid(True, which='both')

plt.plot(x,y,color='black',label='y=sin(x)')
plt.plot(x,y2,color='red',label='y=sin(2x)')
plt.plot(x,y3,color='blue',label=r'y=sin($\frac{x}{2}$)')
plt.plot(x,y4,color='green',label=r'y=2sin(x)')
plt.plot(x,y5,color='orange',label=r'y=$\frac{1}{2}$sin(x) or (2y)=sin(x)')

plt.title('Trasformation of Functions')
plt.legend(shadow=True, loc=(-0.2, 1.05), handlelength=1.5, fontsize=8)
plt.show()

```

#### Example

* draw $x^2+y^2=1$, $\frac{x^2}{4}+\frac{y^2}{9}=1$, $(x-3)^2+(y-3)^2=1$, $\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$

```{python}

# initialize x and y using radian
# theta = np.linspace(0, 2*np.pi, 1000)
# x = np.cos(theta)
# y = np.sin(theta)

# initialize x and y without using radian
x = np.linspace(-1, 1, 1000)
y1 = np.sqrt(1 - x*x)
y2 = -np.sqrt(1 - x*x)

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y1, color='black', label=r'$x^2+y^2=1$')
ax.plot(x, y2, color='black')
ax.plot(0,0,'o',color='black', label='(0,0)')

# unit circle translated by 2
ax.plot(x+3, y1+3, color='red', label=r'$(x-3)^2+(y-3)^2=1$')
ax.plot(x+3, y2+3, color='red')
ax.plot(3,3,'o',color='red', label='(3,3)')

# eplipse: a unit circle transformed by 2,3 in x, y
ax.plot(2*x, 3*y1, color='blue', label=r'$\frac{x^2}{4}+\frac{y^2}{9}=1$')
ax.plot(2*x, 3*y2, color='blue')
ax.plot(0,-np.sqrt(9-4), 'o', color='blue', label=r'$F_1=(0,\sqrt{5}),F_2=(0,-\sqrt{5})$')
ax.plot(0,np.sqrt(9-4), 'o', color='blue')

# translated eplipse: a unit circle translated by 2 and transformed by 2,3 in x, y
ax.plot(2*x+3, 3*y1+3, color='green', label=r'$\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$')
ax.plot(2*x+3, 3*y2+3, color='green')
ax.plot(0+3,-np.sqrt(9-4)+3, 'o', color='green', label=r'$F_1=(3,\sqrt{5}+3),F_2=(3,-\sqrt{5}+3)$')
ax.plot(0+3,np.sqrt(9-4)+3, 'o', color='green')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-4, 7])
ax.set_ylim([-4, 7])

ax.grid(True)
ax.set_title("Transformation of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")

plt.legend(shadow=True, loc=(-0.5, 1.05), handlelength=1.5, fontsize=8)

# show the plot
plt.show()

```

* Try using $y=\sin (\theta)$, $x=\cos (\theta)$, by yourself, to draw $x^2+y^2=1$, $\frac{x^2}{4}+\frac{y^2}{9}=1$, $(x-3)^2+(y-3)^2=1$, $\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$

### Reflections

* $y=-f(x)$, reflect the graph of $y=f(x)$ about the x-axis
* $y=f(-x)$, reflect the graph of $y=f(x)$ about the y-axis
* $-y=f(-x)$, reflect the graph of $y=f(x)$ about the origin on the 2D plain
* $x=f(y)$, reflect the graph of $y=f(x)$ about the $y=x$

#### Example

* draw $y=\sin x$, $y=\sin (-x)$, $y=-\sin x$, $-y=-\sin x$, $x=-\sin y$ 

```{python}

x = np.linspace(0, 2*np.pi, 1000)
x1 = np.linspace(-2*np.pi, 2*np.pi, 1000)
y = np.sin(x)

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y, color='black', label='$y=\sin (x)$')
ax.plot(-x, y, color='blue', label='$y=\sin (-x)$')
ax.plot(x, -y, color='green', label='$y=-\sin (x)$')
ax.plot(-x, -y, color='orange', label='$-y=-\sin (x)$')
ax.plot(x1,x1, color='red', label='$y=x$')
ax.plot(np.sin(y),x, color='black', label='$y=sin^{-1}(x)$',linestyle='dashed')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-7, 7])
ax.set_ylim([-7, 7])

ax.grid(True)
ax.set_title("Reflection of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")
plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
# show the plot
plt.show()

```

* Draw $S(x)=\frac{1}{1+e^{-x}}$


```{python}

x = np.linspace(-10, 10, 1000)
y = 1/(1+np.exp(-x))

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y, color='black', label='$y=S(x)$')
ax.plot(-x, y, color='blue', label='$y=S(-x)$')
ax.plot(x, -y, color='green', label='$y=-S(x)$')
ax.plot(-x, -y, color='orange', label='$-y=-S(x)$')
ax.plot(x,x, color='red', label='$y=x$')
ax.plot(np.sin(y),x, color='black', label='$y=S^{-1}(x)$',linestyle='dashed')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-3, 3])
ax.set_ylim([-3, 3])

ax.grid(True)
ax.set_title("Reflection of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")
plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
# show the plot
plt.show()

```

#### Application: Standardization

* Distribution of Raw Data

```{python}

data1 = np.random.normal(loc=5,scale=6.0,size=1000) #loc=mean, scale=sd
data2 = np.random.normal(loc=-4,scale=2.0,size=1000)
data3 = np.random.normal(loc=-7,scale=2.5,size=1000)
data4 = np.random.normal(loc=0,scale=1.0,size=1000)

# the range of values to evaluate the PDF
x = np.linspace(data2.min(), data1.max(), 10000)

bins_number=100

# Plot the data and PDF
plt.hist(data1, density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5,6^2)$')
plt.hist(data2, density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4,2^2)$')
plt.hist(data3, density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7,2.5^2)$')
plt.hist(data4, density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Raw Data")
plt.show()

```

* Distribution of Translated Raw Data

```{python}

# Plot the data and PDF
plt.hist(data1-data1.mean(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5-5,6^2)$')
plt.hist(data2-data2.mean(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4-(-4),2^2)$')
plt.hist(data3-data3.mean(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7-(-7),2.5^2)$')
plt.hist(data4-data4.mean(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0-0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Translated Raw Data")
plt.show()

```

* Distribution of Transformed Raw Data

```{python}

# Plot the data and PDF
plt.hist(data1/data1.std(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5,6^2/6^2)$')
plt.hist(data2/data2.std(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4,2^2/2^2)$')
plt.hist(data3/data3.std(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7,2.5^2/5^2)$')
plt.hist(data4/data4.std(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1/1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Transformed Raw Data")
plt.show()

```

* Distribution of Standardized Raw Data

```{python}

# Plot the data and PDF
plt.hist((data1-data1.mean())/data1.std(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data2-data2.mean())/data2.std(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data3-data3.mean())/data3.std(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data4-data4.mean())/data4.std(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Standardized Raw Data")
plt.show()

```



## Thinking About ...

* Transformation in Statistics? ex) transformation of random variable
* Transformation in Linear Algebra? ex) linear transformation or linear mapping (transformation matrix) 
* Transformation in Machine Learning? ex) scaling (min-max normalization or standardization) 


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

## Transformations of Functions

### Translations

Thanslations are about vertical and horizontal sifts. To be more sepecific, if $c$ is a positive number, then

* $y=f(x)+c$, shift the graph of $y=f(x)$ a distance $c$ units upward
* $y=f(x)-c$, shift the graph of $y=f(x)$ a distance $c$ units downward
* $y=f(x-c)$, shift the graph of $y=f(x)$ a distance $c$ units to the right
* $y=f(x+c)$, shift the graph of $y=f(x)$ a distance $c$ units to the left

#### Example 

draw $y=x$, $y=(x-3)$, $y=x-3$, $y=(x+3)$, $y=x+3$

```{python}

x = np.linspace(-10, 10, 1000)
y = x
y2 = x-3
y3 = x+3


plt.xlabel('X')
plt.ylabel('Y')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.grid(True, which='both')

plt.plot(x,y,color='black',label='y=x')
plt.plot(x,y2,color='red',label='y=(x-3) or (y+3)=x')
plt.plot(x,y3,color='blue',label='y=(x+3) or (y-3)=x')

plt.title('Traslation of Functions')
plt.legend()
plt.show()

```

### Transformations

There are largely two types of transofrmations of functions: stretching and reflecting. To be more sepecific, if $c$ is larger than 1, then

* $y=cf(x)$, stretch the graph of $y=f(x)$ vertically by a factor of $c$ 
* $y=\frac{1}{c}f(x)$, shrink the graph of $y=f(x)$ vertically by a factor of $c$
* $y=f(cx)$, shrink the graph of $y=f(x)$ horizontally by a factor of $c$
* $y=f(\frac{x}{c})$, stretch the graph of $y=f(x)$ horizontally by a factor of $c$

#### Example 

draw $y=\sin x$, $y=\sin 2x$, $y=\frac{1}{2} \sin x$

```{python}

x = np.linspace(-10, 10, 1000)
y = np.sin(x)
y2 = np.sin(2*x)
y3 = np.sin(x/2)
y4 = 2*np.sin(x)
y5 = np.sin(x)/2

plt.xlabel('X')
plt.ylabel('Y')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.grid(True, which='both')

plt.plot(x,y,color='black',label='y=sin(x)')
plt.plot(x,y2,color='red',label='y=sin(2x)')
plt.plot(x,y3,color='blue',label=r'y=sin($\frac{x}{2}$)')
plt.plot(x,y4,color='green',label=r'y=2sin(x)')
plt.plot(x,y5,color='orange',label=r'y=$\frac{1}{2}$sin(x) or (2y)=sin(x)')

plt.title('Trasformation of Functions')
plt.legend(shadow=True, loc=(-0.2, 1.05), handlelength=1.5, fontsize=8)
plt.show()

```

#### Example

* draw $x^2+y^2=1$, $\frac{x^2}{4}+\frac{y^2}{9}=1$, $(x-3)^2+(y-3)^2=1$, $\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$

```{python}

# initialize x and y using radian
# theta = np.linspace(0, 2*np.pi, 1000)
# x = np.cos(theta)
# y = np.sin(theta)

# initialize x and y without using radian
x = np.linspace(-1, 1, 1000)
y1 = np.sqrt(1 - x*x)
y2 = -np.sqrt(1 - x*x)

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y1, color='black', label=r'$x^2+y^2=1$')
ax.plot(x, y2, color='black')
ax.plot(0,0,'o',color='black', label='(0,0)')

# unit circle translated by 2
ax.plot(x+3, y1+3, color='red', label=r'$(x-3)^2+(y-3)^2=1$')
ax.plot(x+3, y2+3, color='red')
ax.plot(3,3,'o',color='red', label='(3,3)')

# eplipse: a unit circle transformed by 2,3 in x, y
ax.plot(2*x, 3*y1, color='blue', label=r'$\frac{x^2}{4}+\frac{y^2}{9}=1$')
ax.plot(2*x, 3*y2, color='blue')
ax.plot(0,-np.sqrt(9-4), 'o', color='blue', label=r'$F_1=(0,\sqrt{5}),F_2=(0,-\sqrt{5})$')
ax.plot(0,np.sqrt(9-4), 'o', color='blue')

# translated eplipse: a unit circle translated by 2 and transformed by 2,3 in x, y
ax.plot(2*x+3, 3*y1+3, color='green', label=r'$\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$')
ax.plot(2*x+3, 3*y2+3, color='green')
ax.plot(0+3,-np.sqrt(9-4)+3, 'o', color='green', label=r'$F_1=(3,\sqrt{5}+3),F_2=(3,-\sqrt{5}+3)$')
ax.plot(0+3,np.sqrt(9-4)+3, 'o', color='green')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-4, 7])
ax.set_ylim([-4, 7])

ax.grid(True)
ax.set_title("Transformation of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")

plt.legend(shadow=True, loc=(-0.5, 1.05), handlelength=1.5, fontsize=8)

# show the plot
plt.show()

```

* Try using $y=\sin (\theta)$, $x=\cos (\theta)$, by yourself, to draw $x^2+y^2=1$, $\frac{x^2}{4}+\frac{y^2}{9}=1$, $(x-3)^2+(y-3)^2=1$, $\frac{(x-3)^2}{4}+\frac{(y-3)^2}{9}=1$

### Reflections

* $y=-f(x)$, reflect the graph of $y=f(x)$ about the x-axis
* $y=f(-x)$, reflect the graph of $y=f(x)$ about the y-axis
* $-y=f(-x)$, reflect the graph of $y=f(x)$ about the origin on the 2D plain
* $x=f(y)$, reflect the graph of $y=f(x)$ about the $y=x$

#### Example

* draw $y=\sin x$, $y=\sin (-x)$, $y=-\sin x$, $-y=-\sin x$, $x=-\sin y$ 

```{python}

x = np.linspace(0, 2*np.pi, 1000)
x1 = np.linspace(-2*np.pi, 2*np.pi, 1000)
y = np.sin(x)

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y, color='black', label='$y=\sin (x)$')
ax.plot(-x, y, color='blue', label='$y=\sin (-x)$')
ax.plot(x, -y, color='green', label='$y=-\sin (x)$')
ax.plot(-x, -y, color='orange', label='$-y=-\sin (x)$')
ax.plot(x1,x1, color='red', label='$y=x$')
ax.plot(np.sin(y),x, color='black', label='$y=sin^{-1}(x)$',linestyle='dashed')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-7, 7])
ax.set_ylim([-7, 7])

ax.grid(True)
ax.set_title("Reflection of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")
plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
# show the plot
plt.show()

```

* Draw $S(x)=\frac{1}{1+e^{-x}}$


```{python}

x = np.linspace(-10, 10, 1000)
y = 1/(1+np.exp(-x))

fig, ax = plt.subplots()

# unit circle
ax.plot(x, y, color='black', label='$y=S(x)$')
ax.plot(-x, y, color='blue', label='$y=S(-x)$')
ax.plot(x, -y, color='green', label='$y=-S(x)$')
ax.plot(-x, -y, color='orange', label='$-y=-S(x)$')
ax.plot(x,x, color='red', label='$y=x$')
ax.plot(np.sin(y),x, color='black', label='$y=S^{-1}(x)$',linestyle='dashed')

# height/width=1
ax.set_aspect(1)

ax.set_xlim([-3, 3])
ax.set_ylim([-3, 3])

ax.grid(True)
ax.set_title("Reflection of Functions")
ax.set_xlabel("x-axis")
ax.set_ylabel("y-axis")
plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
# show the plot
plt.show()

```

#### Application: Standardization

* Distribution of Raw Data

```{python}

data1 = np.random.normal(loc=5,scale=6.0,size=1000) #loc=mean, scale=sd
data2 = np.random.normal(loc=-4,scale=2.0,size=1000)
data3 = np.random.normal(loc=-7,scale=2.5,size=1000)
data4 = np.random.normal(loc=0,scale=1.0,size=1000)

# the range of values to evaluate the PDF
x = np.linspace(data2.min(), data1.max(), 10000)

bins_number=100

# Plot the data and PDF
plt.hist(data1, density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5,6^2)$')
plt.hist(data2, density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4,2^2)$')
plt.hist(data3, density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7,2.5^2)$')
plt.hist(data4, density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Raw Data")
plt.show()

```

* Distribution of Translated Raw Data

```{python}

# Plot the data and PDF
plt.hist(data1-data1.mean(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5-5,6^2)$')
plt.hist(data2-data2.mean(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4-(-4),2^2)$')
plt.hist(data3-data3.mean(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7-(-7),2.5^2)$')
plt.hist(data4-data4.mean(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0-0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Translated Raw Data")
plt.show()

```

* Distribution of Transformed Raw Data

```{python}

# Plot the data and PDF
plt.hist(data1/data1.std(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(5,6^2/6^2)$')
plt.hist(data2/data2.std(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(-4,2^2/2^2)$')
plt.hist(data3/data3.std(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(-7,2.5^2/5^2)$')
plt.hist(data4/data4.std(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1/1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Transformed Raw Data")
plt.show()

```


* Distribution of Standardized Raw Data

```{python}

# Plot the data and PDF
plt.hist((data1-data1.mean())/data1.std(), density=True, color="red", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data2-data2.mean())/data2.std(), density=True, color="green", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data3-data3.mean())/data3.std(), density=True, color="blue", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')
plt.hist((data4-data4.mean())/data4.std(), density=True, color="black", alpha=0.5, bins=bins_number,label=r'$X \sim N(0,1)$')

plt.legend(shadow=True, loc=(-0.25, 1.05), handlelength=1.5, fontsize=8)
plt.title("Distribution of Standardized Raw Data")
plt.show()

```

## Thinking About ...

* Transformation in Statistics? ex) transformation of random variable
* Transformation in Linear Algebra? ex) linear transformation or linear mapping (transformation matrix) 
* Transformation in Machine Learning? ex) scaling (min-max normalization or standardization) 

</div>

```{python}
#| echo: false
#| eval: false 
radius = 10
from IPython.display import display, Markdown
display(Markdown("""
The radius of the circle is {radius}.
""".format(radius = radius)))
```


## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)