---
title: "DevOps Project: Diagnostic Device QC Platform Construction"
subtitle: "Long Term Strategy: Seegene's Full Automation"
description: "Due to security concerns, it is difficult to display the data used in this project."
author: Kwangmin Kim
date: 2023-04-22
format: 
  html:
    toc: true  
    #page-layout: article
    code-fold: true
    code-copy: true
    code-overflow: wrap
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Background

* 진단 장비의 품질 관리는 의료 장비와 연관된 제품의 특성상 Global Market 진출시 각 나라의 정부에서 요구하는 규제사항 중 하나이다.
    * 시약의 안정성 검증 요구
    * **장비의 안정성 검증 요구**
    * Software의 안정성 검증 요구
    * Diagnostic Algorithm의 안정성 검증 요구
* 현재 Seegene이 사용하고 있는 진단 장비는 자사 제품이 아니기 때문에 진단 장비의 품질 관리 방식에 어려움이 있다.
* PCR 기기의 noise test는 의료 장비의 QC process 중 하나로서, Seegene의 시약 제품의 성능 안정성과 직접적으로 영향을 주는 품질 검증 시스템이다.
* 회사의 규모가 커지고 잦은 조직 개편으로 수동 방식의 noise tests가 여러 부서로 이관됨에 따라 noise test 수행자의 이해도와 숙련도가 떨어져 noise test가 올바르게 수행되지 않고 있다.
* 씨젠의 장기 목표인 전사 자동화를 위해 noise test를 자동화하는 프로젝트가 발탁됐다.
 
## Objective

* 2020.12.19~2021.03.06에 입고된 PCR기기 2201대를 2552번의 실험에서 만들어진 61,248개의 신호에서 얻은 data-driven parameters로 장비의 성능을 평가하여 합격/불합격 뿐만 아니라 장비에 등급을 차등 부여하여 시간에 따른 장비의 성능을 지속적으로 분석 가능하게 한다.
* 다음의 주요 문제점을 개선한다.
    * 신호의 증폭 크기에 따라 noise test 결과에 영향을 크게 주어 잘못된 결과를 산출해주는 metric 개선 
    * 단순한 휴먼 에러 신호에 무조건적으로 장비의 불합격처리가 결정 되는 문제를 보완하여 robust한 평가체계로 현업부서의 부담을 덜어준다.
    * 장비 고유에서 발생하는 pattern을 찾아 장비 error 신호를 labeling 한다.
* 20번의 test를 수동으로 계산하는 과정에 30분이 소요되는 것을 웹 기반의 자동화로 약 2~3분내로 단축시킬 수 있다.
* 씨젠의 full automation을 위한 best practice example로 만들어 IT 부문, 제조 부문 및 BT부문과의 협력체계를 구축 및 활성화 한다.
* 시각화와 noise test result history를 제공하여 추적 및 VOC 대응 system을 구축한다.

## Strategies

### Strategy A

* 현업 부서와의 긴밀한 소통으로 QC process를 세분화하여 앞 단계 QC에서 발생하는 data를 활용하여 뒷 단계 QC인 noise test의 결과를 예측한다.
* noise가 적다고 확실시 되는 기기에 한해서 noise test 생략

### Strategy B

* 전체 QC 프로세스를 자동화 또는 반 자동화
* 기존의 noise 측정 metric 분석 및 새로운 metric 생성하여 검사 결과의 정확도를 향상
* 시각화와 noise test result history를 제공하여 실무자의 이해도를 높이고 관리가능하게 한다.

## Issues

* 현업 업무 기술서 부재
* 실무자의 백업 실수
* 부서마다 산재된 데이터
* 높은 난이도의 data cleansing
    * 실무자의 데이터로부터 분석 가능한 데이터 선별
    * 실무자의 데이터의 오입력
    * data 및 문서의 DRM 수동해제
* reverse engineering 필요
* 잦은 조직 개편으로 관련 인원 및 부서 연락체계 부재 

## Required Skills

* Back-end Engineering for DevOps Pipeline Construction
* Data Engineering for data cleansing and reverse engineering
* Data Modeling for a RDB system construction
* Statistical Analysis for the noise test performance verification
* Machine Learning for pattern analysis
* Front-end Engineering for UI/UX construction
* Biologics, Biophysics, Physics, Mathematics, Computer Science, Statistics Knowledge

## Colaborators

* 1 data scientist (me) - project manager
* 5 mechanical engineers 
* 4 biologists
* 2 patent attorneys
* 2 data engineers
* 3 full stack developers
* 1 advisor (a professor of Computer Science at Seoul National University)
 
## Acheivements

|Noise Test| As-Is |To-Be |
|:---:|:---|:---|
| QC 알고리즘 개발에 사용되는 샘플 크기  | n=100  | Signals from 2552 experiments, n=61,248   |
| QC 알고리즘 성능 비교에 사용되는 샘플 크기 | n=61,248  | n=61,248   |
| Evaluation Metrics | 2 metrics | 10 metrics ( the exsting 2 metrics + new 8 metrics)   |
| Input Process | 특정 프로그램에서 추출한 엑셀 파일의 데이터를 수동으로 복사하여 붙여넣기 | 웹 기반 자동화, 다수의 실험 파일 업로드 |
| Output Process| Batch Evaluation method, 
장비의 신호 중 하나라도 부적합 판정되면 장비 자체가 QC 부적합 판정 (맹점: 휴먼에러 신호가 1개라도 있으면 장비는 무조건 실격 처리)| Differential Evaluation method, 장비의 신호에 점수를 계산 후 평균값을 구하고 장비 등급을 A+, A, B, F로 지정. F인 경우 부적합. 오류 신호를 평가에서 제외하므로 오류 신호에 robust  |
| Output 1 |  pass: 92.58%, fail: 7.42% (after excluding many human errors) | A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%  |
| Output 2 |  NA | Visualized Plots and Tables.|
| Output 3 |  NA | Classfication Results: Normal Signals, Human Errors, Device Errors, Manufacturing Errors |
| Time Consumed  | About 30 minutes per 20 experiments | About 25 minutes per 2552 experiments  |
| Data Management| Non-standard management method (작업자마다 다른 방식으로 Excel 파일로 다른 형태로 NAS 디렉토리에 저장) | RDB uploaded by a scheduler (장비 고장 추적 분석이 가능) |

### Remarkable

* 데이터 분석 및 파악 과정에서 실무자의 짐작과 달리 장비의 성능이 전반적인 일관성을 보여주고 있는 것을 확인
* 큰 노이즈와 같은 치명적인 신호를 발생시키는 장비를 선별하여 걸러내는 알고리즘 추가
* 1% 유의수준에서 노이즈 테스트 결과가 전체 진단 과정에서 최종 결과의 평균 차이에 큰 영향을 미치지 않는다는 것을 통계적으로 증명했기 때문에 전체 QC 프로세스에서 **노이즈 테스트를 폐지**.
  - paired t-test & chi-squared test 사용
* 데이터 사이언스 부서에서 실험과 장비에서 생성된 데이터에 대한 이해도를 높일 수 있는 기회가 됐음.
* 전사 DB구축 및 플랫폼 아키텍처 구축의 기반이 됨.


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

## Background

* Quality Control of diagnostic equipment is one of the necessities for the regulations required by the government of each country when entering the global market due to the nature of products related to medical equipment.
    * Reagent stability verification & validation required
    * **Equipment stability verification & validation request**
    * Software stability verification & validation request
    * Stability Verification & validation Request of Diagnostic Algorithm
* Since the diagnostic equipment currently being used by Seegene is not its own product, it is difficult to manage the quality of the diagnostic equipment.
* The noise test of PCR equipment is one of the QC processes of medical equipments, and it is a quality verification system that directly affects the performance stability of Seegene's reagent products.
* As the size of the company grows and frequent organizational reshuffles result in manual noise tests being transferred to various departments, the noise test performers' understanding and skills are low, resulting in noise tests not being performed correctly.
* A project to automate the noise test was selected for Seegene's long-term goal of enterprise automation.
 
## Objective

* Data-driven parameters obtained from 61,248 signals from 2552 experiments were used to evaluate 2201 PCR devices, which were stocked between 2020.12.19 and 2021.03.06. yield Enables continuous analysis of equipment performance over time.
* Improve the following major problems:
    * Improved metrics that produces erroneous results by greatly affecting the noise test result depending on the size of the signal amplification. 
    * It relieves the burden on the field department with a robust evaluation system by supplementing the problem of unconditionally determining equipment rejection in response to a simple human error signal.
    * Equipment error signals are labeled by finding patterns that occur in equipment.
* The time required for the manual calculation process can be reduced from 30 minutes per 20 tests to about 2 to 3 minutes with web-based automation.
* By making this project the best practice example of Seegene's full automation, establish and vitalize the cooperation system between the IT, manufacturing and BT sectors.
* Visualization and noise test result history are provided to build a tracking and VOC response system.

## Strategies

### Strategy A

* The QC process is subdivided through close communication with the field departments, and the results of the noise test, which is the next stage QC, are predicted by utilizing the data generated in the previous stage QC.
* Noise test omitted only for devices that are certain to have low noise.

### Strategy B

* Automate or semi-automate the entire QC process
* Improve the accuracy of inspection results by analyzing the existing noise measurement metric and creating a new metric
* Visualization and noise test result history are provided to increase the understanding of practitioners and enable management

## Issues

* Absence of job description
* Backup Mistakes by Practitioners
* Data scattered across departments
* High level of data cleansing
    * Select data that can be analyzed from practitioner data
    * Incorrect input of practitioner data
    * Manual release of DRM for data and documents
* reverse engineering required
* Absence of contact system for related personnel and departments due to frequent organizational reshuffle

## Required Skills

* Back-end Engineering for DevOps Pipeline Construction
* Data Engineering for data cleansing and reverse engineering
* Data Modeling for a RDB system construction
* Statistical Analysis for the noise test performance verification
* Machine Learning for pattern analysis
* Front-end Engineering for UI/UX construction
* Biologics, Biophysics, Physics Knowledge

## Colaborators

* 1 data scientist (me) - project owner
* 5 mechanical engineers 
* 4 biologists
* 2 patent attorneys
* 2 data engineers
* 3 full stack developers
* 1 advisor (a professor of Computer Science at Seoul National University)
 
## Acheivements

|Noise Test| As-Is |To-Be |
|:---:|:---|:---|
| Sample Size Used for QC Algorithm Development  | n=100  | Signals from 2552 experiments, n=61,248   |
| Sample Size Used for QC Algorithm Performance Comparison | n=61,248  | n=61,248   |
| Evaluation Metrics | 2 metrics | 10 metrics ( the exsting 2 metrics + new 8 metrics)   |
| Input Process | manually copy & paste data of excel files extracted from a certain program | Web-Based Automation, upload multiple experiment files |
| Output Process| Batch Evaluation method, if even one of the signals from the equipment fails, the equipment fails. (Blind Spot: If there is one human error signal, the equipment is unconditionally disqualified.)| Differential Evaluation method, The signals from the equipment are scored, the average value is obtained, and the equipment is graded A+, A, B, and F. Failed if F. Robust on error signals as it excludes the error signal from evaluation.  |
| Output 1 |  pass: 92.58%, fail: 7.42% (after excluding many human errors) | A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%  |
| Output 2 |  NA | Visualized Plots and Tables.|
| Output 3 |  NA | Classfication Results: Normal Signals, Human Errors, Device Errors, Manufacturing Errors |
| Time Consumed  | About 30 minutes per 20 experiments | About 25 minutes per 2552 experiments  |
| Data Management| Non-standard management method (stored in NAS directory in a different form as an Excel file in a different way for each worker) | Automatic loading in DB in standardized form by a scheduler (it is possible to conduct an equipment failure tracing analysis) |

### Remarkable

* During the data analysis and understanding process, it was confirmed that contrary to practitioners' speculation, the performance of the equipment showed overall consistency.
* An algorithm to filter out devices that generate fatal signals like significant noise was added.
* At a 1% significance level, it was statistically proven that the results of the noise tests do not significantly affect the average difference in the final outcomes of the entire diagnostic process, leading to **the elimination of noise tests from the total QC process**. 
  * Paired t-tests and chi-squared tests were utilized for this purpose.
* The data science department had the opportunity to enhance their understanding of experiments and data generated from equipment.
* This became the foundation for the construction of a company-wide database and the development of platform architecture.
</div>