---
title: "Description"
subtitle: "Project Description"
description: "Due to security concerns, it is difficult to display the data used in this project. This project was not only a project I worked at Columbia University Irving Medical Center, but also used for my graduate school graduation research practicum. Although the goal of each step was different, the subject matter is the same, so I will combine them to explain the project. \n 보안 문제로 인해 이 프로젝트에서 사용된 데이터를 공유하기 어렵습니다. 이 프로젝트는 Columbia University Irving Medical Center에서 근무했던 프로젝트 였던 것 뿐만 아니라 제  대학원 졸업 연구 발표용으로도 사용됐습니다. 각 단계에서의 목표는 달랐지만 주제는 같으므로 통합해서 설명하겠습니다."
author: Kwangmin Kim
date: 2023-01-03
format: 
  html:
    toc: true  
    #page-layout: article
    code-fold: true
    code-copy: true
    code-overflow: wrap
    number-sections: true
    number-depth: 3
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
---


<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Background

알츠하이머병(Alzheimer's Disease, AD)은 수백만 명의 미국인에게 영향을 미치는 가장 흔한 형태의 치매이다. 알츠하이머병은 기억력, 사고력 및 행동에 영향을 주지만 증상이 나타나기까지 거의 20년에 걸쳐 진행이 된다. 따라서 전 임상 단계 (Pre-clinical Stage)에서 생리학을 이해하는 것이 필수적이다. 유전적 요인이 AD에 거의 50% 기여하는 것으로 추정된다. 유전자가 세포 환경을 변경하여 알츠하이머병 위험에 어떻게 기여하는지 더 잘 이해하기 위해 AD와 연관이 있는 유전자인 APOE를 보유한 사람들의 대사체(Metabolome)를 조사했다. 대사체는 유전체(Genome)과 단백질체(Proteome)에서 생성된 산물을 의미한다. 이러한 생화학 부산물은 유전적 요인과 환경적 요인 모두의 영향을 받는다. 모집단은 장수마을에 사는 Caucasian (백인) 참여자들이다. 

## Objective

LLFS(Long Life Family Study) 프로젝트의 목적은 유전체, 전사체, 단백질체 및 대사체 단계를 통해 유전체에서 대사체 단계에 이르는 여러 단계에서 통계 및 기계 학습을 사용하여 분석 파이프라인을 구축하고 알츠하이머병에 대한 중요한 바이오마커를 식별하는 것이다.

## Analysis Pipeline

### Overview

```{dot}
digraph G {
  compound=true;
  rankdir=LR;
  subgraph cluster0 {
    rankdir=TB;
    Multi_Centered_Blood_Sampling [shape=box];
    Mass_Spectrometry [shape=box];
    Data_Transfer [shape=box];
    
    label= "Data Collection";

  }
  subgraph cluster1 {
    Identify_Anomaly_Data [shape=box];
    Identify_Missing_Values [shape=box];
    
    label= "Quality Control";
  }
  subgraph cluster2 {
    EDA [shape=box];
    Data_Mining [shape=box];
    Statistical_Analysis [shape=box];
    Machine_Learning [shape=box];
    
    label= "Analytics";
  }
  subgraph cluster3 {
    Share_with_Faculty [shape=box];
    label= "Reporting and Conclusion";
  }
  Data_Transfer -> Identify_Anomaly_Data [lhead=cluster1];
  Identify_Missing_Values -> EDA [lhead=cluster2];
  Machine_Learning -> Share_with_Faculty [lhead=cluster3];
}

```


Data는 장수 마을에 거주하는 백인을 대상으로 New York, Bonston, Pittsburgh 및 Denmark에 있는 여러 medical centers에서 sampled blood를 MS Spectromtetry로 Digitalization을 했다. 여러 과정을 통해 data를 csv형태로 받아 data의 QC(Quality Control)를 진행한뒤 Data 분석 업무를 수행했다. EDA (Exploratory Data Analysis) 와 Data Mining을 통해 data에 대한 이해도를 높였고 이를 토대로 통계 분석과 machine learning을 이용하여 이 data에 적합한 모형을 찾았다. 모든 결과물은 The Taub Institute for Research on Alzheimer's Disease and the Aging Brain 의 biostaticians, medical doctors, biologists, neurologists, bioinformaticians 및 epidemiologists와 공유를 했다.


### Data QC (Quality Control)

```{dot}
//| fig-height: 8

digraph G {
  compound=true;
  rankdir=TB;
  subgraph cluster0 {
    identify_anomaly_data [shape=box];
    identify_missing_values [shape=box];
    subgraph cluster1 {
      Missing_Completely_At_Random [shape=box];
      Missing_At_Random [shape=box];
      Missing_Not_at_Random [shape=box];
      label= "Missing Value Analysis";
      Missing_Completely_At_Random->Missing_At_Random->Missing_Not_at_Random
    }
    either_imputation_or_omission [shape=box];
    communication_with_labs [shape=box];
    set_data_inclusion_exclusion_criteria [shape=box];

    label= "Data Quality Control";
    identify_anomaly_data->identify_missing_values
    identify_missing_values->Missing_Completely_At_Random [lhead=cluster1];
    Missing_Not_at_Random->either_imputation_or_omission->communication_with_labs->set_data_inclusion_exclusion_criteria;

  }
  subgraph cluster2 {
    Data_Transformation [shape=box];
    Log_Transformation [shape=box];
    Standardization [shape=box];
    label= "Data Preprocessing";
    Data_Transformation->
    Log_Transformation->
    Standardization;
  }
  set_data_inclusion_exclusion_criteria->Data_Transformation [lhead=cluster2];
}

```


Data의 품질 관리를 위해 data를 생성한 biochemists와 소통하여 실험실 기준에 따라 결측치와 이상치를 구분하여 labeling을 수행했고 missing value analysis를 통해 결과에 따라 medical doctors를 포함한 다른 faculty members와 상의하여 결측치 처리를 했다. data QC criteria는 rowwise 와 columwise sum의 합이 sample size에 대하여 missing values의 비율이 5%가 넘는 환자와 변수는 분석 대상에서 제외 됐다. 모든 metabolites data는 log transoformation 과 standardization을 통해 data의 단위를 표준화 했다. 

### Methods
```{dot}
  digraph G {
    compound=true;
    rankdir=TB;
    subgraph cluster2 {
    Exploratory_Data_Analysis [shape=box];
    Data_Minig [shape=box];
    Statistical_Analysis [shape=box];
    Machine_Learning [shape=box];
    label= "Data Analytics";
    }
    
    Exploratory_Data_Analysis -> Data_Minig;
    Data_Minig -> Statistical_Analysis ;
    Statistical_Analysis -> Machine_Learning;
  }

```

Data 분석은 크게 EDA (Exploratory Data Analysis), Statistical Analysis 및 Machine Learning과 같이 3 단계로 수행했다. 각 단계에서 나온 결과가 각 각의 단계에서 일관되게 나오는 metabolites를 선별했다.

#### EDA and Data Mining

student t tests, Wilcoxon Man Whiteney tests, $\chi^2$ tests, Fisher Exact Tests, ANOVAs, Kruskal Wallis Tests 및 regression analysis이 수행됐고 visualization을 통해 검정 결과를 재확인하는 작업을 수행했다. 고차원 데이터를 시각화하여 data의 pattern을 관찰하기 위해 KNN, PCA, K means clustering 및 DB Scan을 이용했다.

#### Statistical Analysis

multivariable linear regression, logistic regression 및 Cox PH(Proportional Hazards) regression anayses 가 수행됐고 질병과 유의한 metabolites를 선별했다. multiple testing으로 인한 1 종 오류를 범하는 것을 줄이기 위해 permuted p-values를 계산하여 유의성을 한번 더 확인했다.

#### Machine Learning

Lasso, ridge regression, elastic net, decision tree, random rorests, ada boosting, gradient descent boosting, SVM (support vector machine), partial least square 및 sparse partial least square가 사용됐다. 질병을 가장 잘 예측하는 classifier를 평가하여 최적의 classifier를 선택했다.

### Results & Conclusion

146개의 관측치와 약 3,000여개의 변수로 구성된 data에서 약 60개 내외의 대사물질이 질병과 5% 유의수준으로 유의한 관계가 있는 것으로 관찰됐고 partial least suare 가 가장 성능이 좋은 것으로 관찰됐다. 


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

## Background

Alzheimer Disease (AD) is the most common form of dementia that affects millions of Americans. AD affects memory, thinking and behavior, but its progression is slow, spanning nearly two decades before the symptoms appear. Thus, it is imperative to understand the physiology at the pre-clinical stage. It is estimated that genetic factors contribute nearly 50% to AD. To better understand how genes contribute to the risk of AD by altering cellular milieu, I have examined the metabolome of individuals with the AD-related genotype, APOE. The metabolome represents the products that were generated from the genome and proteome. These biochemical products represent influences of both genetic and environmental factors. The population is Caucasian participants living in longevity village. 

## Objective

The objective of the Long Life Family Study (LLFS) project was to build an analysis pipeline of identifying significant biomarkers for AD using statistics and machine learning at the multi-stages from the genomic to the metabolomic stage through the transcriptomic and proteomic stage. 

## Analysis Pipeline Architecture

### Overview
```{dot}
digraph G {
  compound=true;
  rankdir=LR;
  subgraph cluster0 {
    rankdir=TB;
    Multi_Centered_Blood_Sampling [shape=box];
    Mass_Spectrometry [shape=box];
    Data_Transfer [shape=box];
    
    label= "Data Collection";

  }
  subgraph cluster1 {
    Identify_Anomaly_Data [shape=box];
    Identify_Missing_Values [shape=box];
    
    label= "Quality Control";
  }
  subgraph cluster2 {
    EDA [shape=box];
    Data_Mining [shape=box];
    Statistical_Analysis [shape=box];
    Machine_Learning [shape=box];
    
    label= "Analytics";
  }
  subgraph cluster3 {
    Share_with_Faculty [shape=box];
    label= "Reporting and Conclusion";
  }
  Data_Transfer -> Identify_Anomaly_Data [lhead=cluster1];
  Identify_Missing_Values -> EDA [lhead=cluster2];
  Machine_Learning -> Share_with_Faculty [lhead=cluster3];
}

```

Data were obtained by digitization through MS Spectromtetry of blood samples from multiple medical centers in New York, Bonston, Pittsburgh, and Denmark for Caucasians residing in longevity villages. After receiving the data in a csv format through various processes, QC (Quality Control) of the data and data analysis were performed. To better understand data, exploratory data analysis (EDA) and data mining were conducted. Based on the analysis findings on data, the machine learning model to explain the data most was selcted. All findings were shared with biostatisticians, medical doctors, biologists, neurologists and epidemiologists at the neurology department and the Taub Institute for Research on Alzheimer's Disease and the Aging Brain in the Columbia University Irving Medical Center.

### Data QC

```{dot}
//| fig-height: 8

digraph G {
  compound=true;
  rankdir=TB;
  subgraph cluster0 {
    identify_anomaly_data [shape=box];
    identify_missing_values [shape=box];
    subgraph cluster1 {
      Missing_Completely_At_Random [shape=box];
      Missing_At_Random [shape=box];
      Missing_Not_at_Random [shape=box];
      label= "Missing Value Analysis";
      Missing_Completely_At_Random->Missing_At_Random->Missing_Not_at_Random
    }
    either_imputation_or_omission [shape=box];
    communication_with_labs [shape=box];
    set_data_inclusion_exclusion_criteria [shape=box];

    label= "Data Quality Control";
    identify_anomaly_data->identify_missing_values
    identify_missing_values->Missing_Completely_At_Random [lhead=cluster1];
    Missing_Not_at_Random->either_imputation_or_omission->communication_with_labs->set_data_inclusion_exclusion_criteria;

  }
  subgraph cluster2 {
    Data_Transformation [shape=box];
    Log_Transformation [shape=box];
    Standardization [shape=box];
    label= "Data Preprocessing";
    Data_Transformation->
    Log_Transformation->
    Standardization;
  }
  set_data_inclusion_exclusion_criteria->Data_Transformation [lhead=cluster2];
}

```

For data quality control, I communicated with whom generated the data, classified missing values ​​and outliers according to laboratory standards, and labeled them. Based on the results through missing value analysis, I processed the missing values through consultation with the faculty members several times. For the data QC criteria, patients and variables whose ratio of missing values ​​for the sum of the rowwise and columnwise sums exceeded 5% for the sample size were excluded from the analysis. All metabolites data were standardized through log transformation and standardization.

### Methods

```{dot}
  digraph G {
    compound=true;
    rankdir=TB;
    subgraph cluster2 {
    Exploratory_Data_Analysis [shape=box];
    Data_Minig [shape=box];
    Statistical_Analysis [shape=box];
    Machine_Learning [shape=box];
    label= "Data Analytics";
    }
    
    Exploratory_Data_Analysis -> Data_Minig;
    Data_Minig -> Statistical_Analysis ;
    Statistical_Analysis -> Machine_Learning;
  }

```

Data analysis was performed in three stages: Exploratory Data Analysis (EDA), Statistical Analysis, and Machine Learning. In each stage, metabolites commonly associated with diseases were selected.

#### EDA and Data Mining

Student t tests, Wilcoxon Man Whiteney tests, $\chi^2$ tests, Fisher Exact Tests, ANOVAs, Kruskal Wallis Tests, and regression testing were performed, and I visualizaed data to reconfirm the test results. To visualize high-dimensional data and observe data patterns, KNN, PCA, K means, Clustering, and DB Scan were used.

#### Statistical Analysis

Multivariable linear regression, logistic regression, and Cox PH (Proportional Hazards) regression analyses were conducted and the metabolites that are signficantly associated with the disease status were selected. In order to reduce the possibility of making a type 1 error due to multiple testing, the significance was checked once more by calculating permuted p-values.

#### Machine Learning

Lasso, ridge regression, elastic net, decision tree, random rorests, ada boosting, gradient descent boosting, support vector machine (SVM), partial least square, and sparse partial least square were used. The optimal classifier was selected by evaluating the classifier that best predicted the disease status.

### Results & Conclusion

In the data consisting of 146 observations and about 3,000 variables, about 60 metabolites were observed to have a significant relationship with the disease at the 5% significance level, and partial least suare was observed to perform the best.

</div>