---
title: "Project Description"
subtitle: "Self Project Description"
description: "Due to security concerns, it is difficult to display the data used in this project. Therefore, I will generate fake data to reproduce and demonstrate a rough analysis pipeline. \n 보안 문제로 인해 이 프로젝트에서 사용된 데이터를 공유하기 어렵습니다. 따라서 대략적인 분석 파이프라인을 재현하고 시연하기 위해 가상의 데이터를 생성할 것입니다."
author: Kwangmin Kim
date: 2023-01-03
format: 
  html:
    toc: true  
    page-layout: full
    code-fold: true  
---
<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

## Introduction 

보안상의 이유로 프로젝트에서 사용됐던 실제 data를 사용하지 못하기 때문에 분석을 위해 사용됐던 방법론을 구체적으로 보여주기 어려웠다. 이에 따라 대략적인 분석 방식을 고차원의 서로 상관 관계가 있는 data를 simulation을 통해 만들어 보여주려고 한다.

## Goal

이 시뮬레이션 연구에서는 정규분포 하에서 대사 물질 데이터를 생성하여 대사 단계에서 가상의 데이터를 생성하는 데에만 집중할 것이다. 시뮬레이션 경험이 많지 않아 시뮬레이션이 수학적으로 통계적으로 틀린 부분이 있을 수 있다. 시뮬레이션은 내가 수행했던 분석 방법론을 간단히 재현하는 용도로 사용하는 것이라 시뮬레이션 자체에 많은 시간을 할애하진 않았다. 이 시뮬레이션 연구의 목표는 AD와 None AD와 관련된 biomarkers를 구별할 수 있는 일련의 예측인자(또는 대사물질 또는 생화학물질)를 식별하는데 사용됐던 방법론을 소개하는 것이다.

## Feature

* 보안 문제로 인해 이 프로젝트에 사용된 실제 데이터와 전체 분석 파이프라인을 보여주기 어렵다. 따라서 시뮬레이션을 통해 대략적인 분석 파이프라인을 재현 및 시연하기 위해 시뮬레이션 데이터를 생성한다.시뮬레이션 데이터는 실제 연구를 위해 표본으로 쓰인 sample 데이터의 분포를 전혀 반영하지 않았다.
* 이 시뮬레이션 연구에서, 실제 데이터의 분포를 반영하지 않았고 범주형 변수 및 연속형 변수와 종속 변수를 통계적으로 잘 연관시키지 못했기 때문에 분석 결과가 생물학적인 사실과 많이 다를 수 있다. 

## Development Environment

* Operating System
    * Window
    * Ubuntu 20.04
* Software
    * Quarto for dynamic documentation
    * VS code
    * R studio 2022.07.2+576
    * R base 4.2.2 used for coding in the Korean section
    * Python 3.11 used for coding in the English section


</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

## Introduction 

Because the actual data used in the project cannot be used for security reasons, it was difficult to show the methodology used for analysis in detail. Accordingly, I am going to show a rough analysis method through simulation of high-dimensional, mutually correlated data.

## Goal

In this simulation study, I will focus only on generating fake data at the metabolomic stage by generating data under multivariate normal distributions. The aim of this simulation study is to identify a set of predictors (or metabolites or bio-chemicals) that will enable to differentiate bio-markers that are associated with AD vs. non-AD.

## Feature

* In this article, due to security concerns, it is difficult to display the real data and the entire analysis pipeline used in this project. Therefore, I prepared simulated data to reproduce and demonstrate a rough analysis pipeline. The simulated data does not reflect the distribution of the truely sampled data used in the LLFS at all.
* In this simulation, since the categorical and continuous variables and the dependent variable could not be statistically associated properly, the analysis result for the discrete variables could be very different from the biological or medical fact.

## Development Environment

* Operating System
    * Window
    * Ubuntu 20.04
* Software
    * Quarto for dynamic documentation
    * VS code
    * R studio 2022.07.2+576
    * R base 4.2.2 used for coding in the Korean section
    * Python 3.11 used for coding in the English section

</div>



