---
title: Probability
subtitle: Set Thoery, Theory Errors, Calculus, Real Analysis, Measure Thoery
description: | 
  Probability for statistics, machine learning and deep learning.
categories:
  - Statistics
author: Kwangmin Kim
date: 02/05/2023
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}


## Terms

* experiment(실험): 연구 수행 방식.
* trial (시행): 연구 실험 시행.
* sample space(표본 공간, ($\text{S or } \Omega$): 실험의 가능한 모든 결과의 모음 또는 근원 사상의 집합.
* element (근원 사상, $\omega$): 표본 공간의 원소.
* event (사건, $E$): 근원 사상의 집합 또는 표본 공간의 부분 집합.

## Notations

* $\omega \in A$ : $\omega$ is an element of a set A
* $\omega \not\in A$ : $\omega$ is not an element of a set A
* $B \subset A$ : B is a subset of A, which means if $\omega \in B$, then $\omega \in A$
* $A = B$ : $B \subset A$, $A \subset B$
* $B \not\subset A$ : B is not a subset of A, which means if $\omega \in B$, then $\omega \not\in A$

## Overview

확률은 우연 (또는 가능성)과 불확실성에 대한 연구이다. 그 이론은 집합 이론을 기반으로 한다. 고전 확률은 가능성 조합 게임, 이론 오류와 같은 도박과 같다. 확률은 통계학, 경제학, 연산연구, 심리학, 생물학, 역학, 의학 등에 사용된다. 확률을 이해하기 위해 미적분학과 집합론의 지식이 요구되며 관련 학문은 ​​해석학, 측도론, 확률과정 등이 있다. 확률을 정의하려면 사건 수집에 대한 규칙성이 필요하다.

## Probability

* 확률은 사건이 발생할 가능성을 나타낸다.
* 고전적 정의

::: {#def-probability}

The probability of event A is the sum of the probabilities assigned to all sample points in event A. Therefore, $0 \le P(A) \le 1, P(\emptyset)=0, P(\Omega)=1$. In addition, if $A_1, A_2, A_3, ...$ are mutually exclusive, 

$$
P(A_1 \cup A_2 \cup A_3 \dots)=P(A_1) + P(A_2) + P(A_3) + \dots =\sum_{i=1}^{\infty}P(A_i)
$$

:::

위의 정의에서 *the probabilities assigned to all sample points in event A* 의 표현은 사건 A안에 있는 element의 가중치로 해석할 수 있다. 즉, 쉽게 말하면, 확률은 표본 공간, sample space $\Omega$ 의 원소 (element) $\omega$ 에 할당된 가중치를 더한 것이다.

예를 들어, 주사위 모양을 어떤식으로든 조작해 홀수가 짝수보다 2배 더 많이 발생하게끔 만들어 1 번 던질 때 3 보다 작은 수가 나올 사건을 A라고 하면 $\Omega=\{1,2,3,4,5,6\}$ 이고 각 홀수 원소에 가중치가 2배씩 붙기 때문에 홀수 눈이 발생할 확률은 $\frac{2x}{2x+x+2x+x+2x+x}=\frac{2}{9}$, 반면에, 짝수의 눈이 나올 확률은 $\frac{x}{2x+x+2x+x+2x+x}=\frac{1}{9}$ 이다. 이 때 확률은 위의 정의를 따라야 하므로

* $0\le P(evenNumber)=\frac{2}{9}, P(oddNumber)=\frac{1}{9}\le 1$ 이고 
* $P(\Omega=\{1,2,3,4,5,6\})=P(evenNumbers)+P(oddNumbers)=1$ 

이므로 확률이라고 할 수있다. 

* 그러므로 $P(A={1,2})=P(1)+P(2)=\frac{2}{9}+\frac{1}{9}=\frac{3}{9}$ 이다.

::: {#thm-eqaullyLikely}

Countable sample space $\Omega$ consists of $N$ distinctive equally likely elements (i.e. $n(S)=N$), and an event $A$ is a subset of the sample space. The event A consists of $n$ distinctive equally likely elements (i.e. $n(A)=n$). Then 
$$
P(A)=\frac{n}{N}
$$

:::

element가 오직 동일한 확률로 발생할 때에만 (equally likely), 확률은 $\frac{n(A)}{n(\Omega \space or \space S)}$ 의 비율(proportion)로 표현될 수 있다.

예를 들어, 주사위의 눈이 3 보다 작은 수가 나올 사건을 A라고 하면 $P(A)= \frac{n(A)}{n(S)}=\frac{n(\{1,2\})}{n(\{1,2,3,4,5,6\})}=\frac{2}{6}$ 가 된다.

::: {#thm-inftyEquallyLikely}

If in $N$ identical and independent repeated experiments, an event $A$ happens $n$ times, the the probability of $A$ is defined by
$$
P(A)=\lim_{N\to\infty}\frac{n}{N}
$$

:::

::: {#thm-basic}

Basic probability theorem: the complement and additive rule.
$$
\begin{aligned}
P(E^c)&=1-P(E) \\
P(E_1 \cup E_2)&= P(E_1) + P(E_2) - P(E_1 \cap E_2) \\
\end{aligned}
$$

$E_1$ and $E_2$ are mutually exclusive.
:::

::: {#thm-additiveRule}

Generalized additive rule
$$
\begin{aligned}

\end{aligned}
$$


:::

나머지는 확률 이론 서적을 살펴 보길 바란다.

:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

## Terms

* experiment: the way carry out a study, study design.
* trial: study experiment trial.
* sample space ($\text{S or } \Omega$): the set of all possible elements (i.e. the collection of all possible outcomes of an experiment).
* element ($\omega$): each outcome of sample space, it is also called 'sample point'.
* event ($E$): a set of sample points or outcomes or a subset of sample space.

## Notations

* $\omega \in A$ : $\omega$ is an element of a set A
* $\omega \not\in A$ : $\omega$ is not an element of a set A
* $B \subset A$ : B is a subset of A, which means if $\omega \in B$, then $\omega \in A$
* $A = B$ : $B \subset A$, $A \subset B$
* $B \not\subset A$ : B is not a subset of A, which means if $\omega \in B$, then $\omega \not\in A$

## Overview

Probability is on study of chance and uncertainty. Its theory builds on set theory. Classic probability is like a gambling of combinatorial games of chance, theory errors. Probability is used in statistics, economics, operation research, psychology, biology, epidemiology, medicine, etc. The prerequisite for probability is calculus and set theory, and the related study is real analysis, measure theory, and stochastic process. To define probability, some regularity on the collection of events is required. 


## Probability

* probability shows the possibility of the occurrence of an event.
* classic definition
::: {#def-classic}

Countable sample space $\Omgega$ consists of $N$ distinctive equally likely elements (i.e. $n(S)=N$), and an event $A$ is a subset of the sample space. The event A consists of $n$ distinctive equally likely elements (i.e. $n(A)=n$). Then 
$$
P(A)=\frac{n}{N}
$$

:::

::: {#thm-classic}

If in $N$ identical and independent repeated experiments, an event $A$ happens $n$ times, the the probability of $A$ is defined by
$$
P(A)=\lim_{N\to\infty}\frac{n}{N}
$$

:::

* The case of the sample space consisting of $N$ distinctive not equally likely elements,
* The case of the uncountable sample space 
*
*
*
*
*
*
*
*
*
*
*

:::


</div>



## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)



