<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="dcterms.date" content="2023-04-22">
<meta name="description" content="This project is necessary for entering global markets to prepare for the requirement of the government all around the world. Due to security concerns, it is difficult to display the data used in this project.">

<title>Kwangmin Kim - Project (ongoing): Diagnostic Signal Processing Algorithm Validation for Surveilance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/CV/index.html">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/projects/index.html">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/blog/index.html">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">
 <span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"><i class="bi bi-github" role="img" aria-label="Github">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"><i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/blog/index.html"><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project (ongoing): Diagnostic Signal Processing Algorithm Validation for Surveilance</h1>
<p class="subtitle lead">Seegene’s Top Priority Project</p>
</div>

<div>
  <div class="description">
    This project is necessary for entering global markets to prepare for the requirement of the government all around the world. Due to security concerns, it is difficult to display the data used in this project.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kwangmin Kim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 22, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<ul class="nav nav-pills" id="language-tab" role="tablist">
<li class="nav-item" role="presentation">
<button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">
Korean
</button>
</li>
<li class="nav-item" role="presentation">
<button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">
English
</button>
</li>
<div class="tab-content" id="language-tabcontent">

<div id="Korean" class="tab-pane fade show active" role="tabpanel" aria-labelledby="Korean-tab">
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<ul>
<li>의료 장비와 연관된 시약 제품의 특성상 Global Market 진출시 각 나라의 정부에서 자국민의 건강 및 생명의 안전을 위해 요구하는 규제사항들이 있다.
<ul>
<li>시약의 안정성 검증 요구</li>
<li>장비의 안정성 검증 요구</li>
<li>Software의 안정성 검증 요구</li>
<li><strong>Diagnostic Algorithm의 안정성 검증 요구</strong></li>
</ul></li>
<li>COVID19 특수 시기 해제 후 Global market으로 진입 및 유지를 위해 제품의 안정성 검증이 각 국의 정부로 부터 요구된다. 그 중 가장 엄격한 기준을 요구하는 미국의 FDA와 캐나다의 Health Canada를 기준으로 진단 알고리즘의 안정성 검증 문서를 기획하고 작성해야만 한다.</li>
<li>시간이 지날 수록 각 국에서 Software 및 algorithms에 대한 규제가 강화되고 있기때문에 기존의 Software Engineering에 의한 안전성 검증보다 더 엄격한 Advanced Testing이 요구되고 있다.</li>
</ul>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<ul>
<li>algorithm이 안전한 성능을 발휘한다는 것을 증명한다</li>
<li>algorithm이 risk 관리가 가능하다는 것을 증명한다.</li>
</ul>
</section>
<section id="strategies" class="level2">
<h2 class="anchored" data-anchor-id="strategies">Strategies</h2>
<ul>
<li>세계에서 가장 엄격한 검열 인증서를 발급 및 교육을 제공하는 기업인 SGS의 guidance를 참고한다.</li>
<li>SGS는 FDA를 target으로 guidance를 제공한다.</li>
<li>Software의 안전성 검증을 위해 FDA에서 제공하는 General Principles of Software Validation 문서를 정독 후 이 문서를 기반으로 기획 및 작성한다.</li>
<li>Structural Testing와 Advanced Testing 모두 포함한다.</li>
<li>algorithm 안전성에 대한 정의와 논리를 확립한다.</li>
<li>algorithm 안전성에 대한 지표를 확립한다.</li>
<li>Software engineering은 General Principles of Software Validation 문서를 기반하여 수행한다.</li>
<li>Advanced Testing인 Statistical Testing은 data scientist의 창의성이 요구되는 작업으로 Testing Model을 기획하여 statistical analysis design을 한다.</li>
<li>기획된 Testing model에 적합한 statistical model을 찾고 biological experiment design과 engineering design을 한다.</li>
</ul>
</section>
<section id="issues" class="level2">
<h2 class="anchored" data-anchor-id="issues">Issues</h2>
<ul>
<li>선례 및 template를 찾을 수 없을 정도로 매우 드물다.</li>
</ul>
</section>
<section id="required-skills" class="level2">
<h2 class="anchored" data-anchor-id="required-skills">Required Skills</h2>
<ul>
<li>FDA software validation</li>
<li>Statistics</li>
<li>Dynamic documentation</li>
<li>Biology</li>
<li>Clinical study design</li>
</ul>
</section>
<section id="colaborators" class="level2">
<h2 class="anchored" data-anchor-id="colaborators">Colaborators</h2>
<ul>
<li>project owner (me)</li>
<li>7 data scientists</li>
<li>1 data enineer</li>
<li>27 biologists</li>
<li>2 patent attoneys</li>
</ul>
</section>
<section id="acheivements" class="level2">
<h2 class="anchored" data-anchor-id="acheivements">Acheivements</h2>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Noise Test</th>
<th style="text-align: left;">As-Is</th>
<th style="text-align: left;">To-Be</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sample Size</td>
<td style="text-align: left;">n=100</td>
<td style="text-align: left;">2552번의 실험에서 얻은 신호 n=61,248</td>
</tr>
<tr class="even">
<td style="text-align: center;">Evaluation Metrics</td>
<td style="text-align: left;">2 metrics</td>
<td style="text-align: left;">10 metrics ( the exsting 2 metrics + new 8 metrics)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Input Process</td>
<td style="text-align: left;">manually copy &amp; paste data of excel files extracted from a certain program</td>
<td style="text-align: left;">Web-Based Automation, upload multiple experiment files</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output Process</td>
<td style="text-align: left;">Batch Evaluation method, if even one of the signals from the equipment fails, the equipment fails. (Blind Spot: If there is one human error signal, the equipment is unconditionally disqualified.)</td>
<td style="text-align: left;">Differential Evaluation method, The signals from the equipment are scored, the average value is obtained, and the equipment is graded A+, A, B, and F. Failed if F. Robust on the error signal as it excludes the error signal from evaluation</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 1</td>
<td style="text-align: left;">pass: 92.58%, fail: 7.42%</td>
<td style="text-align: left;">A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output 2</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Visualized Plots and Tables.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 3</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Normal Signals, Human Errors, Device Errors, Manufacturing Errors</td>
</tr>
<tr class="even">
<td style="text-align: center;">Time Consumed</td>
<td style="text-align: left;">About 30 minutes per 20 experiments</td>
<td style="text-align: left;">About 25 minutes per 2552 experiments</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Data Management</td>
<td style="text-align: left;">Non-standard management method (stored in NAS directory in a different form as an Excel file in a different way for each worker)</td>
<td style="text-align: left;">Automatic loading in DB in standardized form by a scheduler (equipment failure tracing analysis becomes possible)</td>
</tr>
</tbody>
</table>
<section id="remarkable" class="level3">
<h3 class="anchored" data-anchor-id="remarkable">Remarkable</h3>
</section>
</section>
</div>
<div id="English" class="tab-pane fade" role="tabpanel" aria-labelledby="English-tab">
<section id="background-1" class="level2">
<h2 class="anchored" data-anchor-id="background-1">Background</h2>
<ul>
<li>Quality Control of diagnostic equipment is one of the necessities for the regulations required by the government of each country when entering the global market due to the nature of products related to medical equipment.
<ul>
<li>Reagent stability verification &amp; validation required</li>
<li><strong>Equipment stability verification &amp; validation request</strong></li>
<li>Software stability verification &amp; validation request</li>
<li>Stability Verification &amp; validation Request of Diagnostic Algorithm</li>
</ul></li>
<li>Since the diagnostic equipment currently being used by Seegene is not its own product, it is difficult to manage the quality of the diagnostic equipment.</li>
<li>The noise test of PCR equipment is one of the QC processes of medical equipments, and it is a quality verification system that directly affects the performance stability of Seegene’s reagent products.</li>
<li>As the size of the company grows and frequent organizational reshuffles result in manual noise tests being transferred to various departments, the noise test performers’ understanding and skills are low, resulting in noise tests not being performed correctly.</li>
<li>A project to automate the noise test was selected for Seegene’s long-term goal of enterprise automation.</li>
</ul>
</section>
<section id="objective-1" class="level2">
<h2 class="anchored" data-anchor-id="objective-1">Objective</h2>
<ul>
<li>Data-driven parameters obtained from 61,248 signals from 2552 experiments were used to evaluate 2201 PCR devices, which were stocked between 2020.12.19 and 2021.03.06. yield Enables continuous analysis of equipment performance over time.</li>
<li>Improve the following major problems:
<ul>
<li>Improved metrics that produces erroneous results by greatly affecting the noise test result depending on the size of the signal amplification.</li>
<li>It relieves the burden on the field department with a robust evaluation system by supplementing the problem of unconditionally determining equipment rejection in response to a simple human error signal.</li>
<li>Equipment error signals are labeled by finding patterns that occur in equipment.</li>
</ul></li>
<li>The time required for the manual calculation process can be reduced from 30 minutes per 20 tests to about 2 to 3 minutes with web-based automation.</li>
<li>By making it the best practice of Seegene’s full automation, establish and vitalize the cooperation system between the IT, manufacturing and BT sectors.</li>
<li>Visualization and noise test result history are provided to build a tracking and VOC response system.</li>
</ul>
</section>
<section id="strategies-1" class="level2">
<h2 class="anchored" data-anchor-id="strategies-1">Strategies</h2>
<section id="strategy-a" class="level3">
<h3 class="anchored" data-anchor-id="strategy-a">Strategy A</h3>
<ul>
<li>The QC process is subdivided through close communication with the field departments, and the results of the noise test, which is the next stage QC, are predicted by utilizing the data generated in the previous stage QC.</li>
<li>Noise test omitted only for devices that are certain to have low noise.</li>
</ul>
</section>
<section id="strategy-b" class="level3">
<h3 class="anchored" data-anchor-id="strategy-b">Strategy B</h3>
<ul>
<li>Automate or semi-automate the entire QC process</li>
<li>Improve the accuracy of inspection results by analyzing the existing noise measurement metric and creating a new metric</li>
<li>Visualization and noise test result history are provided to increase the understanding of practitioners and enable management</li>
</ul>
</section>
</section>
<section id="issues-1" class="level2">
<h2 class="anchored" data-anchor-id="issues-1">Issues</h2>
<ul>
<li>Absence of job description</li>
<li>Backup Mistakes by Practitioners</li>
<li>Data scattered across departments</li>
<li>High level of data cleansing
<ul>
<li>Select data that can be analyzed from practitioner data</li>
<li>Incorrect input of practitioner data</li>
<li>Manual release of DRM for data and documents</li>
</ul></li>
<li>reverse engineering required</li>
<li>Absence of contact system for related personnel and departments due to frequent organizational reshuffle</li>
</ul>
</section>
<section id="required-skills-1" class="level2">
<h2 class="anchored" data-anchor-id="required-skills-1">Required Skills</h2>
<ul>
<li>Back-end Engineering for DevOps Pipeline Construction</li>
<li>Data Engineering for data cleansing and reverse engineering</li>
<li>Data Modeling for a RDB system construction</li>
<li>Statistical Analysis for the noise test performance verification</li>
<li>Machine Learning for pattern analysis</li>
<li>Front-end Engineering for UI/UX construction</li>
<li>Biologics, Biophysics, Physics Knowledge</li>
</ul>
</section>
<section id="colaborators-1" class="level2">
<h2 class="anchored" data-anchor-id="colaborators-1">Colaborators</h2>
<ul>
<li>1 data scientist (me) - project owner</li>
<li>5 mechanical engineers</li>
<li>4 biologists</li>
<li>2 patent attoneys</li>
<li>2 data engineers</li>
<li>3 full stack developers</li>
<li>1 advisor (a professor of Computer Science at Seoul National University)</li>
</ul>
</section>
<section id="acheivements-1" class="level2">
<h2 class="anchored" data-anchor-id="acheivements-1">Acheivements</h2>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Noise Test</th>
<th style="text-align: left;">As-Is</th>
<th style="text-align: left;">To-Be</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sample Size</td>
<td style="text-align: left;">n=100</td>
<td style="text-align: left;">Signals from 2552 experiments, n=61,248</td>
</tr>
<tr class="even">
<td style="text-align: center;">Evaluation Metrics</td>
<td style="text-align: left;">2 metrics</td>
<td style="text-align: left;">10 metrics ( the exsting 2 metrics + new 8 metrics)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Input Process</td>
<td style="text-align: left;">manually copy &amp; paste data of excel files extracted from a certain program</td>
<td style="text-align: left;">Web-Based Automation, upload multiple experiment files</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output Process</td>
<td style="text-align: left;">Batch Evaluation method, if even one of the signals from the equipment fails, the equipment fails. (Blind Spot: If there is one human error signal, the equipment is unconditionally disqualified.)</td>
<td style="text-align: left;">Differential Evaluation method, The signals from the equipment are scored, the average value is obtained, and the equipment is graded A+, A, B, and F. Failed if F. Robust on the error signal as it excludes the error signal from evaluation</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 1</td>
<td style="text-align: left;">pass: 92.58%, fail: 7.42%</td>
<td style="text-align: left;">A+ (pass): 7.01%, A (pass): 12.91%, B (pass): 75.72%, F (fail): 4.36%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Output 2</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Visualized Plots and Tables.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Output 3</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Normal Signals, Human Errors, Device Errors, Manufacturing Errors</td>
</tr>
<tr class="even">
<td style="text-align: center;">Time Consumed</td>
<td style="text-align: left;">About 30 minutes per 20 experiments</td>
<td style="text-align: left;">About 25 minutes per 2552 experiments</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Data Management</td>
<td style="text-align: left;">Non-standard management method (stored in NAS directory in a different form as an Excel file in a different way for each worker)</td>
<td style="text-align: left;">Automatic loading in DB in standardized form by a scheduler (equipment failure tracing analysis becomes possible)</td>
</tr>
</tbody>
</table>
<section id="remarkable-1" class="level3">
<h3 class="anchored" data-anchor-id="remarkable-1">Remarkable</h3>
<ul>
<li>The noise test was abolished in the whole QC Process because I statistically proved that the noise test result does not have a significant impact on the difference of the mean of the final result in the whole diagnostic process at the 1% significance level.</li>
<li>It turned out to be an opportunity for the Data Science department to increase their understanding of experiments and data generated from equipment.</li>
<li>It served as the basis for building a company-wide DB and building a platform architecture.</li>
</ul>
</section>
</section>
</div>



</div></ul></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>