---
title: "Mosaic Package"
subtitle: "plotFun()"
description: |
  template
categories:
  - Language
author: Kwangmin Kim
date: 03/31/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
comments: 
  utterances: 
    repo: ./docs/comments
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}
## plotFun()

수식 base로 함수를 그릴 수 있는 package

```{r}
library(tidyverse)
library(mosaic)

rm(list=ls())
```

```{r}
plotFun(x1^2~x1,
x1.lim=range(-10,10),
x2.lim=range(-10,10),
surface=TRUE,
# surface=FALSE, # contour 를 보여줌
xlab=expression(x[1]),
ylab=expression(f(x)))

plotFun(5*x1^2~x1 & x2,
x1.lim=range(-10,10),
x2.lim=range(-10,10),
surface=TRUE,
xlab=expression(x[1]),
ylab=expression(x[2]),
zlab=expression(f(x[1],x[2])))
```

그려진 그래프를 R studio에선 plot의 톱니바퀴를 누르면 축별로 회전이 가능하지만 vs code에서는 지원이 안되는 것 같음

:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>

```{python}
#| echo: false
#| eval: true
radius = 10
from IPython.display import display, Markdown
display(Markdown("""
The radius of the circle is {radius}.
""".format(radius = radius)))
```


# Go to Project Content List

[Project Content List](./docs/projects/index.qmd)

# Go to Blog Content List

[Blog Content List](../../content_list.qmd)