---
title: Geometric Distribution
subtitle: Exponential Family
description: | 
 
categories:
  - Statistics
author: Kwangmin Kim
date: 02/27/2023
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}



## Geometric Distribution

::: {#def-Geometric}

성공 확률이 $p$ 인 independent Bernoulli trials을 시행할 때 첫 성공할때까지의 시행 횟수를 확률 변수 $X$ 로 갖는 분포를 geometric distribution이라고 하고 $X$ 의 probability mass function은 
$$
\begin{aligned}
  f_X(x;p)&=p(1-p)^{x-1}
\end{aligned}
$$ 
이다.  (단, $x=1,2,...$)

:::

### Expectation

$$

\begin{aligned}
  \text{E}(X)&=\sum_{x=1}^{\infty} x f(x)\\
             &=\sum_{x=1}^{\infty} x pq^{x-1} &\text{ }(q=1-p)\\
             &=p\sum_{x=1}^{\infty} x q^{x-1} \\
             &=p\frac{d}{dx}\sum_{x=1}^{\infty} q^{x} \\
             &=p\frac{d}{dx}\frac{q}{1-q} \\
             &=p\frac{d}{dx}\frac{(1-q)+q}{(1-q)^2} \\
             &=p\frac{d}{dx}\frac{(1-q)+q}{p^2} \\
             &=p\frac{1}{p^2}\\
             &=\frac{1}{p}

\end{aligned}

$$ 


### Variance

$$
\begin{aligned}
  \text{E}(X(X-1))&=\sum_{x=1}^{\infty}x(x-1)pq^{x-1}\\
                  &=pq\sum_{x=1}^{\infty}x(x-1)q^{x-2}\\
                  &=pq\sum_{x=1}^{\infty}\frac{d^2}{dq^2}q^{x}\\
                  &=pq\frac{d^2}{dq^2}\sum_{x=1}^{\infty}q^{x}\\
                  &=pq\frac{d^2}{dq^2}(\frac{1}{1-q})\\
                  &=pq\frac{d}{dq}(\frac{1}{(1-q)^2})\\
                  &=pq(\frac{2(1-q)}{(1-q)^4})\\
                  &=\frac{2q}{p^2}\\
  \text{E}(X^2)&=\frac{2q}{p^2}+\text{E}(X)=\frac{2q}{p^2}+\frac{1}{p}\\
  \text{Var}(X)&=\text{E}(X^2)-\text{E}(X)^2\\
               &=\frac{2q}{p^2}+\frac{1}{p}-\frac{1}{p^2}\\
               &=\frac{1-p}{p^2}\\
\end{aligned}
$$ 


### Example

한 장비 제조 업체에서 사람의 건강과 생명을 진단하는데 사용되는 medical device가 1000 개마다 평균 2개 꼴로 불량이 발생한다고 가정할 때 그 장비를 공급받는 구매자가 medical device의 공급 업체의 불량 평가 기준으로 quality control을 1대 씩 진행할 때 불량 장비가 3번째 검사에서 발생할 확률은


$$
\begin{aligned}
   \text{f}(X=3,\frac{2}{1000})&=(\frac{998}{1000})^2\frac{2}{1000}\\
\end{aligned}
$$
이다. 평균과 분산 각 각 $(\frac{2}{1000})^{-1}$, $\frac{1-\frac{2}{1000}}{(\frac{2}{1000})^2}$ 이다.

:::

</div>


## Blog Guide Map Link

* [Statistics Blog](../guide_map/index.qmd)
* [Engineering Blog](../../Engineering/guide_map/index.qmd)
* [Deep Learning Blog](../../DL/guide_map/index.qmd)
* [Machine Learning Blog](../../ML/guide_map/index.qmd)
* [Mathematics Blog](../../Mathmatics/guide_map/index.qmd)
* [Patent Blog](../../Patent/guide_map/index.qmd)
* [Validation Blog](../../Validation/guide_map/index.qmd)



